import {newId} from "./geo";
import parks from "./parks.json";
import campgrounds from "./campgrounds.json";
import type {Place,Trip,Layer,PlaceKind} from "./types";
import {DEFAULT_PREFERENCES} from "./types";
export const CATEGORY_LABELS:Record<PlaceKind,string>={park:"National park",monument:"National monument",recreation:"Recreation area",statepark:"State park",camp:"Campground",fuel:"Fuel station",ev:"EV charging",scenic:"Viewpoint",waterfall:"Waterfall",trail:"Trail",historic:"Historic place",museum:"Museum",attraction:"Attraction",food:"Food",cave:"Cave",hotspring:"Hot spring",land:"Public land",city:"Destination"};
export const REFERENCE_PLACES:Place[]=[...(parks as Place[]),...(campgrounds as unknown as Place[]),{id:"paris-tx",name:"Paris, Texas",coordinates:[-95.5555,33.6609],kind:"city",region:"TX",source:"Reference location"},{id:"santa-fe",name:"Santa Fe, New Mexico",coordinates:[-105.9378,35.6870],kind:"city",region:"NM",source:"Reference location",description:"An adobe city in the high desert, with art, architecture, and a good reason to stay another night."}];
function futureDate(days:number){const d=new Date();d.setDate(d.getDate()+days);return d.toISOString().slice(0,10);}
export function createDemoTrip():Trip{const ids=["paris-tx","santa-fe","grca","zion","deva","yose"];return{id:newId(),name:"The long way west",stops:ids.map((id,i)=>({...REFERENCE_PLACES.find(p=>p.id===id)!,stopId:newId(),date:futureDate(3+i*3)})),startDate:futureDate(3),endDate:futureDate(20),notes:"Take the scenic way. Leave room for an unplanned stop.",savedPlaces:[],placeNotes:{},preferences:{...DEFAULT_PREFERENCES},modifiedAt:new Date().toISOString()};}
export function createEmptyTrip():Trip{return{id:newId(),name:"An open road",stops:[],startDate:"",endDate:"",notes:"",savedPlaces:[],placeNotes:{},preferences:{...DEFAULT_PREFERENCES},modifiedAt:new Date().toISOString()};}
export const INITIAL_LAYERS:Layer[]=[{id:"national-parks",label:"National parks",group:"Parks & public lands",kind:"park",enabled:true},...([
 ["monuments","National monuments","monument"],["recreation","Recreation areas","recreation"],["state-parks","State parks","statepark"],["public-lands","Protected / public lands","land"],["campgrounds","Campgrounds","camp"],["fuel","Fuel stations","fuel"],["ev","EV chargers","ev"],["scenic","Viewpoints","scenic"],["attractions","Attractions","attraction"],["historic","Historic places","historic"],["museums","Museums","museum"],["trails","Trails & trailheads","trail"],["waterfalls","Waterfalls","waterfall"],["caves","Caves","cave"],["springs","Hot springs","hotspring"],["food","Food stops","food"]
] as [string,string,PlaceKind][]).map(([id,label,kind])=>({id,label,kind,group:["monument","recreation","statepark","land"].includes(kind)?"Parks & public lands":kind==="camp"?"Camping":"Along the road",enabled:kind==="camp"})),...([ ["weather","Route weather"],["alerts","Weather alerts"],["fire","Satellite fire detections"],["air","Air quality"],["river","River / flood conditions"],["roads","Closures & construction"] ]).map(([id,label])=>({id,label,group:"Conditions",enabled:false}))];
