import type {Trip,Route} from "./types";
import {buildMapStyle,addRouteLayers,loadMapLibre} from "./map-style";
import {boundsOf,formatMiles,formatDrive} from "./geo";
import {renderRaster} from "./raster";
export type ExportLayout="landscape"|"portrait"|"map";
function wrap(ctx:CanvasRenderingContext2D,text:string,x:number,y:number,width:number,lineHeight:number,maxLines=3){const words=text.split(/\s+/);let line="",lines=0;for(const word of words){const test=line?line+" "+word:word;if(ctx.measureText(test).width>width&&line){ctx.fillText(line,x,y);y+=lineHeight;lines++;if(lines>=maxLines)return y;line=word;}else line=test;}if(line)ctx.fillText(line,x,y);return y+lineHeight;}
export async function exportTrip(trip:Trip,route:Route|null,layout:ExportLayout):Promise<void>{if(!route)throw Error("Create a driving route before exporting your trip.");const width=layout==="portrait"?1080:1920,height=layout==="portrait"?1920:1080;const gl=await loadMapLibre(),style=await buildMapStyle("atlas");const host=document.createElement("div");host.style.cssText=`position:fixed;left:-10000px;top:0;width:${width}px;height:${height}px;pointer-events:none;`;document.body.appendChild(host);let map:import("maplibre-gl").Map|undefined;
 try{await document.fonts.ready;
 const canvas=document.createElement("canvas");canvas.width=width;canvas.height=height;const ctx=canvas.getContext("2d")!;
 const pad=layout==="portrait"?{top:360,bottom:470,left:100,right:100}:layout==="map"?{top:115,bottom:170,left:150,right:150}:{top:245,bottom:280,left:130,right:130};
 let attribution="© OpenStreetMap contributors";
 let project:(p:import("./types").Coordinate)=>{x:number;y:number};
 if(document.createElement("canvas").getContext("webgl2")){
  try{map=new gl.Map({container:host,style,center:trip.stops[0].coordinates,zoom:4,interactive:false,attributionControl:false,canvasContextAttributes:{preserveDrawingBuffer:true,antialias:true}});await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>reject(Error("Map loading timed out.")),16000);map!.once("load",()=>{clearTimeout(timer);resolve();});});addRouteLayers(map,route.coordinates);map.setPaintProperty("trip-route-main","line-width",7);map.setPaintProperty("trip-route-edge","line-width",12);const bounds=boundsOf(route.coordinates);map.fitBounds([[bounds[0],bounds[1]],[bounds[2],bounds[3]]],{padding:pad,duration:0,maxZoom:12});await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>reject(Error("Map tiles timed out.")),16000);map!.once("idle",()=>{clearTimeout(timer);resolve();});map!.triggerRepaint();});ctx.drawImage(map.getCanvas(),0,0,width,height);attribution=style.sources.base?"© OpenStreetMap contributors":"© OpenStreetMap contributors · OpenFreeMap";project=p=>map!.project(p);
  }catch{map?.remove();map=undefined;project=await renderRaster(canvas,route.coordinates,pad);}
 }else project=await renderRaster(canvas,route.coordinates,pad);
 const gradient=ctx.createLinearGradient(0,0,0,height);gradient.addColorStop(0,"#10251fed");gradient.addColorStop(.26,"#10251f20");gradient.addColorStop(.65,"#10251f00");gradient.addColorStop(1,"#10251ff5");ctx.fillStyle=gradient;ctx.fillRect(0,0,width,height);
 for(let i=0;i<trip.stops.length;i++){const stop=trip.stops[i],p=project(stop.coordinates);const x=p.x,y=p.y;ctx.beginPath();ctx.arc(x,y,layout==="portrait"?22:20,0,Math.PI*2);ctx.fillStyle="#c4f17b";ctx.fill();ctx.lineWidth=4;ctx.strokeStyle="#142b20";ctx.stroke();ctx.fillStyle="#182c20";ctx.font="600 21px 'DM Sans', Arial";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(String(i+1),x,y);ctx.textAlign="left";ctx.textBaseline="alphabetic";}
 const margin=layout==="portrait"?72:86;ctx.fillStyle="#c4f17b";ctx.font="600 27px 'DM Sans',Arial";ctx.fillText("Trippr",margin,layout==="map"?70:76);ctx.fillStyle="#c5d1bc";ctx.font="17px 'DM Sans',Arial";ctx.textAlign="right";ctx.fillText("A SAFISOLUTIONS PROJECT",width-margin,76);ctx.textAlign="left";
 if(layout!=="map"){ctx.fillStyle="#f0f3e9";ctx.font=`${layout==="portrait"?76:82}px 'DM Serif Display',Georgia`;wrap(ctx,trip.name||"An open road",margin,layout==="portrait"?178:183,width-margin*2,90,2);}
 const bottom=layout==="portrait"?height-358:height-235;ctx.fillStyle="#f0f3e9";ctx.font="500 39px 'DM Sans',Arial";ctx.fillText(`${formatMiles(route.distance)} miles`,margin,bottom);ctx.fillStyle="#b8c7b0";ctx.font="24px 'DM Sans',Arial";ctx.fillText(`${formatDrive(route.duration)} driving  ·  ${trip.stops.length} stops`,margin,bottom+43);if(trip.startDate){ctx.font="20px 'DM Sans',Arial";ctx.fillText(`${trip.startDate}${trip.endDate?` to ${trip.endDate}`:""}`,margin,bottom+80);}
 ctx.font="21px 'DM Sans',Arial";ctx.fillStyle="#e0e9d7";const names=trip.stops.map((s,i)=>`${i+1}. ${s.name.replace(/ National Park( & Preserve)?$/g,"")}`).join("  ·  ");wrap(ctx,names,margin,bottom+(trip.startDate?121:95),width-2*margin,33,layout==="portrait"?5:3);
 ctx.fillStyle="#b0bea7";ctx.font="15px 'DM Sans',Arial";ctx.fillText("Map "+attribution+" · Route: "+route.source,margin,height-35);ctx.textAlign="right";ctx.fillText("Driving estimates exclude live traffic and closures.",width-margin,height-61);ctx.textAlign="left";
 const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error("The image could not be created.")),"image/png"));const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`${(trip.name||"Trippr").replace(/[^a-z0-9]+/gi,"-").replace(/^-|-$/g,"")}-${layout}.png`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);
 }finally{map?.remove();host.remove();}
}
