import type {Coordinate,Place} from "./types";
import {validCoordinate} from "./geo";
type Remote=(url:string,options?:RequestInit)=>Promise<any>;
export async function publicLands(b:number[],stateOnly:boolean,remote:Remote):Promise<Place[]>{
 const root="https://edits.nationalmap.gov/arcgis/rest/services/PAD-US/PAD_US_4_1/MapServer/0";
 const q=new URLSearchParams({f:"geojson",where:stateOnly?"UPPER(Unit_Nm) LIKE '%STATE PARK%' OR UPPER(Loc_Nm) LIKE '%STATE PARK%'":"1=1",geometry:b.join(","),geometryType:"esriGeometryEnvelope",inSR:"4326",outSR:"4326",spatialRel:"esriSpatialRelIntersects",outFields:"OBJECTID,Loc_Nm,Unit_Nm,Mang_Name,Mang_Type,Pub_Access,Src_Date,State_Nm",returnGeometry:"true",maxAllowableOffset:"0.003",resultRecordCount:"250"});
 const d=await remote(root+"/query?"+q);if(!Array.isArray(d.features))throw Error("Public land boundaries are unavailable.");
 return d.features.filter((f:any)=>["Polygon","MultiPolygon"].includes(f.geometry?.type)).map((f:any)=>{const p=f.properties||{},rings=f.geometry.type==="Polygon"?f.geometry.coordinates:f.geometry.coordinates.flat(),points=rings.flat() as Coordinate[];let west=180,east=-180,south=90,north=-90;for(const c of points){west=Math.min(west,c[0]);east=Math.max(east,c[0]);south=Math.min(south,c[1]);north=Math.max(north,c[1]);}const name=p.Unit_Nm||p.Loc_Nm||"Protected land",access=({OA:"Open access",RA:"Restricted access",XA:"Closed access",UK:"Access unknown"} as Record<string,string>)[p.Pub_Access]||"Access unknown";return{id:`padus-${p.OBJECTID||f.id}`,name,kind:/state park/i.test(name)||stateOnly?"statepark":"land",coordinates:[(west+east)/2,(south+north)/2],region:p.State_Nm,source:"USGS PAD-US 4.1 ⋅ reference boundaries",sourceUrl:root,description:`Manager: ${p.Mang_Name||"not reported"}. ${access} in the source inventory. Boundaries and access are reference information; check the land manager before visiting or camping.`,tags:{manager:p.Mang_Name||"Unknown",access:access},geometry:f.geometry} as Place;}).filter((p:Place)=>validCoordinate(p.coordinates));
}
export async function recreationFacilities(p:Coordinate,radius:number,key:string,remote:Remote):Promise<Place[]>{
 const q=new URLSearchParams({latitude:String(p[1]),longitude:String(p[0]),radius:String(Math.min(50,radius)),limit:"200",full:"true",apikey:key});const d=await remote("https://ridb.recreation.gov/api/v1/facilities?"+q);if(!Array.isArray(d.RECDATA))throw Error("Recreation.gov facilities are unavailable.");
 return d.RECDATA.filter((f:any)=>validCoordinate([Number(f.FacilityLongitude),Number(f.FacilityLatitude)])&&/campground|camping/i.test(f.FacilityTypeDescription||f.FacilityName||"")).map((f:any):Place=>({id:`ridb-${f.FacilityID}`,name:f.FacilityName,kind:"camp",coordinates:[Number(f.FacilityLongitude),Number(f.FacilityLatitude)],source:"Recreation.gov / RIDB ⋅ reference facility",updated:f.LastUpdatedDate,description:String(f.FacilityDescription||"").replace(/<[^>]*>/g," ").replace(/&nbsp;/g," ").replace(/\s+/g," ").trim(),website:f.FacilityReservationURL||undefined,sourceUrl:"https://ridb.recreation.gov/",amenities:{Classification:"Recreation.gov facility",Tents:null,"RV / caravan":null,Restrooms:null,"Drinking water":null,Showers:null,Electricity:null,"Dump station":null,Reservations:typeof f.Reservable==="boolean"?f.Reservable:null,Elevation:null}}));
}
