import { validCoordinate, milesBetween, sampleLine, distanceToRoute, boundsOf } from "@/lib/trippr/geo";
import { publicLands, recreationFacilities } from "@/lib/trippr/government";
import type { Coordinate, Place, PlaceKind, Hazard } from "@/lib/trippr/types";

type Json = Record<string, any>;
// Public, keyless Overpass instances, tried in order when one is busy or down.
export const OVERPASS_ENDPOINTS = ["https://overpass-api.de/api/interpreter","https://overpass.private.coffee/api/interpreter","https://maps.mail.ru/osm/tools/overpass/api/interpreter"];
const FLOODING = ["action","minor","moderate","major"];
export function decodePolyline(text:string,precision=6):Coordinate[]{const factor=10**precision,out:Coordinate[]=[];let i=0,lat=0,lon=0;while(i<text.length){for(let axis=0;axis<2;axis++){let shift=0,result=0,b:number;do{b=text.charCodeAt(i++)-63;result|=(b&31)<<shift;shift+=5;}while(b>=32&&i<text.length);const delta=result&1?~(result>>1):result>>1;if(axis===0)lat+=delta;else lon+=delta;}out.push([lon/factor,lat/factor]);}return out;}
// A route corridor becomes a union of small grid boxes: index lookups that public Overpass servers
// answer far faster than an "around" search over a long polyline.
export function corridorBoxes(line:Coordinate[],radius:number,grid=.5):number[][]{const cells=new Set<string>(),rows=new Map<number,number[]>(),boxes:number[][]=[];const points:Coordinate[]=[line[0]];for(let i=1;i<line.length;i++){const a=line[i-1],b=line[i],n=Math.min(200,Math.ceil(milesBetween(a,b)/8));for(let k=1;k<=n;k++)points.push([a[0]+(b[0]-a[0])*k/n,a[1]+(b[1]-a[1])*k/n]);}for(const p of points){const dy=radius/69,dx=radius/(69*Math.max(.2,Math.cos(p[1]*Math.PI/180)));for(let x=Math.floor((p[0]-dx)/grid);x<=Math.floor((p[0]+dx)/grid);x++)for(let y=Math.floor((p[1]-dy)/grid);y<=Math.floor((p[1]+dy)/grid);y++)cells.add(`${x}:${y}`);}
 for(const c of cells){const [x,y]=c.split(":").map(Number);rows.set(y,[...(rows.get(y)||[]),x]);}for(const [y,xs] of rows){xs.sort((a,b)=>a-b);let first=xs[0],prev=xs[0];for(const x of [...xs.slice(1),Infinity]){if(x!==prev+1){boxes.push([first*grid,y*grid,(prev+1)*grid,(y+1)*grid]);first=x;}prev=x;}}return boxes;}
export function createTripprHandler(environment:Record<string,unknown> = {}) {
const memo = new Map<string,{until:number;data:unknown}>();
const pending = new Map<string,Promise<unknown>>();
const visitors = new Map<string,{time:number;count:number}>();
class DataError extends Error { constructor(message:string,public status=502,public code="unavailable"){super(message);} }
const secret = (name:string)=>String(environment[name] || "");
function coordinate(q:URLSearchParams):Coordinate{const p:Coordinate=[Number(q.get("lon")),Number(q.get("lat"))];if(!q.has("lon")||!q.has("lat")||!validCoordinate(p))throw new DataError("Choose a valid map location.",400,"invalid_input");return p;}
function bbox(q:URLSearchParams){const b=(q.get("bbox")||"").split(",").map(Number);if(b.length!==4||!validCoordinate([b[0],b[1]])||!validCoordinate([b[2],b[3]])||b[0]>=b[2]||b[1]>=b[3])throw new DataError("Choose a valid map area.",400,"invalid_input");if(b[2]-b[0]>7||b[3]-b[1]>7)throw new DataError("Zoom closer to search this area.",400,"zoom_in");return b;}
function routePoints(q:URLSearchParams,max=160):Coordinate[]{let p:Coordinate[];try{p=JSON.parse(q.get("points")||"");}catch{throw new DataError("Invalid route corridor.",400,"invalid_input");}if(!Array.isArray(p)||p.length<2||p.length>max||!p.every(validCoordinate))throw new DataError("Invalid route corridor.",400,"invalid_input");let len=0;for(let i=1;i<p.length;i++)len+=milesBetween(p[i-1],p[i]);if(len>7000)throw new DataError("Search this trip in smaller sections.",400,"invalid_input");return p;}
function corridorRadius(q:URLSearchParams){const radius=Number(q.get("radius")||25);if(!Number.isFinite(radius)||radius<5||radius>50)throw new DataError("Choose a corridor between 5 and 50 miles.",400,"invalid_input");return radius;}
// Conditions are checked either for a map area or along a whole route corridor.
function region(q:URLSearchParams){if(!q.has("points")){const b=bbox(q);return{bbox:b,distance:(_p:Coordinate)=>undefined as number|undefined,near:(p:Coordinate)=>p[0]>=b[0]&&p[0]<=b[2]&&p[1]>=b[1]&&p[1]<=b[3]};}
 const line=routePoints(q,80),radius=corridorRadius(q),pad=radius/55,raw=boundsOf(line),b=[raw[0]-pad,raw[1]-pad,raw[2]+pad,raw[3]+pad].map(n=>Number(n.toFixed(3)));if(b[2]-b[0]>45||b[3]-b[1]>25)throw new DataError("Check this trip in smaller sections.",400,"invalid_input");return{bbox:b,distance:(p:Coordinate)=>distanceToRoute(p,line),near:(p:Coordinate)=>distanceToRoute(p,line)<=radius};}
async function remote(url:string,options:RequestInit&{timeout?:number}={},format="json"):Promise<any>{const response=await fetch(url,{...options,signal:AbortSignal.timeout(options.timeout||26000),headers:{...(typeof window === "undefined" ? {"User-Agent":"Trippr/1.0 (safisolutions.org)"} : {}),Accept:format==="json"?"application/json":"text/plain",...options.headers}});if(!response.ok)throw new DataError(response.status===429?"This source is busy. Try again shortly.":"This source is temporarily unavailable.",response.status===429?429:502);const length=Number(response.headers.get("content-length"));if(length>8_000_000)throw new DataError("This area has too much data. Zoom closer.");return format==="json"?response.json():response.text();}
async function cached(key:string,ttl:number,load:()=>Promise<unknown>){const old=memo.get(key);if(old&&old.until>Date.now())return old.data;if(pending.has(key))return pending.get(key);const request=load().then(data=>{if(memo.size>=100)memo.delete(memo.keys().next().value!);memo.set(key,{until:Date.now()+ttl,data});return data;}).finally(()=>pending.delete(key));pending.set(key,request);return request;}
// Only point-like OSM features go to Overpass; state parks and public lands come from PAD-US, which is
// faster and authoritative, and national parks, monuments and recreation areas are bundled from NPS.
const tagsFor:Record<string,string>={camp:'["tourism"~"^(camp_site|caravan_site)$"]',fuel:'["amenity"="fuel"]',ev:'["amenity"="charging_station"]',scenic:'["tourism"="viewpoint"]["name"]',waterfall:'["waterway"="waterfall"]["name"]',trail:'["highway"="trailhead"]["name"]',historic:'["historic"~"^(monument|fort|castle|ruins|archaeological_site|battlefield|lighthouse|ship|mine|manor|building)$"]["name"]',museum:'["tourism"="museum"]["name"]',attraction:'["tourism"="attraction"]["name"]',food:'["amenity"~"^(restaurant|cafe)$"]["name"]',cave:'["natural"="cave_entrance"]["name"]',hotspring:'["natural"="hot_spring"]'};
const LAND_KINDS=["statepark","land"];
function classify(t:Json):PlaceKind{if(t.amenity==="fuel")return"fuel";if(t.amenity==="charging_station")return"ev";if(["camp_site","caravan_site"].includes(t.tourism))return"camp";if(t.tourism==="viewpoint")return"scenic";if(t.waterway==="waterfall")return"waterfall";if(t.natural==="cave_entrance")return"cave";if(t.natural==="hot_spring")return"hotspring";if(t.highway==="trailhead")return"trail";if(t.tourism==="museum")return"museum";if(t.historic)return"historic";if(/state park/i.test(t.name||""))return"statepark";if(t.boundary==="protected_area")return"land";if(["restaurant","cafe"].includes(t.amenity))return"food";return"attraction";}
function osmPlaces(data:Json):Place[]{if(!Array.isArray(data.elements))throw new DataError("The place source returned unreadable data.");return data.elements.filter((e:Json)=>e.tags?.name&&validCoordinate([e.lon??e.center?.lon,e.lat??e.center?.lat])).slice(0,1500).map((e:Json)=>{const t=e.tags,kind=classify(t),yes=(v:unknown)=>v==="yes"?true:v==="no"?false:typeof v==="string"?v:null;return{id:`osm-${e.type}-${e.id}`,name:t.name,kind,coordinates:[e.lon??e.center.lon,e.lat??e.center.lat],region:[t["addr:city"],t["addr:state"]].filter(Boolean).join(", "),description:t.description||t["description:en"],website:t.website||t["contact:website"],source:"OpenStreetMap ⋅ community mapped",sourceUrl:`https://www.openstreetmap.org/${e.type}/${e.id}`,updated:data.osm3s?.timestamp_osm_base,tags:t,amenities:kind==="camp"?{Tents:yes(t.tents),"RV / caravan":yes(t.caravans),Restrooms:yes(t.toilets),"Drinking water":yes(t.drinking_water),Showers:yes(t.shower),Electricity:yes(t.power_supply),"Dump station":yes(t.sanitary_dump_station),Reservations:yes(t.reservation),Operator:t.operator||null,Elevation:t.ele?`${t.ele} m`:null}:undefined};});}
// Public instances are busy; a mirror that just failed rests for five minutes so the next request
// goes straight to one that is answering. Requests can start on different mirrors to spread load.
const resting=new Map<string,number>();
async function overpass(query:string,start=0){const order=OVERPASS_ENDPOINTS.map((_,i)=>OVERPASS_ENDPOINTS[(i+start)%OVERPASS_ENDPOINTS.length]).sort((a,b)=>Number((resting.get(a)||0)>Date.now())-Number((resting.get(b)||0)>Date.now()));let last:unknown;
 for(const url of order){try{const data=await remote(url,{method:"POST",timeout:20000,headers:{"Content-Type":"application/x-www-form-urlencoded",Accept:"*/*",...(typeof window==="undefined"?{Referer:"https://www.safisolutions.org/trippr/"}:{})},body:new URLSearchParams({data:query}).toString()});if(data.remark&&(!data.elements||!data.elements.length))throw new DataError("Place search timed out. Try a shorter distance or fewer kinds.");resting.delete(url);return data;}catch(e){last=e;resting.set(url,Date.now()+300000);}}
 throw last instanceof DataError?last:new DataError("Place search is temporarily unavailable. Try again shortly.");}
async function places(q:URLSearchParams){const all=(q.get("kinds")||"camp").split(","),kinds=all.filter(k=>tagsFor[k]).slice(0,8),landKinds=all.filter(k=>LAND_KINDS.includes(k));if(!kinds.length&&!landKinds.length)throw new DataError("Choose a place filter.",400,"invalid_input");let region:number[],line:Coordinate[]|undefined,radius=0,boxes:number[][];
 if(q.has("points")){line=routePoints(q);radius=corridorRadius(q);boxes=corridorBoxes(line,radius);const pad=radius/55,b=boundsOf(line);region=[b[0]-pad,b[1]-pad,b[2]+pad,b[3]+pad];}
 else{region=bbox(q);boxes=[region];}
 const near=(p:Place)=>!line||distanceToRoute(p.coordinates,line)<=radius,start=Number(q.get("mirror"))||0,CAP=1200;
 const jobs:{source:string;run:Promise<{places:Place[];limited?:boolean;updated?:string}>}[]=[];
 if(kinds.length)jobs.push({source:"OpenStreetMap / Overpass",run:overpass(`[out:json][timeout:18];(${kinds.flatMap(k=>boxes.map(b=>`nwr(${b[1].toFixed(3)},${b[0].toFixed(3)},${b[3].toFixed(3)},${b[2].toFixed(3)})${tagsFor[k]};`)).join("")});out center tags qt ${CAP};`,start).then(data=>({places:osmPlaces(data).filter(near),limited:data.elements?.length>=CAP,updated:data.osm3s?.timestamp_osm_base}))});
 if(landKinds.length){const areas=region[2]-region[0]<=8&&region[3]-region[1]<=8?[region]:sampleLine(line||[[region[0],region[1]],[region[2],region[3]]],4).map(c=>[c[0]-1,c[1]-.8,c[0]+1,c[1]+.8]);for(const b of areas)jobs.push({source:"USGS PAD-US 4.1 reference",run:publicLands(b,!landKinds.includes("land"),remote).then(places=>({places:line?places.filter(p=>distanceToRoute(p.coordinates,line!)<=radius+15):places,limited:places.length>=250}))});}
 const centers:Coordinate[]=line?sampleLine(line,3):[[(region[0]+region[2])/2,(region[1]+region[3])/2]];
 const ridb=secret("RIDB_API_KEY"),nrel=secret("NREL_API_KEY");for(const c of centers){if(kinds.includes("camp")&&ridb)jobs.push({source:"Recreation.gov / RIDB",run:recreationFacilities(c,Number(q.get("radius")||25),ridb,remote).then(places=>({places:places.filter(near)}))});if(kinds.includes("ev")&&nrel)jobs.push({source:"NREL / AFDC",run:ev(new URLSearchParams({lon:String(c[0]),lat:String(c[1])})).then(d=>({places:d.places.filter(near)}))});}
 const results=await Promise.allSettled(jobs.map(j=>j.run)),available=results.flatMap((r,i)=>r.status==="fulfilled"?[{...r.value,source:jobs[i].source}]:[]);if(!available.length){const first=results.find(r=>r.status==="rejected") as PromiseRejectedResult|undefined;throw first?.reason instanceof DataError?first.reason:new DataError("Place sources are temporarily unavailable. Try again shortly.");}
 return{places:[...new Map(available.flatMap(d=>d.places).map(p=>[p.id,p])).values()],source:[...new Set(available.map(d=>d.source))].join(" ⋅ "),updated:available[0].updated||new Date().toISOString(),limited:available.some(d=>d.limited),partial:results.some(r=>r.status==="rejected")};
}
async function osrm(points:Coordinate[]){const data=await remote(`https://router.project-osrm.org/route/v1/driving/${points.map(p=>p.join(",")).join(";")}?overview=full&geometries=geojson&steps=false`);const r=data.routes?.[0];if(data.code!=="Ok"||!Array.isArray(r?.geometry?.coordinates)||!r.geometry.coordinates.every(validCoordinate)||!Number.isFinite(r.distance)||!Number.isFinite(r.duration))throw new DataError("A driving route could not be found. Try a road-accessible entrance.");return{coordinates:r.geometry.coordinates,distance:r.distance,duration:r.duration,legs:r.legs.map((l:Json)=>({distance:l.distance,duration:l.duration})),source:"OSRM ⋅ driving estimate",updated:new Date().toISOString()};}
// FOSSGIS Valhalla supports toll, highway and ferry preferences without a key. It caps each
// request at 1,500 km of stop-to-stop distance and one call per second, so long trips go in pieces.
const VALHALLA_KM=1400;
async function valhallaPiece(points:Coordinate[],avoid:string[]){const auto={use_tolls:avoid.includes("tollways")?0:.5,use_highways:avoid.includes("highways")?0:1,use_ferry:avoid.includes("ferries")?0:.5};const body={locations:points.map(([lon,lat])=>({lon,lat,type:"break"})),costing:"auto",costing_options:{auto},units:"miles",directions_type:"none"};const data=await remote(`https://valhalla1.openstreetmap.de/route?json=${encodeURIComponent(JSON.stringify(body))}`);const legs=data.trip?.legs;if(!Array.isArray(legs)||!legs.length||!Number.isFinite(data.trip?.summary?.length))throw new DataError("A driving route could not be found with these road preferences.");const coordinates=legs.flatMap((l:Json,i:number)=>decodePolyline(String(l.shape||"")).slice(i?1:0));if(coordinates.length<2||!coordinates.every(validCoordinate))throw new DataError("The route geometry could not be read.");return{coordinates,legs:legs.map((l:Json)=>({distance:l.summary.length*1609.344,duration:l.summary.time}))};}
async function valhalla(points:Coordinate[],avoid:string[]){const pieces:Coordinate[][]=[];let piece=[points[0]],km=0;for(let i=1;i<points.length;i++){const d=milesBetween(points[i-1],points[i])*1.609344;if(d>VALHALLA_KM)throw new DataError("One drive between stops is too long to route with road preferences. Add a stop in between, or turn the preferences off.",400,"invalid_input");if(km+d>VALHALLA_KM){pieces.push(piece);piece=[points[i-1]];km=0;}piece.push(points[i]);km+=d;}pieces.push(piece);
 const parts:{coordinates:Coordinate[];legs:{distance:number;duration:number}[]}[]=[];for(const [i,p] of pieces.entries()){if(i)await new Promise(r=>setTimeout(r,1100));parts.push(await valhallaPiece(p,avoid));}
 const legs=parts.flatMap(p=>p.legs);return{coordinates:parts.flatMap((p,i)=>i?p.coordinates.slice(1):p.coordinates),distance:legs.reduce((n,l)=>n+l.distance,0),duration:legs.reduce((n,l)=>n+l.duration,0),legs,source:avoid.length?"Valhalla ⋅ driving estimate with your road preferences":"Valhalla ⋅ driving estimate",updated:new Date().toISOString()};}
async function route(q:URLSearchParams){let points:Coordinate[];try{points=JSON.parse(q.get("points")||"[]");}catch{throw new DataError("Invalid trip stops.",400,"invalid_input");}if(!Array.isArray(points)||points.length<2||points.length>20||!points.every(validCoordinate))throw new DataError("Use 2–20 valid stops to plan a route.",400,"invalid_input");const avoid:string[]=[];if(q.get("tolls")==="1")avoid.push("tollways");if(q.get("highways")==="1")avoid.push("highways");if(q.get("ferries")==="1")avoid.push("ferries");const key=secret("OPENROUTESERVICE_API_KEY");
 if(key){const data=await remote("https://api.openrouteservice.org/v2/directions/driving-car/geojson",{method:"POST",headers:{Authorization:key,"Content-Type":"application/json"},body:JSON.stringify({coordinates:points,...(avoid.length?{options:{avoid_features:avoid}}:{})})});const f=data.features?.[0];if(!f?.geometry?.coordinates||!f.properties?.summary)throw new DataError("A driving route could not be found.");return{coordinates:f.geometry.coordinates,distance:f.properties.summary.distance,duration:f.properties.summary.duration,legs:(f.properties.segments||[]).map((l:Json)=>({distance:l.distance,duration:l.duration})),source:"OpenRouteService ⋅ driving estimate",updated:new Date().toISOString()};}
 if(avoid.length)return valhalla(points,avoid);
 try{return await osrm(points);}catch(e){try{return await valhalla(points,[]);}catch{throw e;}}
}
async function weather(q:URLSearchParams){const p=coordinate(q),data=await remote(`https://api.open-meteo.com/v1/forecast?latitude=${p[1]}&longitude=${p[0]}&current=temperature_2m,weather_code,wind_speed_10m&daily=temperature_2m_max,temperature_2m_min,weather_code,precipitation_probability_max,sunrise,sunset&temperature_unit=fahrenheit&wind_speed_unit=mph&timezone=auto&forecast_days=14`);if(!data.current||!data.daily||!Number.isFinite(data.current.temperature_2m)||!Number.isFinite(data.current.weather_code)||!Number.isFinite(data.current.wind_speed_10m)||!Array.isArray(data.daily.time))throw new DataError("Weather data is unavailable at this location.");const d=data.daily;return{temperature:data.current.temperature_2m,code:data.current.weather_code,wind:data.current.wind_speed_10m,days:d.time.map((date:string,i:number)=>({date,high:d.temperature_2m_max?.[i],low:d.temperature_2m_min?.[i],code:d.weather_code?.[i],precipitation:Number.isFinite(d.precipitation_probability_max?.[i])?d.precipitation_probability_max[i]:null,sunrise:d.sunrise?.[i]||undefined,sunset:d.sunset?.[i]||undefined})).filter((x:Json)=>Number.isFinite(x.high)&&Number.isFinite(x.low)&&Number.isFinite(x.code)),updated:data.current.time+(data.utc_offset_seconds===0?"Z":offsetString(data.utc_offset_seconds)),source:"Open-Meteo ⋅ modeled weather & forecast"};}
function offsetString(seconds:number){const sign=seconds>=0?"+":"-",v=Math.abs(seconds);return`${sign}${String(Math.floor(v/3600)).padStart(2,"0")}:${String(Math.floor(v%3600/60)).padStart(2,"0")}`;}
async function alerts(q:URLSearchParams){const p=coordinate(q),data=await remote(`https://api.weather.gov/alerts/active?point=${p[1].toFixed(4)},${p[0].toFixed(4)}`);if(!Array.isArray(data.features))throw new DataError("Weather alerts are temporarily unavailable.");return{alerts:data.features.map((f:Json)=>({id:f.id,title:f.properties.event,severity:f.properties.severity,description:f.properties.description,area:f.properties.areaDesc,source:"National Weather Service",url:f.properties["@id"]||f.id,updated:f.properties.sent,geometry:f.geometry,coordinates:p})),updated:new Date().toISOString(),source:"National Weather Service"};}
async function search(q:URLSearchParams){const term=(q.get("q")||"").trim().slice(0,120);if(term.length<2)throw new DataError("Type at least two characters.",400,"invalid_input");const key=secret("GEOAPIFY_API_KEY");if(key){const data=await remote(`https://api.geoapify.com/v1/geocode/search?text=${encodeURIComponent(term)}&filter=countrycode:us&limit=8&apiKey=${encodeURIComponent(key)}`);return{places:(data.features||[]).map((f:Json)=>({id:`geo-${f.properties.place_id}`,name:f.properties.formatted,kind:"city",coordinates:f.geometry.coordinates,region:f.properties.state,source:"Geoapify geocoding"}))};}
 const data=await remote(`https://photon.komoot.io/api/?q=${encodeURIComponent(term)}&limit=10&lang=en&lat=39&lon=-98`);return{places:(data.features||[]).filter((f:Json)=>validCoordinate(f.geometry?.coordinates)&&(!f.properties.countrycode||f.properties.countrycode.toUpperCase()==="US")).slice(0,8).map((f:Json)=>({id:`photon-${f.properties.osm_type}-${f.properties.osm_id}`,name:[f.properties.name,f.properties.housenumber,f.properties.street].filter(Boolean).join(" ")||term,kind:"city",coordinates:f.geometry.coordinates,region:[f.properties.city!==f.properties.name?f.properties.city:"",f.properties.state].filter(Boolean).join(", "),source:"OpenStreetMap / Photon",sourceUrl:`https://www.openstreetmap.org/${({N:"node",W:"way",R:"relation"} as Json)[f.properties.osm_type]||"node"}/${f.properties.osm_id}`}))};}
async function reverse(q:URLSearchParams){const p=coordinate(q),data=await remote(`https://photon.komoot.io/reverse?lat=${p[1].toFixed(5)}&lon=${p[0].toFixed(5)}&limit=1&lang=en`),f=data.features?.[0]?.properties;if(!f)throw new DataError("No address was found here.");const town=f.city||f.town||f.village||f.county,named=f.osm_key&&!["highway","building","place"].includes(f.osm_key)&&f.name;return{name:named?f.name:town?`Near ${town}`:f.name||"A place on the map",region:[named&&town?town:"",f.state].filter(Boolean).join(", "),source:"OpenStreetMap / Photon"};}
async function wiki(q:URLSearchParams){const p=coordinate(q),radius=Math.max(500,Math.min(10000,Number(q.get("radius"))||10000)),params=new URLSearchParams({action:"query",generator:"geosearch",ggscoord:`${p[1].toFixed(5)}|${p[0].toFixed(5)}`,ggsradius:String(radius),ggslimit:"8",prop:"pageimages|extracts|description|coordinates",exintro:"1",explaintext:"1",exsentences:"2",exlimit:"8",piprop:"thumbnail",pithumbsize:"480",format:"json",formatversion:"2",origin:"*"});const data=await remote(`https://en.wikipedia.org/w/api.php?${params}`,{headers:typeof window==="undefined"?{}:{"Api-User-Agent":"Trippr/1.0 (https://www.safisolutions.org/trippr/)"}});const pages=Array.isArray(data.query?.pages)?data.query.pages:Object.values(data.query?.pages||{});return{pages:pages.filter((x:Json)=>typeof x.title==="string").map((x:Json)=>{const c=x.coordinates?.[0],coordinates=c&&validCoordinate([c.lon,c.lat])?[c.lon,c.lat] as Coordinate:undefined;return{title:x.title,description:typeof x.description==="string"?x.description:undefined,extract:typeof x.extract==="string"?x.extract.slice(0,600):undefined,thumbnail:typeof x.thumbnail?.source==="string"?x.thumbnail.source:undefined,coordinates,url:`https://en.wikipedia.org/wiki/${encodeURIComponent(x.title.replaceAll(" ","_"))}`,distance:coordinates?milesBetween(p,coordinates):undefined};}).sort((a:Json,b:Json)=>(a.distance??99)-(b.distance??99)),source:"Wikipedia",updated:new Date().toISOString()};}
function aqiCategory(n:number){return n<=50?"Good":n<=100?"Moderate":n<=150?"Unhealthy for sensitive groups":n<=200?"Unhealthy":n<=300?"Very unhealthy":"Hazardous";}
async function air(q:URLSearchParams){const p=coordinate(q),key=secret("AIRNOW_API_KEY");if(key){const d=await remote(`https://www.airnowapi.org/aq/observation/latLong/current/?format=application/json&latitude=${p[1]}&longitude=${p[0]}&distance=25&API_KEY=${encodeURIComponent(key)}`);if(!Array.isArray(d)||!d.length)throw new DataError("No reporting station is available nearby.");const aqi=Math.max(...d.map((x:Json)=>x.AQI));return{aqi,source:"AirNow ⋅ nearby observations",updated:new Date().toISOString(),category:aqiCategory(aqi)};}
 const d=await remote(`https://air-quality-api.open-meteo.com/v1/air-quality?latitude=${p[1]}&longitude=${p[0]}&current=us_aqi,pm2_5&timezone=auto`);if(!Number.isFinite(d.current?.us_aqi))throw new DataError("Air quality is unavailable here.");return{aqi:d.current.us_aqi,pm25:d.current.pm2_5,category:aqiCategory(d.current.us_aqi),source:"Open-Meteo / CAMS ⋅ modeled air quality",updated:new Date().toISOString()};}
async function parkInfo(q:URLSearchParams){const code=(q.get("park")||"").replace(/[^a-z]/g,"").slice(0,5),key=secret("NPS_API_KEY");if(!code)throw new DataError("Choose a park.",400,"invalid_input");if(!key)throw new DataError("Live park notices are not connected. Check the official park website.",503,"not_configured");const headers={"X-Api-Key":key};const rs=await Promise.allSettled([remote(`https://developer.nps.gov/api/v1/alerts?parkCode=${code}&limit=50`,{headers}),remote(`https://developer.nps.gov/api/v1/campgrounds?parkCode=${code}&limit=50`,{headers}),remote(`https://developer.nps.gov/api/v1/visitorcenters?parkCode=${code}&limit=20`,{headers})]);const get=(i:number)=>rs[i].status==="fulfilled"?(rs[i] as PromiseFulfilledResult<Json>).value.data:[];return{alerts:get(0).map((a:Json)=>({id:a.id,title:a.title,severity:a.category==="Danger"?"Severe":"Informational",description:a.description,area:code.toUpperCase(),source:"National Park Service",url:a.url,updated:new Date().toISOString()})),campgrounds:get(1).filter((c:Json)=>validCoordinate([Number(c.longitude),Number(c.latitude)])).map((c:Json)=>({id:`nps-camp-${c.id}`,name:c.name,kind:"camp",coordinates:[Number(c.longitude),Number(c.latitude)],description:c.description,source:"National Park Service",website:c.reservationUrl||c.url,amenities:{Restrooms:c.amenities?.toilets?.join(", ")||null,"Drinking water":c.amenities?.potableWater?.join(", ")||null,Showers:c.amenities?.showers?.join(", ")||null,Reservations:c.reservationInfo||null}})),visitorCenters:get(2).map((v:Json)=>({name:v.name,description:v.description,url:v.url})),partial:rs.some(r=>r.status==="rejected"),updated:new Date().toISOString()};}
async function ev(q:URLSearchParams){const p=coordinate(q),key=secret("NREL_API_KEY");if(!key)throw new DataError("The federal charger source is not connected. Community-mapped chargers remain available.",503,"not_configured");const d=await remote(`https://developer.nrel.gov/api/alt-fuel-stations/v1/nearest.json?api_key=${encodeURIComponent(key)}&latitude=${p[1]}&longitude=${p[0]}&radius=50&fuel_type=ELEC&limit=100&status=E&access=public`);return{places:(d.fuel_stations||[]).filter((s:Json)=>validCoordinate([s.longitude,s.latitude])&&typeof s.station_name==="string").map((s:Json)=>({id:`nrel-${s.id}`,name:s.station_name,kind:"ev",coordinates:[s.longitude,s.latitude],region:[s.city,s.state].join(", "),source:"NREL / AFDC",updated:s.updated_at,tags:{network:s.ev_network,connectors:(s.ev_connector_types||[]).join(", "),access:s.access_days_time},website:s.station_url,description:[s.ev_network,s.access_days_time].filter(Boolean).join(" ⋅ ")}))};}
// NIFC's current incident service is public; FIRMS satellite detections add to it when a key exists.
async function fire(q:URLSearchParams){const area=region(q),key=secret("NASA_FIRMS_MAP_KEY"),jobs:Promise<Hazard[]>[]=[];
 jobs.push(cached("wfigs",600000,()=>remote("https://services3.arcgis.com/T4QMspbfLg3qTGWY/arcgis/rest/services/WFIGS_Incident_Locations_Current/FeatureServer/0/query?"+new URLSearchParams({where:"IncidentTypeCategory='WF'",outFields:"IncidentName,IncidentSize,PercentContained,FireDiscoveryDateTime,ModifiedOnDateTime_dt,POOState,UniqueFireIdentifier",f:"geojson",resultRecordCount:"2000"}))).then((d:any)=>{if(!Array.isArray(d.features))throw new DataError("Wildfire incidents are temporarily unavailable.");return d.features.filter((f:Json)=>validCoordinate(f.geometry?.coordinates)&&Number(f.properties?.PercentContained)!==100&&area.near(f.geometry.coordinates)).map((f:Json):Hazard=>{const p=f.properties||{},acres=Number(p.IncidentSize),contained=Number(p.PercentContained),found=Number(p.FireDiscoveryDateTime);return{id:`wfigs-${p.UniqueFireIdentifier||f.id}`,coordinates:f.geometry.coordinates,kind:"fire",title:`${String(p.IncidentName||"Unnamed").replace(/\s+fire$/i,"")} Fire`,detail:[Number.isFinite(acres)&&acres>0?`${Math.round(acres).toLocaleString()} acres`:"Size not reported",Number.isFinite(contained)?`${Math.round(contained)}% contained`:"Containment not reported",Number.isFinite(found)?`reported ${new Date(found).toLocaleDateString("en-US",{month:"short",day:"numeric"})}`:""].filter(Boolean).join(" ⋅ ")+".",source:"NIFC WFIGS ⋅ current wildfire incidents",updated:Number.isFinite(Number(p.ModifiedOnDateTime_dt))?new Date(Number(p.ModifiedOnDateTime_dt)).toISOString():undefined,severity:Number.isFinite(contained)&&contained<50?"Active":"Monitored",distance:area.distance(f.geometry.coordinates)};});}));
 if(key)jobs.push(remote(`https://firms.modaps.eosdis.nasa.gov/api/area/csv/${encodeURIComponent(key)}/VIIRS_SNPP_NRT/${area.bbox.join(",")}/1`,{},"text").then((raw:string)=>{const lines=raw.trim().split(/\r?\n/),fields=lines.shift()?.split(",")||[];if(!fields.includes("latitude"))throw new DataError("Satellite detections are temporarily unavailable.");return lines.slice(0,1500).map((l,i):Hazard=>{const v=l.split(","),f=(k:string)=>v[fields.indexOf(k)]||"";const coordinates:Coordinate=[Number(f("longitude")),Number(f("latitude"))];return{id:`firms-${i}-${f("acq_date")}-${f("latitude")}`,coordinates,kind:"fire",title:"Satellite heat detection",detail:`Confidence: ${f("confidence")||"unknown"}. A heat detection is not a confirmed wildfire.`,source:"NASA FIRMS / VIIRS",updated:`${f("acq_date")}T${f("acq_time").padStart(4,"0").slice(0,2)}:${f("acq_time").padStart(4,"0").slice(2)}:00Z`,url:"https://firms.modaps.eosdis.nasa.gov/map/",severity:"Detection",distance:area.distance(coordinates)};}).filter(h=>validCoordinate(h.coordinates)&&area.near(h.coordinates));}));
 const rs=await Promise.allSettled(jobs);if(rs.every(r=>r.status==="rejected"))throw new DataError("Wildfire sources are temporarily unavailable.");const hazards=rs.flatMap(r=>r.status==="fulfilled"?r.value:[]).sort((a,b)=>(a.distance??0)-(b.distance??0));return{hazards:hazards.slice(0,800),source:key?"NIFC WFIGS ⋅ NASA FIRMS":"NIFC WFIGS",updated:new Date().toISOString(),coverage:"Reported wildfire incidents. Smoke, closures, and new starts may not appear yet."};}
async function rivers(q:URLSearchParams){const area=region(q),b=area.bbox;const d=await remote(`https://api.water.noaa.gov/nwps/v1/gauges?bbox.xmin=${b[0]}&bbox.ymin=${b[1]}&bbox.xmax=${b[2]}&bbox.ymax=${b[3]}&srid=EPSG_4326`);const list=d.gauges||d;if(!Array.isArray(list))throw new DataError("River conditions are temporarily unavailable.");const label=(s?:string)=>s?s.replaceAll("_"," "):"not reported";return{hazards:list.filter((g:Json)=>{const p:Coordinate=[Number(g.longitude),Number(g.latitude)];return validCoordinate(p)&&area.near(p)&&(FLOODING.includes(g.status?.observed?.floodCategory)||FLOODING.includes(g.status?.forecast?.floodCategory));}).slice(0,350).map((g:Json)=>{const p:Coordinate=[Number(g.longitude),Number(g.latitude)],observed=g.status?.observed?.floodCategory,forecast=g.status?.forecast?.floodCategory;return{id:`river-${g.lid||g.identifier}`,kind:"river",coordinates:p,title:g.name||g.lid||g.identifier,detail:`Observed: ${label(observed)} stage. Forecast: ${label(forecast)}.`,source:"NOAA National Water Prediction Service",url:`https://water.noaa.gov/gauges/${g.lid||g.identifier}`,updated:g.status?.observed?.validTime||undefined,severity:["moderate","major"].includes(observed)||["moderate","major"].includes(forecast)?"Flooding":"Elevated",distance:area.distance(p)};}),updated:new Date().toISOString(),source:"NOAA NWPS",coverage:"Only gauges at action stage or above are shown."};}
async function roads(q:URLSearchParams){const area=region(q),feeds=secret("WZDX_FEED_URLS").split(",").map(x=>x.trim()).filter(Boolean);if(!feeds.length)throw new DataError("Road-status coverage is not connected. Check state 511 / DOT information.",503,"not_configured");const rs=await Promise.allSettled(feeds.slice(0,6).map(url=>{const u=new URL(url);if(u.protocol!=="https:")throw new DataError("Road feed configuration is unavailable.");return remote(u.href);}));const hazards:Hazard[]=[];rs.forEach(r=>{if(r.status!=="fulfilled")return;for(const f of r.value.features||[]){const p=f.geometry?.type==="Point"?f.geometry.coordinates:f.geometry?.type==="LineString"?f.geometry.coordinates[0]:null;if(!validCoordinate(p)||!area.near(p))continue;const c=f.properties?.core_details||f.properties||{},end=f.properties?.end_date;if(end&&Date.parse(end)<Date.now())continue;const closed=(f.properties?.lanes||[]).some((l:Json)=>l.status==="closed");hazards.push({id:`road-${f.id||hazards.length}`,coordinates:p,kind:"road",title:closed?"Reported lane closure":"Work zone / construction",detail:c.description||c.road_names?.join(", ")||"See the source for road status and restrictions.",source:"State transportation WZDx feed",updated:r.value.feed_info?.update_date,url:c.data_source?.url,severity:closed?"Closure":"Construction",distance:area.distance(p)});}});if(rs.every(r=>r.status==="rejected"))throw new DataError("Road feeds are temporarily unavailable.");return{hazards:hazards.slice(0,500),updated:new Date().toISOString(),source:"Configured state WZDx feeds",partial:rs.some(r=>r.status==="rejected"),coverage:"Coverage is limited to connected state feeds. Missing markers do not mean roads are open."};}
function capabilities(){return{routing:secret("OPENROUTESERVICE_API_KEY")?"openrouteservice":"public",parks:!!secret("NPS_API_KEY"),roads:!!secret("WZDX_FEED_URLS"),firms:!!secret("NASA_FIRMS_MAP_KEY"),ridb:!!secret("RIDB_API_KEY"),nrel:!!secret("NREL_API_KEY"),airnow:!!secret("AIRNOW_API_KEY")};}
const actions:Record<string,{load:(q:URLSearchParams)=>Promise<unknown>;ttl:number}>={route:{load:route,ttl:3600000},weather:{load:weather,ttl:600000},alerts:{load:alerts,ttl:180000},search:{load:search,ttl:3600000},reverse:{load:reverse,ttl:86400000},wiki:{load:wiki,ttl:86400000},places:{load:places,ttl:1800000},air:{load:air,ttl:600000},park:{load:parkInfo,ttl:300000},ev:{load:ev,ttl:3600000},fire:{load:fire,ttl:600000},river:{load:rivers,ttl:600000},roads:{load:roads,ttl:300000},capabilities:{load:async()=>capabilities(),ttl:3600000}};
// Rate limiting applies to the shared backend; in-browser use has one visitor.
return async function GET(request:Request){try{const q=new URL(request.url).searchParams,action=actions[q.get("action")||""];if(!action)throw new DataError("Unknown data request.",400,"invalid_input");if(q.toString().length>14000)throw new DataError("This request is too large.",400,"invalid_input");const ip=request.headers.get("cf-connecting-ip");if(ip){const now=Date.now(),last=visitors.get(ip);if(!last||now-last.time>60000)visitors.set(ip,{time:now,count:1});else if(++last.count>90)throw new DataError("Too many requests. Try again in a minute.",429,"rate_limit");if(visitors.size>1000)visitors.delete(visitors.keys().next().value!);}const data=await cached(q.toString(),action.ttl,()=>action.load(q));return Response.json(data,{headers:{"Cache-Control":`public, max-age=${Math.floor(action.ttl/1000)}`,"X-Content-Type-Options":"nosniff"}});}catch(e){const error=e instanceof DataError?e:new DataError("This source is temporarily unavailable. Try again shortly.");return Response.json({error:error.message,code:error.code},{status:error.status,headers:{"Cache-Control":"no-store"}});}}

}
export const GET = createTripprHandler();
