import type {Coordinate} from "./types";
import type {MapTheme} from "./map-style";
export const rasterTileUrl=(theme:MapTheme)=>theme==="satellite"?"https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}":((globalThis as unknown as {TRIPPR_CONFIG?:{rasterTiles?:string}}).TRIPPR_CONFIG?.rasterTiles || "https://tile.openstreetmap.org/{z}/{x}/{y}.png");
export const rasterAttribution=(theme:MapTheme)=>theme==="satellite"?"Imagery © Esri, Maxar, Earthstar Geographics and the GIS User Community":'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors';
export function mercator(p:Coordinate,z:number){const scale=256*2**z,sin=Math.sin(Math.max(-85,Math.min(85,p[1]))*Math.PI/180);return{x:(p[0]+180)/360*scale,y:(.5-Math.log((1+sin)/(1-sin))/(4*Math.PI))*scale};}
export async function renderRaster(canvas:HTMLCanvasElement,line:Coordinate[],pad:{top:number;bottom:number;left:number;right:number}){
 const ctx=canvas.getContext("2d")!,width=canvas.width,height=canvas.height,points=line.map(p=>mercator(p,0)),minX=Math.min(...points.map(p=>p.x)),maxX=Math.max(...points.map(p=>p.x)),minY=Math.min(...points.map(p=>p.y)),maxY=Math.max(...points.map(p=>p.y));
 const z=Math.max(2,Math.min(12,Math.floor(Math.log2(Math.min((width-pad.left-pad.right)/Math.max(maxX-minX,1),(height-pad.top-pad.bottom)/Math.max(maxY-minY,1))))));
 const scale=2**z,originX=(minX+maxX)/2*scale-(pad.left+(width-pad.left-pad.right)/2),originY=(minY+maxY)/2*scale-(pad.top+(height-pad.top-pad.bottom)/2),project=(p:Coordinate)=>{const q=mercator(p,z);return{x:q.x-originX,y:q.y-originY};};ctx.fillStyle="#192a27";ctx.fillRect(0,0,width,height);
 const jobs:Promise<void>[]=[];for(let x=Math.floor(originX/256);x<Math.ceil((originX+width)/256);x++)for(let y=Math.floor(originY/256);y<Math.ceil((originY+height)/256);y++){if(y<0||y>=2**z)continue;const url=rasterTileUrl("atlas").replace("{z}",String(z)).replace("{x}",String((x+2**z)%2**z)).replace("{y}",String(y));jobs.push(new Promise((resolve,reject)=>{const img=new Image();img.crossOrigin="anonymous";const timer=setTimeout(()=>{img.src="";reject(Error("The export map took too long to load. Try again shortly."));},15000);img.onload=()=>{clearTimeout(timer);ctx.filter="invert(.9) hue-rotate(180deg) saturate(.55) brightness(.85)";ctx.drawImage(img,x*256-originX,y*256-originY,256,256);ctx.filter="none";resolve();};img.onerror=()=>{clearTimeout(timer);reject(Error("Some map tiles are unavailable. Try the export again shortly."));};img.src=url;}));}
 await Promise.all(jobs);ctx.lineCap="round";ctx.lineJoin="round";ctx.beginPath();line.forEach((p,i)=>{const q=project(p);if(i)ctx.lineTo(q.x,q.y);else ctx.moveTo(q.x,q.y);});ctx.strokeStyle="#c4f17b25";ctx.lineWidth=22;ctx.stroke();ctx.strokeStyle="#12281b";ctx.lineWidth=12;ctx.stroke();ctx.strokeStyle="#c4f17b";ctx.lineWidth=7;ctx.stroke();return project;
}
