import type {Trip,Stop,PlaceKind,Coordinate} from "./types";
import {DEFAULT_PREFERENCES} from "./types";
import {newId,validCoordinate} from "./geo";
import {REFERENCE_PLACES,CATEGORY_LABELS} from "./data";
// A shared trip travels inside the link itself: no account, no server copy.
type Packed={v:1;n:string;a?:string;b?:string;s:[string,number,number,string?,string?,string?][]};
const toBase64Url=(bytes:Uint8Array)=>btoa(String.fromCharCode(...bytes)).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"");
const fromBase64Url=(text:string)=>Uint8Array.from(atob(text.replace(/-/g,"+").replace(/_/g,"/")),c=>c.charCodeAt(0));
async function pipe(bytes:Uint8Array,stream:CompressionStream|DecompressionStream){return new Uint8Array(await new Response(new Blob([bytes as BlobPart]).stream().pipeThrough(stream)).arrayBuffer());}
export async function encodeTrip(trip:Trip):Promise<string>{const packed:Packed={v:1,n:trip.name.slice(0,120),a:trip.startDate||undefined,b:trip.endDate||undefined,s:trip.stops.map(s=>[s.name.slice(0,120),Number(s.coordinates[0].toFixed(5)),Number(s.coordinates[1].toFixed(5)),s.date||"",REFERENCE_PLACES.some(r=>r.id===s.id)?s.id:"",s.kind])};const raw=new TextEncoder().encode(JSON.stringify(packed));if(typeof CompressionStream==="function")return"z"+toBase64Url(await pipe(raw,new CompressionStream("deflate-raw")));return"j"+toBase64Url(raw);}
export async function decodeTrip(text:string):Promise<Trip|null>{try{const bytes=fromBase64Url(text.slice(1)),raw=text[0]==="z"?await pipe(bytes,new DecompressionStream("deflate-raw")):text[0]==="j"?bytes:null;if(!raw)return null;const p=JSON.parse(new TextDecoder().decode(raw)) as Packed;if(p.v!==1||!Array.isArray(p.s)||p.s.length>20)return null;const stops:Stop[]=p.s.filter(s=>Array.isArray(s)&&typeof s[0]==="string"&&validCoordinate([s[1],s[2]])).map(([name,lon,lat,date,id,kind])=>{const known=id?REFERENCE_PLACES.find(r=>r.id===id):undefined,k=(kind&&kind in CATEGORY_LABELS?kind:"city") as PlaceKind;return{...(known||{id:newId(),name,kind:k,coordinates:[lon,lat] as Coordinate,source:"Shared trip link"}),stopId:newId(),date:/^\d{4}-\d{2}-\d{2}$/.test(date||"")?date:undefined};});return{id:newId(),name:String(p.n||"A shared road trip").slice(0,120),stops,startDate:p.a||"",endDate:p.b||"",notes:"",savedPlaces:[],placeNotes:{},preferences:{...DEFAULT_PREFERENCES},modifiedAt:new Date().toISOString()};}catch{return null;}}
export async function shareUrl(trip:Trip){return`${location.origin}/trippr/#trip=${await encodeTrip(trip)}`;}
// Google Maps accepts an origin, a destination and up to nine waypoints in a directions link.
export function directionsUrl(points:Coordinate[]){if(points.length<2)return undefined;const fmt=(p:Coordinate)=>`${p[1].toFixed(5)},${p[0].toFixed(5)}`,via=points.slice(1,-1).slice(0,9);const q=new URLSearchParams({api:"1",origin:fmt(points[0]),destination:fmt(points[points.length-1]),travelmode:"driving"});if(via.length)q.set("waypoints",via.map(fmt).join("|"));return`https://www.google.com/maps/dir/?${q}`;}
export const placeDirectionsUrl=(p:Coordinate)=>`https://www.google.com/maps/dir/?api=1&destination=${p[1].toFixed(5)},${p[0].toFixed(5)}&travelmode=driving`;
