/* ============================================================
   OVERTONE — ENCYCLOPEDIA
   {t, cat, tag, def, why, watch}
   ============================================================ */
window.OT = window.OT || {};

OT.ENC_CATS = [
  ['all','Everything'],
  ['fundamentals','Fundamentals'],
  ['harmony','Harmony'],
  ['melody','Melody & Form'],
  ['rhythm','Rhythm & Time'],
  ['instruments','Instruments'],
  ['production','Sound & Production'],
  ['practice','Ear & Practice']
];

OT.ENCYCLOPEDIA = [
/* ---------------- FUNDAMENTALS ---------------- */
{t:'Pitch',cat:'fundamentals',tag:'frequency, heard as height',
 def:'How high or low a sound is, set by how many times per second the air pressure cycles. A4 is conventionally 440 Hz.',
 why:'Pitch is the vertical axis of music. Every melody is a path drawn through it and every chord is a stack of it.',
 watch:'Doubling the frequency raises the pitch by exactly one octave, and we hear that as "the same note", the single most important fact in all of tuning.'},
{t:'The Harmonic Series',cat:'fundamentals',tag:'why anything sounds like anything',
 def:'A vibrating string or column of air does not produce one frequency. It produces a fundamental plus whole-number multiples of it, all at once.',
 why:'This is the physical foundation under every other page here. The octave, the fifth and the major third appear in the first five partials, which is why those intervals sound consonant in every musical culture.',
 watch:'The relative loudness of those upper partials is what we call timbre: it is why a violin and a flute playing the same note are instantly distinguishable.'},
{t:'Octave',cat:'fundamentals',tag:'the 2:1 ratio',
 def:'The interval between a frequency and double that frequency. Notes an octave apart share a letter name.',
 why:'Octave equivalence lets us collapse the infinite range of hearing into twelve repeating names. Without it there would be no such thing as "a C".',
 watch:'The octave is the only interval that is acoustically pure in equal temperament. Every other interval on a piano is slightly out of tune on purpose.'},
{t:'Equal Temperament',cat:'fundamentals',tag:'the useful compromise',
 def:'Dividing the octave into twelve mathematically identical half-steps, so every key sounds equally in tune and equally slightly wrong.',
 why:'It is what makes modulation possible. Before it, keys had genuinely different characters because their intervals were differently out of tune.',
 watch:'The equal-tempered major third is noticeably sharper than the pure 5:4 ratio from the harmonic series. Barbershop and choral singers instinctively correct it.'},
{t:'Semitone & Whole Tone',cat:'fundamentals',tag:'the unit of measurement',
 def:'A semitone is the smallest step in Western music: one fret, one piano key. A whole tone is two semitones.',
 why:'Every scale and chord in this app is defined purely as a pattern of semitones from a root, which is why the same shape works in all twelve keys.',
 watch:'On a piano the half-steps hide between E–F and B–C where there are no black keys. That irregularity is the entire reason the keyboard looks the way it does.'},
{t:'Enharmonic Equivalents',cat:'fundamentals',tag:'same key, different name',
 def:'Two spellings for the same pitch: F♯ and G♭ are the same piano key.',
 why:'The spelling encodes function. F♯ is the leading tone in G major; G♭ is the flat sixth in B♭ minor. Same sound, different job.',
 watch:'Sight-reading gets much easier once you stop treating spelling as arbitrary. The notation is telling you where the note is going.'},
{t:'Key Signature',cat:'fundamentals',tag:'the sharps and flats up front',
 def:'The sharps or flats printed at the start of each staff line, declaring which notes are altered throughout.',
 why:'It saves writing an accidental on every single note and tells the reader the home key before a note is played.',
 watch:'A key signature does not tell you major or minor: C major and A minor look identical. You have to look at where the music actually rests.'},
{t:'Tonic & Tonality',cat:'fundamentals',tag:'home base',
 def:'The tonic is the note the music treats as home. Tonality is the system of gravity that pulls back toward it.',
 why:'Expectation and resolution are the emotional engine of most Western music, and both depend on there being a home to leave and return to.',
 watch:'Modal and atonal music weaken or remove that gravity deliberately. Ambient and minimalist music often weakens resolution so a texture can continue without sounding finished.'},

/* ---------------- HARMONY ---------------- */
{t:'Interval',cat:'harmony',tag:'the distance between two notes',
 def:'The gap between two pitches, named by size and quality: major 3rd, perfect 5th, tritone.',
 why:'Intervals are the DNA of both melody and harmony. Name them by ear and you can transcribe or build anything.',
 watch:'The same interval feels different ascending versus descending, and different again when the two notes sound together instead of in sequence.'},
{t:'Triad',cat:'harmony',tag:'three notes stacked in thirds',
 def:'A root, a third and a fifth. Major, minor, diminished and augmented are the four possibilities.',
 why:'Nearly all Western harmony is triads plus decoration. Understanding four shapes gets you most of the way through most repertoire.',
 watch:'The third is the note that decides major or minor. The fifth is the most disposable; pianists drop it constantly to make room for extensions.'},
{t:'Inversion',cat:'harmony',tag:'which note is on the bottom',
 def:'Rearranging a chord so a note other than the root is lowest. A C major triad with E in the bass is first inversion.',
 why:'Inversions let the bass move smoothly while the harmony stays put. It is the difference between a progression that lurches and one that flows.',
 watch:'The bass note changes the emotional weight enormously even though the chord "is" the same. First inversion sounds lighter and less final than root position.'},
{t:'Seventh Chord',cat:'harmony',tag:'adding the fourth note',
 def:'A triad with another third stacked on top, producing a seventh above the root.',
 why:'Sevenths are where harmony stops being primary-colour and starts having shades. Jazz, soul, R&B and sophisticated pop harmony live here.',
 watch:'The dominant 7th contains a tritone between its 3rd and 7th. That internal dissonance is the mechanism of functional harmony, not a flaw.'},
{t:'Extensions (9ths, 11ths, 13ths)',cat:'harmony',tag:'stacking past the seventh',
 def:'Continuing to stack thirds beyond the 7th, producing tones named by their distance above the root in the octave above.',
 why:'Extensions add colour without changing function. A G7 and a G13 do the same harmonic job; one is just wearing a better coat.',
 watch:'Keep extensions high. A 9th played next to the root in the bass register turns to mud, because the ear cannot separate close intervals down low.'},
{t:'Roman Numeral Analysis',cat:'harmony',tag:'chords by function, not by letter',
 def:'Labelling chords by their scale degree (I, ii, V7, vi) so the same progression can be described in any key.',
 why:'It reveals that thousands of songs are the same four chords transposed. Once you think in numerals you can hear structure instead of letters.',
 watch:'Uppercase means major, lowercase means minor, ° is diminished. The numeral describes the chord built on that degree, not the melody note.'},
{t:'Cadence',cat:'harmony',tag:'musical punctuation',
 def:'A chord pair that ends a phrase. Authentic is V–I, plagal is IV–I, half ends on V, deceptive goes V–vi.',
 why:'Cadences are how music signals a comma, a full stop or a cliffhanger. Listeners parse them without knowing the names.',
 watch:'The deceptive cadence is the most useful one to know by ear: it is the sound of a song refusing to end when you expected it to.'},
{t:'Voice Leading',cat:'harmony',tag:'how each line moves',
 def:'The melodic path each individual voice takes from one chord to the next, ideally by the smallest possible step.',
 why:'It is what separates progressions that sound professional from ones that sound like someone pressing chord buttons.',
 watch:'Hold common tones, move everything else the shortest distance. That single rule will improve your arrangements more than any new chord will.'},
{t:'Modulation',cat:'harmony',tag:'changing key mid-piece',
 def:'Moving the tonal centre to a new home key, either abruptly or through a pivot chord shared by both keys.',
 why:'It resets the listener\u2019s expectations and creates lift. The final-chorus key change is the most commercial application of a very old device.',
 watch:'Closely related keys share most of their notes and modulate smoothly. Distant keys need preparation or a deliberate shock.'},
{t:'Modal Interchange',cat:'harmony',tag:'borrowing from the parallel key',
 def:'Using chords from the parallel major or minor: a ♭VI or iv appearing in a major key, for example.',
 why:'It is the most efficient way to add emotional shading without leaving the key. One borrowed chord can turn contentment into longing.',
 watch:'The minor iv in a major key is the classic tearjerker. If a song suddenly aches on one chord, that is usually what happened.'},
{t:'Secondary Dominant',cat:'harmony',tag:'a V of something that is not I',
 def:'A dominant 7th chord that resolves to a chord other than the tonic: V7/V, V7/vi and so on.',
 why:'It temporarily makes another chord feel like home, which adds forward motion without a full modulation.',
 watch:'It will contain a note outside the key. That accidental is the tell. Spot it in sheet music and you have found the secondary dominant.'},
{t:'Tritone',cat:'harmony',tag:'the interval that splits the octave',
 def:'Three whole tones, exactly half an octave. Historically nicknamed the devil in music.',
 why:'It is maximally unstable, which makes it the engine inside every dominant 7th chord and every diminished chord.',
 watch:'Because it splits the octave evenly, it is its own inversion. That symmetry is what makes tritone substitution possible in jazz.'},
{t:'Pedal Tone',cat:'harmony',tag:'a bass note that refuses to move',
 def:'A sustained or repeated note, usually in the bass, held while the harmony above it changes.',
 why:'It creates tension and stillness at once. Film, ambient and minimalist writing use it because it lets the harmony stay grounded while the surface keeps moving.',
 watch:'The dissonances that occur against the pedal are features, not errors. The ear forgives almost anything over a strong held bass.'},

/* ---------------- MELODY & FORM ---------------- */
{t:'Scale',cat:'melody',tag:'an ordered set of pitches',
 def:'A collection of notes arranged in ascending order within an octave, acting as the raw material for melody and harmony.',
 why:'Choosing a scale is choosing a palette and a mood before you have written a single phrase.',
 watch:'Modes are the same notes started from a different degree. The notes do not change; where the gravity sits does, and that changes everything.'},
{t:'Mode',cat:'melody',tag:'same notes, different centre',
 def:'A scale derived by treating a different degree of a parent scale as the tonic. Dorian is the major scale started from its second degree.',
 why:'Modes give you seven distinct emotional colours out of one set of notes, which is why film, jazz and folk writers reach for them constantly.',
 watch:'A mode only sounds modal if the harmony supports it. Play D Dorian over a C major chord and you will just hear C major.'},
{t:'Motif',cat:'melody',tag:'the smallest memorable idea',
 def:'A short rhythmic or melodic fragment (sometimes only three or four notes) that a piece develops and repeats.',
 why:'Memorability lives here. Almost every theme people can hum is built from one small cell repeated and varied.',
 watch:'A motif can survive being transposed, inverted, reversed or re-harmonised and still be recognisable. That durability is what makes it a motif.'},
{t:'Leitmotif',cat:'melody',tag:'a theme attached to a thing',
 def:'A recurring musical idea tied to a character, place or concept, transformed as their situation changes.',
 why:'Wagner formalised it for opera; film scoring inherited it wholesale. It lets music carry plot information without a word.',
 watch:'The power is in the transformation. Hearing a hero\u2019s theme in minor, slow, on a solo instrument tells you what happened without a cutscene.'},
{t:'Phrase & Period',cat:'melody',tag:'musical sentences',
 def:'A phrase is a complete musical thought, commonly four bars. Two phrases that answer each other form a period.',
 why:'It is the grammar of melody. The reason so much music comes in four- and eight-bar chunks is that we parse it like speech.',
 watch:'Antecedent and consequent: question and answer. The first phrase ends unresolved, the second finishes the thought.'},
{t:'Song Form',cat:'melody',tag:'the architecture',
 def:'The arrangement of sections: verse, chorus, bridge, and in jazz the 32-bar AABA.',
 why:'Form manages attention. It decides when to give the listener something familiar and when to give them something new.',
 watch:'Great songs feel inevitable because the structure is invisible. Map the form of a track you love and the craft becomes obvious.'},
{t:'Counterpoint',cat:'melody',tag:'independent lines at once',
 def:'Two or more melodies of equal importance sounding together, each making sense alone.',
 why:'It is the difference between melody-plus-accompaniment and genuine musical conversation. Bach is the reference point.',
 watch:'Contrary motion (one line rising while another falls) is the fastest way to make two parts sound independent rather than parallel.'},
{t:'Ostinato',cat:'melody',tag:'a figure that will not stop',
 def:'A short pattern repeated persistently, usually in the bass or an inner voice.',
 why:'It creates momentum and hypnosis at the same time, which is why it appears constantly in minimalism, electronic music and film scoring.',
 watch:'Repetition works because of what changes around it. An ostinato with nothing developing above it becomes wallpaper within a minute.'},

/* ---------------- RHYTHM ---------------- */
{t:'Beat & Tempo',cat:'rhythm',tag:'the pulse and its speed',
 def:'The beat is the steady underlying pulse; tempo is how fast it runs, measured in beats per minute.',
 why:'Tempo changes meaning more than almost any other parameter. The same melody at 60 and 140 BPM is two different pieces.',
 watch:'Perceived speed depends on subdivision, not just BPM. A 70 BPM track full of sixteenth notes feels faster than a sparse 110.'},
{t:'Time Signature',cat:'rhythm',tag:'how beats are grouped',
 def:'Two numbers: how many beats per bar, and which note value gets the beat. 4/4 is four quarter notes.',
 why:'Grouping creates the feel of a genre before any notes arrive. 3/4 spins, 4/4 walks, 6/8 lopes.',
 watch:'Compound meters like 6/8 group beats in threes. They are counted in two but felt in six, which is why they swing naturally.'},
{t:'Syncopation',cat:'rhythm',tag:'accents where they should not be',
 def:'Emphasising the weak parts of the beat: the off-beats or the spaces between them.',
 why:'It is a primary source of groove in funk, hip-hop, R&B, Latin music and modern pop.',
 watch:'Syncopation only exists relative to a pulse the listener is already tracking. Remove the steady reference and it stops reading as syncopated.'},
{t:'Swing',cat:'rhythm',tag:'the long-short subdivision',
 def:'Playing paired eighth notes unevenly (the first longer than the second) rather than as mathematical halves.',
 why:'It is the rhythmic signature of jazz and blues, and it is almost never notated. Players supply it from style knowledge.',
 watch:'Swing is a continuous dial, not a switch. How hard to swing is a decision made per tune and often per section.'},
{t:'Polyrhythm',cat:'rhythm',tag:'two grids at once',
 def:'Two conflicting rhythmic groupings played simultaneously, three against two being the simplest.',
 why:'It generates complexity from simple parts and creates a shifting, unstable surface over a steady pulse.',
 watch:'Three-against-two is the gateway. Say "not-diff-i-cult" evenly and you are already playing it.'},
{t:'Groove & Pocket',cat:'rhythm',tag:'the feel behind the grid',
 def:'The micro-timing that makes a rhythm feel good: playing slightly ahead of, behind or exactly on the beat.',
 why:'Two drummers playing identical notation can produce completely different results. The deviation from the grid is the performance.',
 watch:'Perfect quantisation removes groove. This is why programmed drums often get humanised deliberately after being programmed perfectly.'},
{t:'Clave',cat:'rhythm',tag:'the organising pattern',
 def:'A two-bar rhythmic key in Afro-Cuban music that everything else in the arrangement aligns to.',
 why:'It functions like a time signature for feel. Play against the clave and the whole band sounds wrong to anyone who knows the tradition.',
 watch:'Direction matters: 3-2 and 2-3 are not interchangeable. Flipping it mid-tune is a genuine error, not a variation.'},

/* ---------------- INSTRUMENTS ---------------- */
{t:'The Keyboard Layout',cat:'instruments',tag:'theory made visible',
 def:'Twelve keys per octave in a repeating pattern of two and three black keys, with half-steps at E–F and B–C.',
 why:'It is the clearest physical map of pitch ever designed. Intervals are distances you can see, which is why theory is taught at a piano.',
 watch:'You do not need to be a pianist. Fifteen minutes a day finding intervals on a keyboard will transform how you understand your main instrument.'},
{t:'Guitar Fretboard',cat:'instruments',tag:'a movable grid',
 def:'Six strings tuned mostly in fourths, with each fret one semitone. Any shape can slide to any key.',
 why:'Transposition is free. A shape learned once works in all twelve keys, which is why guitarists can play in keys they cannot name.',
 watch:'The B string breaks the pattern of fourths, which is why chord shapes look asymmetrical and why the same interval has two different shapes.'},
{t:'CAGED System',cat:'instruments',tag:'five shapes cover the neck',
 def:'Five open chord shapes (C, A, G, E, D) moved up the neck as barre forms, linking into a complete map.',
 why:'It connects scale shapes to chord shapes so you always know which notes are chord tones under your fingers.',
 watch:'It is a navigation aid, not a theory. Players who only know CAGED shapes often cannot name a single note they are playing.'},
{t:'Transposing Instruments',cat:'instruments',tag:'written pitch is not sounding pitch',
 def:'Instruments whose written C sounds as a different pitch: a B♭ trumpet\u2019s written C sounds as a B♭.',
 why:'It exists so players can switch between family members using identical fingerings. It is a player convenience with a notation cost.',
 watch:'When arranging, always confirm concert versus written pitch. It is the single most common source of embarrassing errors in scores.'},
{t:'Register & Range',cat:'instruments',tag:'where an instrument lives',
 def:'Range is the span of notes an instrument can play; register refers to the character of different areas within it.',
 why:'Instruments change personality across their range. A clarinet\u2019s low register is dark and woody; the top is piercing.',
 watch:'Arrangement problems are usually register problems. Two parts fighting in the same octave will sound muddy no matter how good the notes are.'},
{t:'Voice Types',cat:'instruments',tag:'the original instrument',
 def:'Classified roughly by range (soprano, alto, tenor, bass) with subdivisions by timbre and weight.',
 why:'Singing what you play is the fastest known route to internalising intervals. The voice has no frets or keys to hide behind.',
 watch:'Range and tessitura are different. A singer may be able to hit a note without being able to sit there comfortably for eight bars.'},

/* ---------------- PRODUCTION ---------------- */
{t:'Timbre',cat:'production',tag:'why a flute is not a violin',
 def:'The tonal colour of a sound, determined by the relative strengths of its harmonics and the shape of its attack.',
 why:'Timbre is how we identify instruments and voices instantly. It carries more information than pitch in most real listening.',
 watch:'The attack matters more than the sustain. Remove the first fraction of a second from a piano note and most listeners cannot identify the instrument.'},
{t:'ADSR Envelope',cat:'production',tag:'the shape of a note over time',
 def:'Attack, decay, sustain, release: the four stages describing how a sound\u2019s volume evolves from keypress to silence.',
 why:'It is how synthesisers imitate real instruments and how sample-based hardware shaped its voices. Plucked sounds have fast attack and no sustain; strings have the opposite.',
 watch:'Sustain is a level, not a time. The other three are durations, which is the detail that confuses everyone the first time.'},
{t:'EQ',cat:'production',tag:'sculpting the frequency balance',
 def:'Boosting or cutting specific frequency ranges of a sound.',
 why:'Most mixing problems are two sounds occupying the same frequency space. Clarity comes from carving room, not from adding volume.',
 watch:'Cut narrow, boost wide, and always compare against the bypassed signal. Ears adapt to whatever they have been hearing for thirty seconds.'},
{t:'Compression',cat:'production',tag:'controlling dynamic range',
 def:'Automatically reducing the loudest parts of a signal so the overall level can be raised.',
 why:'It creates density and consistency, and it is why modern recordings feel present at low listening volumes.',
 watch:'Over-compression removes the dynamics that carry emotion. If everything is loud, nothing is loud.'},
{t:'Reverb',cat:'production',tag:'putting sound in a room',
 def:'The dense pattern of reflections that follows a sound in a physical space, simulated electronically.',
 why:'It supplies depth and distance. Dry sounds feel close and clinical; wet sounds feel far away and atmospheric.',
 watch:'Reverb eats clarity. In dense arrangements it is usually applied to a few elements rather than everything, so the mix keeps its focus.'},
{t:'Sampling',cat:'production',tag:'recording as an instrument',
 def:'Recording a real sound and playing it back at different pitches from a keyboard or sequencer.',
 why:'It is how realistic instrument sounds work in software, including in this app. Recorded notes are pitch-shifted to fill the gaps between them.',
 watch:'Shift a sample too far and the artefacts show: the classic chipmunk effect. Good sample sets record many notes so each is used near its true pitch.'},
{t:'FM Synthesis',cat:'production',tag:'oscillators modulating each other',
 def:'Generating complex timbres by using one oscillator to modulate the frequency of another.',
 why:'It produces metallic, bell-like and aggressive tones that subtractive synthesis struggles with; the Yamaha DX7 made the method famous in pop production.',
 watch:'It is famously unintuitive to program. Small parameter changes produce enormous timbral jumps, which is why most people used presets.'},

/* ---------------- EAR & PRACTICE ---------------- */
{t:'Relative Pitch',cat:'practice',tag:'hearing relationships',
 def:'The ability to identify intervals, chords and scale degrees relative to a reference note.',
 why:'This is the practical skill, and it is fully trainable at any age. It is what lets you transcribe, improvise and play by ear.',
 watch:'Sing every interval you are trying to learn. Producing a sound trains recognition far faster than passive listening does.'},
{t:'Absolute Pitch',cat:'practice',tag:'naming notes without reference',
 def:'The rare ability to identify or produce a pitch with no reference note.',
 why:'It is genuinely useful for transcription, and it is not required for excellent musicianship. Most great musicians do not have it.',
 watch:'It can even get in the way: some absolute-pitch listeners struggle with transposing instruments or ensembles tuned away from A440.'},
{t:'Transcription',cat:'practice',tag:'learning by ear',
 def:'Working out music by listening and writing it down or committing it to memory, without a score.',
 why:'It trains pitch, rhythm, harmony, form and style simultaneously. It is the single highest-value practice activity there is.',
 watch:'Start with bass lines. They move slowly, sit in a clear register and reveal the harmony faster than melodies do.'},
{t:'Deliberate Practice',cat:'practice',tag:'not just repetition',
 def:'Focused work at the edge of your ability with immediate feedback and a specific goal, rather than playing through what you already know.',
 why:'Mindless repetition reinforces whatever you are already doing, including the mistakes. Attention is the active ingredient.',
 watch:'Slow practice feels unproductive and is the fastest route to reliable speed. If you cannot play it slowly and cleanly, you cannot play it.'},
{t:'Interleaved Practice',cat:'practice',tag:'mixing it up on purpose',
 def:'Rotating between several skills or pieces in a session rather than drilling one to exhaustion.',
 why:'It performs worse during practice and better at retention, which is why it feels wrong and works anyway.',
 watch:'Judge a session by what you can do the next day, not by how smooth it felt at the time.'},
{t:'Sight-Reading',cat:'practice',tag:'playing it cold',
 def:'Performing written music on first encounter, without stopping to work it out.',
 why:'It is pattern recognition rather than decoding. Fluent readers see chord shapes and scale fragments, not individual dots.',
 watch:'Never stop to fix mistakes while reading. Keeping time is the skill being trained; accuracy comes second and arrives later.'},
{t:'The Practice Loop',cat:'practice',tag:'record, listen, adjust',
 def:'Recording yourself, listening back critically, identifying one specific problem and practising that alone.',
 why:'Playing and evaluating at the same time is nearly impossible. Recording separates the two jobs so each can be done properly.',
 watch:'Almost everyone finds their timing is worse than they thought and their tone is better. Both are useful information.'}
];
