/* ============================================================
   OVERTONE — THEORY CORE
   Every pitch set in the app is defined here as semitone offsets
   from a root (0 = the root itself). Nothing is hard-coded to a key.
   ============================================================ */
window.OT = window.OT || {};

OT.SHARP = ['C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B'];
OT.FLAT  = ['C','D♭','D','E♭','E','F','G♭','G','A♭','A','B♭','B'];

/* Keys that are conventionally written with flats */
OT.FLAT_KEYS = [1,3,5,8,10];

/* ---- INTERVALS (ear training + the interval ruler) ---- */
OT.INTERVALS = [
  {s:0,  n:'Unison',          sh:'P1', cue:'The same note twice, the reference point.'},
  {s:1,  n:'Minor 2nd',       sh:'m2', cue:'The Jaws shark motif. Maximum tension in one step.'},
  {s:2,  n:'Major 2nd',       sh:'M2', cue:'The first two notes of Happy Birthday.'},
  {s:3,  n:'Minor 3rd',       sh:'m3', cue:'Smoke on the Water. The sad-chord interval.'},
  {s:4,  n:'Major 3rd',       sh:'M3', cue:'When the Saints Go Marching In. The happy-chord interval.'},
  {s:5,  n:'Perfect 4th',     sh:'P4', cue:'Here Comes the Bride. Open and heraldic.'},
  {s:6,  n:'Tritone',         sh:'TT', cue:'The Simpsons theme opening. Restless, unresolved.'},
  {s:7,  n:'Perfect 5th',     sh:'P5', cue:'Twinkle Twinkle, first leap. The most stable interval after the octave.'},
  {s:8,  n:'Minor 6th',       sh:'m6', cue:'The Entertainer. Wistful, slightly aching.'},
  {s:9,  n:'Major 6th',       sh:'M6', cue:'NBC chimes. Warm and open.'},
  {s:10, n:'Minor 7th',       sh:'m7', cue:'Star Trek original theme leap. Bluesy pull.'},
  {s:11, n:'Major 7th',       sh:'M7', cue:'Take On Me chorus leap. Bright, almost painful reach.'},
  {s:12, n:'Octave',          sh:'P8', cue:'Somewhere Over the Rainbow, first two notes.'}
];
/* ---- SCALES & MODES ---- */
OT.SCALES = [
  /* — the parent system — */
  {id:'ionian', n:'Major (Ionian)', alt:'The parent scale', cat:'major', mood:'bright',
   iv:[0,2,4,5,7,9,11], deg:['1','2','3','4','5','6','7'],
   read:'Whole–whole–half–whole–whole–whole–half. The reference every other scale gets described against.',
   ctx:'A huge amount of Western pop, folk and classical music is in it or measured from it. Its power is the leading tone: that 7th sits a half-step under the root and leans hard toward home.',
   trap:'Playing it only from C. The pattern is the scale. Move it to all twelve roots or you have learned one key, not one scale.'},
  {id:'aeolian', n:'Natural Minor (Aeolian)', alt:'The relative minor', cat:'minor', mood:'dark',
   iv:[0,2,3,5,7,8,10], deg:['1','2','♭3','4','5','♭6','♭7'],
   read:'Same seven notes as its relative major, started three half-steps lower. A minor uses the notes of C major.',
   ctx:'The default sad scale. Because the 7th is flat there is no leading tone, so it sounds ancient and unhurried rather than urgent.',
   trap:'Expecting a strong V–i cadence. You will not get one here. That is exactly why harmonic minor exists.'},
  /* — the modes — */
  {id:'dorian', n:'Dorian', alt:'Minor with a bright 6th', cat:'mode', mood:'cool',
   iv:[0,2,3,5,7,9,10], deg:['1','2','♭3','4','5','6','♭7'],
   read:'Natural minor with the 6th raised. One note different, completely different attitude.',
   ctx:'The funk and folk minor. That major 6th keeps it from collapsing into sadness; it sounds capable rather than defeated. Miles Davis built So What on it.',
   trap:'It only reads as Dorian if the 6th actually appears. Skip it and you are just playing natural minor.'},
  {id:'phrygian', n:'Phrygian', alt:'Minor with a flat 2nd', cat:'mode', mood:'dark',
   iv:[0,1,3,5,7,8,10], deg:['1','♭2','♭3','4','5','♭6','♭7'],
   read:'Natural minor with the 2nd lowered. The half-step right above the root is the whole identity.',
   ctx:'Flamenco, metal and tense film scoring all lean on this sound. The ♭2 leaning down onto the root is one of the strongest gravitational pulls in music.',
   trap:'Treating it as a riff scale only. The ♭2 needs to land against the root to register. Bury it in the middle of a run and the colour disappears.'},
  {id:'lydian', n:'Lydian', alt:'Major with a raised 4th', cat:'mode', mood:'bright',
   iv:[0,2,4,6,7,9,11], deg:['1','2','3','♯4','5','6','7'],
   read:'The major scale with the 4th raised a half-step, putting a tritone between the root and the 4th.',
   ctx:'Wonder, openness and lift. The raised 4th keeps major from settling completely, which makes the harmony feel as if it is reaching past the horizon.',
   trap:'The ♯4 wants to resolve upward. Leaning on it is the effect; resolving it immediately throws the colour away.'},
  {id:'mixolydian', n:'Mixolydian', alt:'Major with a flat 7th', cat:'mode', mood:'bright',
   iv:[0,2,4,5,7,9,10], deg:['1','2','3','4','5','6','♭7'],
   read:'Major with a lowered 7th, which removes the leading tone and softens the pull home.',
   ctx:'Rock, blues, folk and roots music. Losing the leading tone makes it sound open-ended and travelling rather than resolved.',
   trap:'It is still a major-quality scale. Playing it like minor pentatonic misses the major 3rd that gives it the swagger.'},
  {id:'locrian', n:'Locrian', alt:'The unstable one', cat:'mode', mood:'dark',
   iv:[0,1,3,5,6,8,10], deg:['1','♭2','♭3','4','♭5','♭6','♭7'],
   read:'Flat 2 and flat 5. The 5th being diminished means the tonic chord itself is unstable.',
   ctx:'Rarely a home key, mostly a colour over half-diminished chords, or a deliberate refusal to give the listener ground to stand on.',
   trap:'Trying to write a tune that rests here. Without a stable fifth there is nothing to rest on; use it for passage, not arrival.'},
  /* — minor variants — */
  {id:'harmonic', n:'Harmonic Minor', alt:'Minor with the leading tone restored', cat:'minor', mood:'dark',
   iv:[0,2,3,5,7,8,11], deg:['1','2','♭3','4','5','♭6','7'],
   read:'Natural minor with the 7th raised, which rebuilds the leading tone and turns the v chord into a real V7.',
   ctx:'Classical minor-key harmony, metal, and the whole "ancient east" trope. The augmented second between ♭6 and 7 is the exotic-sounding gap.',
   trap:'The ♭6–7 leap is a big step. Composers usually smooth it in melodies and save it for the harmony. That is precisely why melodic minor was invented.'},
  {id:'melodic', n:'Melodic Minor', alt:'Jazz minor', cat:'minor', mood:'cool',
   iv:[0,2,3,5,7,9,11], deg:['1','2','♭3','4','5','6','7'],
   read:'Minor with both the 6th and 7th raised: a major scale with a flat 3rd, effectively.',
   ctx:'Classically it raises those notes ascending and reverts descending. Jazz just uses the ascending form in both directions and calls it the jazz minor.',
   trap:'It sits between two worlds. Lean too far and it sounds major; hide the raised tones and it sounds like plain minor.'},
  /* — pentatonics & blues — */
  {id:'majpent', n:'Major Pentatonic', alt:'Five notes, no wrong ones', cat:'pentatonic', mood:'bright',
   iv:[0,2,4,7,9], deg:['1','2','3','5','6'],
   read:'The major scale with the 4th and 7th removed, the two notes that create half-step tension.',
   ctx:'Because the half-steps are gone almost any combination sounds consonant. Nearly every musical culture on earth arrived at some version of it independently.',
   trap:'Safe becomes bland fast. The removed notes are where the tension lives, so put them back once the shape is under your fingers.'},
  {id:'minpent', n:'Minor Pentatonic', alt:'The first scale every guitarist learns', cat:'pentatonic', mood:'dark',
   iv:[0,3,5,7,10], deg:['1','♭3','4','5','♭7'],
   read:'Natural minor without the 2nd and 6th. Five notes, one shape, instant attitude.',
   ctx:'Rock, blues, soul and countless guitar solos. Five notes are enough for strong melodic identity without many avoid notes.',
   trap:'Box-one syndrome. Learning one shape and staying in it is why so many solos sound identical.'},
  {id:'blues', n:'Blues Scale', alt:'Minor pentatonic plus the blue note', cat:'pentatonic', mood:'cool',
   iv:[0,3,5,6,7,10], deg:['1','♭3','4','♭5','5','♭7'],
   read:'Minor pentatonic with a chromatic passing tone between the 4th and 5th: the blue note.',
   ctx:'That ♭5 is not really a scale degree, it is a bend. On guitar and voice it lives between the frets, which is why notation never quite captures the blues.',
   trap:'Sitting on the blue note. It is a passing colour; hold it and it sounds like a mistake rather than an inflection.'},
  {id:'majpent-jp', n:'Hirajōshi', alt:'Japanese pentatonic', cat:'world', mood:'dark',
   iv:[0,2,3,7,8], deg:['1','2','♭3','5','♭6'],
   read:'A Japanese five-note scale built on koto tuning, with two half-steps that give it its distinct sting.',
   ctx:'Closely associated with traditional Japanese string repertoire. The missing third and close half-steps make it feel spacious and tense at once.',
   trap:'It is a real tradition, not a costume. Used lazily it becomes the musical equivalent of a stock backdrop.'},
  /* — symmetrical & advanced — */
  {id:'wholetone', n:'Whole Tone', alt:'Six equal steps', cat:'symmetric', mood:'cool',
   iv:[0,2,4,6,8,10], deg:['1','2','3','♯4','♯5','♭7'],
   read:'Every step is a whole tone. No half-steps means no leading tone and no clear root.',
   ctx:'Debussy used it for weightlessness and ambiguity. It remains a standard colour for dreamlike, suspended or surreal writing.',
   trap:'There are only two whole-tone scales in existence. Because it is symmetrical, it disorients quickly: a little is atmosphere, a lot is nausea.'},
  {id:'octatonic', n:'Octatonic (Diminished)', alt:'Half–whole', cat:'symmetric', mood:'dark',
   iv:[0,1,3,4,6,7,9,10], deg:['1','♭2','♭3','3','♯4','5','6','♭7'],
   read:'Alternating half and whole steps, eight notes per octave. Contains four diminished chords stacked inside it.',
   ctx:'Stravinsky, horror scoring and tense contemporary composition. It supplies dominant-7♭9 colour on demand.',
   trap:'Its symmetry makes everything sound related to everything, which reads as "tense" for about eight bars and then as "unfocused".'},
  {id:'phrygdom', n:'Phrygian Dominant', alt:'The fifth mode of harmonic minor', cat:'mode', mood:'dark',
   iv:[0,1,4,5,7,8,10], deg:['1','♭2','3','4','5','♭6','♭7'],
   read:'Phrygian with a major 3rd, a flat 2 sitting directly above a major triad.',
   ctx:'Flamenco, klezmer and metal all lean heavily on this colour. The gap between ♭2 and 3 is the augmented second that makes it sound so specific.',
   trap:'Very strongly flavoured. It is almost impossible to use casually; it will dominate whatever you put it in.'},
  {id:'harmmaj', n:'Harmonic Major', alt:'Major with a flat 6th', cat:'major', mood:'cool',
   iv:[0,2,4,5,7,8,11], deg:['1','2','3','4','5','♭6','7'],
   read:'The major scale with the 6th lowered, borrowing one note from the parallel minor.',
   ctx:'The sound of bittersweet: major enough to feel warm, with one note of grief in it. Useful whenever a melody needs hope without complete resolution.',
   trap:'Easy to mistake for a wrong note rather than a choice. It needs harmonic support underneath to read as intentional.',}
];

/* ---- CHORDS ---- */
OT.CHORDS = [
  {id:'maj',    n:'Major',              sym:'',      iv:[0,4,7],        cat:'triad', mood:'bright',
   read:'Root, major 3rd, perfect 5th.', ctx:'The stable, resolved chord. I, IV and V in any major key.',
   trap:'Inversions change the feeling completely: the same three notes over a different bass is a different chord in practice.'},
  {id:'min',    n:'Minor',              sym:'m',     iv:[0,3,7],        cat:'triad', mood:'dark',
   read:'Root, minor 3rd, perfect 5th.', ctx:'One semitone away from major and emotionally a world apart.',
   trap:'Minor is not automatically sad. Context and tempo decide. Plenty of dance music is entirely minor.'},
  {id:'dim',    n:'Diminished',         sym:'°',     iv:[0,3,6],        cat:'triad', mood:'dark',
   read:'Two stacked minor 3rds. The 5th is flattened, so nothing is stable.',
   ctx:'vii° in major. A tension chord that exists to move somewhere else.',
   trap:'Leaving it unresolved reads as unfinished rather than mysterious.'},
  {id:'aug',    n:'Augmented',          sym:'+',     iv:[0,4,8],        cat:'triad', mood:'cool',
   read:'Two stacked major 3rds. Perfectly symmetrical.',
   ctx:'Dream sequences, transformation, and the moment before something changes.',
   trap:'Every inversion contains the same intervals, so it has no natural root; it floats until something else grounds it.'},
  {id:'sus2',   n:'Suspended 2nd',      sym:'sus2',  iv:[0,2,7],        cat:'triad', mood:'cool',
   read:'The 3rd replaced by the 2nd.', ctx:'Open and unresolved. Post-rock, ambient music and spacious guitar writing lean on it.',
   trap:'It has no 3rd, so it is neither major nor minor. That ambiguity is the point, not a gap to fill.'},
  {id:'sus4',   n:'Suspended 4th',      sym:'sus4',  iv:[0,5,7],        cat:'triad', mood:'cool',
   read:'The 3rd replaced by the 4th.', ctx:'Classic delay-the-payoff device: sus4 then resolve down to the 3rd.',
   trap:'The resolution is where the emotion is. Never resolving it is a style choice you should make on purpose.'},
  {id:'7',      n:'Dominant 7th',       sym:'7',     iv:[0,4,7,10],     cat:'seventh', mood:'bright',
   read:'Major triad plus a minor 7th. Contains a tritone between the 3rd and 7th.',
   ctx:'The engine of functional harmony. That internal tritone is what makes V7 pull so hard toward I.',
   trap:'In blues it never resolves: the tension becomes the texture. Different rules apply there.'},
  {id:'maj7',   n:'Major 7th',          sym:'maj7',  iv:[0,4,7,11],     cat:'seventh', mood:'bright',
   read:'Major triad plus a major 7th.', ctx:'Warm and reflective. A core colour in jazz, neo-soul, R&B and city pop.',
   trap:'Every chord as maj7 turns to syrup. It works because it contrasts with plainer chords around it.'},
  {id:'m7',     n:'Minor 7th',          sym:'m7',    iv:[0,3,7,10],     cat:'seventh', mood:'dark',
   read:'Minor triad plus a minor 7th.', ctx:'Smooth and unhurried. ii7 in a ii–V–I, and the backbone of groove music.',
   trap:'It is much softer than a plain minor triad. If you need actual sadness, the triad hits harder.'},
  {id:'m7b5',   n:'Half-Diminished',    sym:'m7♭5',  iv:[0,3,6,10],     cat:'seventh', mood:'dark',
   read:'Diminished triad plus a minor 7th.', ctx:'The iiø in a minor ii–V–i. Elegant rather than merely dark.',
   trap:'Constantly confused with the fully diminished 7th. The 7th is the difference and it changes everything.'},
  {id:'dim7',   n:'Diminished 7th',     sym:'°7',    iv:[0,3,6,9],      cat:'seventh', mood:'dark',
   read:'Three stacked minor 3rds. Fully symmetrical.',
   ctx:'The great pivot chord: any of its four notes can act as the root, so it can modulate almost anywhere.',
   trap:'Overuse makes everything sound like silent-film peril. Use it to travel, not to sit.'},
  {id:'mmaj7',  n:'Minor-Major 7th',    sym:'m(maj7)',iv:[0,3,7,11],    cat:'seventh', mood:'dark',
   read:'Minor triad with a major 7th on top.', ctx:'The James Bond chord. Simultaneously sad and menacing.',
   trap:'Extremely strong flavour. One is a statement; four in a row is a horror cue.'},
  {id:'6',      n:'Major 6th',          sym:'6',     iv:[0,4,7,9],      cat:'extended', mood:'bright',
   read:'Major triad plus a 6th instead of a 7th.', ctx:'Resolved but not final. The classic vintage ending chord.',
   trap:'Shares all its notes with a minor 7th a third below. Which chord you hear depends on the bass.'},
  {id:'add9',   n:'Add 9',              sym:'add9',  iv:[0,4,7,14],     cat:'extended', mood:'bright',
   read:'Major triad with a 9th added and no 7th.', ctx:'Bright, modern and open. Everywhere in pop and film scoring.',
   trap:'Voice it too tightly and the 9th clashes with the root. Give it space, usually an octave or more.'},
  {id:'9',      n:'Dominant 9th',       sym:'9',     iv:[0,4,7,10,14],  cat:'extended', mood:'bright',
   read:'Dominant 7th with the 9th stacked on top.', ctx:'Funk, soul and gospel. The chord that makes a groove feel expensive.',
   trap:'Five notes gets crowded fast. Drop the 5th first, it is the least informative note in the chord.'},
  {id:'m9',     n:'Minor 9th',          sym:'m9',    iv:[0,3,7,10,14],  cat:'extended', mood:'dark',
   read:'Minor 7th with a 9th.', ctx:'Lush and nocturnal. Common in neo-soul, jazz, R&B and city pop.',
   trap:'Needs register. Played low it turns to mud. Keep extensions above middle C.'},
  {id:'maj9',   n:'Major 9th',          sym:'maj9',  iv:[0,4,7,11,14],  cat:'extended', mood:'bright',
   read:'Major 7th with a 9th.', ctx:'Warm, wide and settled: a polished tonic colour in jazz, soul and modern pop harmony.',
   trap:'So consonant it can drift into wallpaper. It needs somewhere to have come from.'},
  {id:'7sharp9',n:'7♯9',                sym:'7♯9',   iv:[0,4,7,10,15],  cat:'extended', mood:'cool',
   read:'Dominant 7th with a raised 9th, a major and minor 3rd in the same chord.',
   ctx:'The Hendrix chord. Both thirds at once is the whole point: it is the blues contradiction made into a single sound.',
   trap:'It only works with grit. Played politely on a clean piano it just sounds wrong.'}
];

/* ---- PROGRESSIONS ---- deg = scale degree index, q = chord id ---- */
OT.PROGS = [
  {id:'axis',    n:'I–V–vi–IV', alt:'The Axis', cat:'pop', mood:'bright',
   steps:[[0,'maj'],[7,'maj'],[9,'min'],[5,'maj']],
   read:'Four chords, endlessly recyclable, and the backbone of a startling share of chart music since the 1990s.',
   ctx:'It works because it never truly resolves: the IV at the end throws you back to the start, so the loop feels inevitable.',
   trap:'The melody has to do the work. The progression alone is common property.'},
  {id:'sensitive',n:'vi–IV–I–V', alt:'The sensitive rotation', cat:'pop', mood:'dark',
   steps:[[9,'min'],[5,'maj'],[0,'maj'],[7,'maj']],
   read:'The same four chords as the Axis, rotated to begin on the relative minor.',
   ctx:'Starting minor and arriving major is the musical shape of a story turning out alright.',
   trap:'Rotation changes everything about how a loop feels. Same chords, different emotional arc.'},
  {id:'251',     n:'ii–V–I', alt:'The jazz cadence', cat:'jazz', mood:'bright',
   steps:[[2,'m7'],[7,'7'],[0,'maj7']],
   read:'The strongest functional resolution in Western harmony, and the unit jazz musicians think in.',
   ctx:'Every note moves the shortest possible distance, and the tritone inside the V7 resolves outward into the I. It feels like gravity because it is.',
   trap:'In minor it becomes iiø–V7–i, which is a different colour entirely despite the identical roman numerals.'},
  {id:'1451',    n:'I–IV–V', alt:'Three chords', cat:'rock', mood:'bright',
   steps:[[0,'maj'],[5,'maj'],[7,'maj']],
   read:'The three major triads in a key. Rock and roll, folk, country, punk.',
   ctx:'These three chords contain all seven notes of the major scale between them, which is why they can harmonise almost any diatonic melody.',
   trap:'Add 7ths and you are in blues. Same roots, completely different genre.'},
  {id:'12bar',   n:'12-Bar Blues', alt:'The form', cat:'blues', mood:'cool',
   steps:[[0,'7'],[0,'7'],[0,'7'],[0,'7'],[5,'7'],[5,'7'],[0,'7'],[0,'7'],[7,'7'],[5,'7'],[0,'7'],[7,'7']],
   read:'Twelve bars: four on I, two on IV, two on I, then V–IV–I–V.',
   ctx:'A shared form rather than a song. Two strangers can play it together in any key without discussion. That portability is why it spread across the whole century.',
   trap:'The last two bars are the turnaround, and that is where the personality lives. Everything before it is scaffolding.'},
  {id:'andalusian',n:'i–♭VII–♭VI–V', alt:'Andalusian cadence', cat:'classical', mood:'dark',
   steps:[[0,'min'],[10,'maj'],[8,'maj'],[7,'maj']],
   read:'A stepwise descent from the tonic down to a major V: the flamenco cadence.',
   ctx:'That final major chord in a minor key is the Phrygian dominant sound. Descending bass plus a bright surprise at the bottom.',
   trap:'It is so recognisable that it arrives with baggage. You are quoting a tradition whether you meant to or not.'},
  {id:'royalroad',n:'IV–V–iii–vi', alt:'The Royal Road', cat:'jpop', mood:'cool',
   steps:[[5,'maj7'],[7,'7'],[4,'m7'],[9,'min']],
   read:'Starts on IV rather than I, so the progression is already in motion before you notice it began.',
   ctx:'Ubiquitous in J-pop and city pop. Often called the ōdō shinkō. The iii–vi at the end is a soft landing rather than a resolution.',
   trap:'It carries an accent. Drop it into a Western rock arrangement and it will still sound distinctly Japanese.'},
  {id:'canon',   n:'Canon (Pachelbel)', alt:'I–V–vi–iii–IV–I–IV–V', cat:'classical', mood:'bright',
   steps:[[0,'maj'],[7,'maj'],[9,'min'],[4,'min'],[5,'maj'],[0,'maj'],[5,'maj'],[7,'maj']],
   read:'A descending bass line harmonised into eight chords that loop seamlessly.',
   ctx:'Three hundred years old and still load-bearing. Its stepwise bass makes it feel like it is constantly, gently falling.',
   trap:'Extremely familiar. Use the bass motion without the exact chords if you want the shape without the association.'},
  {id:'circle',  n:'Circle of Fifths Turnaround', alt:'vi–ii–V–I', cat:'jazz', mood:'cool',
   steps:[[9,'m7'],[2,'m7'],[7,'7'],[0,'maj7']],
   read:'Each root moves down a fifth to the next. The strongest possible root motion, chained.',
   ctx:'Autumn Leaves, Fly Me to the Moon, and a thousand others. Once you hear the falling-fifths pattern you cannot stop hearing it.',
   trap:'It is so strong it can steer a song for you. Break the chain deliberately or it will decide the ending.'},
  {id:'lament',  n:'Lament Bass', alt:'i–♭VII–♭VI–♭VII', cat:'classical', mood:'dark',
   steps:[[0,'min'],[10,'maj'],[8,'maj'],[10,'maj']],
   read:'A chromatic or stepwise descent in the bass used to signal grief since the Baroque.',
   ctx:'Purcell made it famous in art music, but the device works anywhere. A repeating descending bass reads as sinking almost immediately.',
   trap:'The device is the descent, not the specific chords. Keep the bass falling and you can reharmonise freely.'},
  {id:'plagal',  n:'IV–I', alt:'The Amen cadence', cat:'classical', mood:'bright',
   steps:[[5,'maj'],[0,'maj']],
   read:'A softer alternative to V–I, with no leading tone pushing you home.',
   ctx:'Hymns, gospel and any ending that should feel like a settling rather than an arrival.',
   trap:'It is gentle by nature. If a piece needs a decisive full stop, this is the wrong cadence.'},
  {id:'picardy', n:'Picardy Third', alt:'i…I', cat:'classical', mood:'bright',
   steps:[[0,'min'],[5,'min'],[7,'maj'],[0,'maj']],
   read:'A piece in minor that ends on a major tonic chord.',
   ctx:'Centuries old, and still the most efficient way to make an ending feel like unexpected hope after darkness.',
   trap:'It only lands if the minor has been genuinely established first. Switch too early and it reads as indecision.',}
];

/* ---- RHYTHM PATTERNS (16th grid, 16 slots) ---- */
OT.RHYTHMS = [
  {id:'rock', n:'Straight Rock', bpm:110, sig:'4/4', cat:'rock', beats:4,
   k:[1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0], s:[0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0], h:[1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0],
   read:'Kick on 1 and 3, snare on 2 and 4, eighth notes on the hats.',
   ctx:'The default groove of most Western popular music since the 1960s. Everything else is a variation on it.',
   trap:'The snare on 2 and 4 is the backbeat and it is non-negotiable. Move it and the genre changes.'},
  {id:'four', n:'Four on the Floor', bpm:126, sig:'4/4', cat:'dance', beats:4,
   k:[1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0], s:[0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0], h:[0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0],
   read:'Kick on every quarter note, hats on the off-beats.',
   ctx:'Disco, house and techno. The relentless pulse removes ambiguity about where the beat is, which is what makes it danceable.',
   trap:'Without off-beat hats or percussion it is just a metronome. The space between kicks is where the groove lives.'},
  {id:'funk', n:'Syncopated Funk', bpm:98, sig:'4/4', cat:'funk', beats:4,
   k:[1,0,0,1,0,0,1,0,0,0,1,0,0,1,0,0], s:[0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1], h:[1,0,1,1,1,0,1,0,1,1,1,0,1,0,1,1],
   read:'Kick and snare deliberately displaced off the main beats, with sixteenth-note hats filling the grid.',
   ctx:'The pocket is defined by what is missing. Funk works because your ear supplies the beats the drummer refuses to play.',
   trap:'If it is easy to count, it is not funky yet. Feel comes before arithmetic here.'},
  {id:'boom', n:'Boom Bap', bpm:90, sig:'4/4', cat:'hiphop', beats:4,
   k:[1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0], s:[0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0], h:[1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0],
   read:'Hard snare on the backbeat with a kick pattern that leans slightly late.',
   ctx:'The sound of sampled 90s hip-hop. Often deliberately not quantised; the human drift is the character.',
   trap:'Perfectly gridded boom bap sounds sterile. The swing and the slop are the style.'},
  {id:'shuffle', n:'Shuffle / Swing', bpm:120, sig:'12/8', cat:'blues', beats:4,
   k:[1,0,0,0,0,0,1,0,0,0,0,0], s:[0,0,0,1,0,0,0,0,0,1,0,0], h:[1,0,1,1,0,1,1,0,1,1,0,1],
   read:'Beats divided into three instead of two, giving the long–short lope of blues and swing.',
   ctx:'Written as triplets, felt as a limp. Nearly all jazz and blues before 1960 is in this feel even when notated straight.',
   trap:'Swing is a spectrum, not a switch. How hard you swing is a stylistic decision on every tune.'},
  {id:'bossa', n:'Bossa Nova', bpm:132, sig:'4/4', cat:'latin', beats:4,
   k:[1,0,0,1,0,0,1,0,1,0,0,1,0,0,1,0], s:[0,0,1,0,0,1,0,0,0,1,0,0,1,0,0,0], h:[1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0],
   read:'A two-bar clave-derived pattern with a gentle, continuous surface and no backbeat.',
   ctx:'Brazilian by origin and a staple of jazz, lounge and singer-songwriter arranging whenever the music needs to feel unhurried.',
   trap:'It should never feel like it is pushing. Play it hard and it stops being bossa.'},
  {id:'amen', n:'Breakbeat', bpm:170, sig:'4/4', cat:'electronic', beats:4,
   k:[1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0], s:[0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,1], h:[1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0],
   read:'A chopped and displaced funk break, played fast.',
   ctx:'Jungle, drum and bass and breakbeat culture are built around it: a few seconds of drumming rearranged into an entire rhythmic language.',
   trap:'Speed does not create energy on its own. The displacement of the snare is what makes it move.'},
  {id:'waltz', n:'Waltz', bpm:150, sig:'3/4', cat:'classical', beats:3,
   k:[1,0,0,0,0,0,0,0,0], s:[0,0,0,1,0,0,1,0,0], h:[1,0,0,1,0,0,1,0,0],
   read:'Three beats to the bar with a strong downbeat and two lighter beats after it.',
   ctx:'Three-four can feel elegant, circular or weightless depending on tempo and accent. The lilt comes from one strong beat followed by two lighter ones.',
   trap:'The emphasis must stay on beat one. Even it out and it stops spinning.'}
];

/* ---- STRING INSTRUMENT TUNINGS (low → high) ---- */
OT.TUNINGS = [
  {id:'gtr-std',  n:'Guitar · Standard',    inst:'guitar', notes:[4,9,2,7,11,4],  oct:[2,2,3,3,3,4], frets:16,
   note:'EADGBE. The B string breaks the pattern of fourths, which is why chord shapes look asymmetrical.'},
  {id:'gtr-drop', n:'Guitar · Drop D',      inst:'guitar', notes:[2,9,2,7,11,4],  oct:[2,2,3,3,3,4], frets:16,
   note:'Low E dropped to D. One finger plays a power chord, and the low D rings under everything.'},
  {id:'gtr-dadgad',n:'Guitar · DADGAD',     inst:'guitar', notes:[2,9,2,7,9,2],   oct:[2,2,3,3,3,4], frets:16,
   note:'Celtic and fingerstyle standard. Open strings form a Dsus4, so drones come free.'},
  {id:'gtr-openg',n:'Guitar · Open G',      inst:'guitar', notes:[2,7,2,7,11,2],  oct:[2,2,3,3,3,4], frets:16,
   note:'The Keith Richards tuning. Strum open and you already have a G major chord.'},
  {id:'bass-std', n:'Bass · Standard',      inst:'bass',   notes:[4,9,2,7],       oct:[1,1,2,2],     frets:16,
   note:'EADG, an octave below the guitar\u2019s bottom four. Root and fifth covers most of the job.'},
  {id:'uke-std',  n:'Ukulele · Standard',   inst:'ukulele',notes:[7,0,4,9],       oct:[4,4,4,4],     frets:14,
   note:'GCEA with a re-entrant high G, so the strings are not in pitch order. That is what gives it the bounce.'},
  {id:'mando',    n:'Mandolin · Standard',  inst:'mandolin',notes:[7,2,9,4],      oct:[3,4,4,5],     frets:16,
   note:'GDAE in fifths, same as a violin. Wide intervals mean wide chord shapes.'}
];

/* ---- CIRCLE OF FIFTHS ---- */
OT.CIRCLE = [
  {maj:'C',  min:'Am',  pc:0,  sig:'–'},
  {maj:'G',  min:'Em',  pc:7,  sig:'1♯'},
  {maj:'D',  min:'Bm',  pc:2,  sig:'2♯'},
  {maj:'A',  min:'F♯m', pc:9,  sig:'3♯'},
  {maj:'E',  min:'C♯m', pc:4,  sig:'4♯'},
  {maj:'B',  min:'G♯m', pc:11, sig:'5♯'},
  {maj:'G♭', min:'E♭m', pc:6,  sig:'6♭'},
  {maj:'D♭', min:'B♭m', pc:1,  sig:'5♭'},
  {maj:'A♭', min:'Fm',  pc:8,  sig:'4♭'},
  {maj:'E♭', min:'Cm',  pc:3,  sig:'3♭'},
  {maj:'B♭', min:'Gm',  pc:10, sig:'2♭'},
  {maj:'F',  min:'Dm',  pc:5,  sig:'1♭'}
];
