/* ============================================================
   OVERTONE — WORLD, RHYTHM & MOTIF PACK
   Adds: cultural scales, a much larger rhythm library,
   playable phrases, and the regional guide.

   ON THE PHRASES — two kinds, both clean to play in full:
   kind:'etude'  original phrases written for this site to
                 isolate one device. Not transcriptions.
   kind:'trad'   traditional or public-domain melodies.

   Format: mel/bass = [[semitonesFromRoot | null for rest, beats], ...]
   ============================================================ */
window.OT = window.OT || {};

/* ------------------------------------------------------------
   1 · MORE SCALES — the ones outside the Western seven
   ------------------------------------------------------------ */
OT.SCALES.push(
  {id:'insen', n:'In Sen', alt:'Japanese, koto tuning', cat:'world', mood:'dark',
   iv:[0,1,5,7,10], deg:['1','♭2','4','5','♭7'],
   read:'Five notes with a half-step directly above the root and a wide leap after it.',
   ctx:'One of the standard Japanese pentatonics, closely tied to koto and shakuhachi repertoire. The gap where a third would be is what makes it sound suspended.',
   trap:'The missing third means it is neither major nor minor. Harmonising it with Western triads flattens exactly what makes it distinctive.', culture:'Japan'},
  {id:'hijaz', n:'Hijaz', alt:'Maqam Hijaz · Arabic', cat:'world', mood:'dark',
   iv:[0,1,4,5,7,8,10], deg:['1','♭2','3','4','5','♭6','♭7'],
   read:'A half-step above the root followed by an augmented second up to the major third.',
   ctx:'A core maqam across Arabic, Turkish and Greek traditions, and the parent of the flamenco sound. The same interval pattern appears in klezmer as Ahava Rabbah.',
   trap:'Real maqam practice includes microtonal inflections and rules about melodic direction that a twelve-note keyboard simply cannot express. This is the approximation, not the tradition.', culture:'Middle East · North Africa'},
  {id:'bhairav', n:'Bhairav', alt:'North Indian thāt', cat:'world', mood:'dark',
   iv:[0,1,4,5,7,8,11], deg:['1','♭2','3','4','5','♭6','7'],
   read:'Flat second and flat sixth against a major third and major seventh: two augmented seconds in one scale.',
   ctx:'A morning rāga family in Hindustani music, performed over a drone rather than chord changes. The drone is what lets such wide intervals feel stable.',
   trap:'A rāga is not a scale. It carries required phrases, ornaments, ascent and descent rules and a time of day. The note set is the smallest part of it.', culture:'North India'},
  {id:'pelog', n:'Pelog (approx.)', alt:'Javanese gamelan', cat:'world', mood:'cool',
   iv:[0,1,3,7,8], deg:['1','♭2','♭3','5','♭6'],
   read:'A five-note approximation of a Javanese tuning that does not actually fit the Western twelve-note grid.',
   ctx:'Gamelan ensembles are tuned as a set, and no two gamelans are tuned identically. Debussy heard one in Paris in 1889 and Western harmony has never fully recovered.',
   trap:'This is genuinely a translation with information lost. Real pelog intervals fall between our keys. Treat it as a signpost toward the tradition, not the thing itself.', culture:'Java · Bali'},
  {id:'blues-maj', n:'Major Blues', alt:'The other blues scale', cat:'pentatonic', mood:'cool',
   iv:[0,2,3,4,7,9], deg:['1','2','♭3','3','5','6'],
   read:'Major pentatonic with a chromatic passing tone between the 2nd and 3rd.',
   ctx:'The sound of country, gospel and a lot of early rock and roll. Brighter than minor blues while keeping the blue inflection.',
   trap:'The ♭3 must pass through to the 3. Sitting on it turns the whole thing minor and loses the point.', culture:'African-American tradition'},
  {id:'romanian', n:'Ukrainian Dorian', alt:'Altered Dorian · klezmer',cat:'world', mood:'cool',
   iv:[0,2,3,6,7,9,10], deg:['1','2','♭3','♯4','5','6','♭7'],
   read:'Dorian with a raised fourth, producing a tritone against the root.',
   ctx:'Widespread in Eastern European, klezmer and Romanian folk music. The raised fourth over a minor third is the sound of the whole region.',
   trap:'It is often confused with Lydian because of the sharp fourth, but the flat third puts it in a completely different emotional place.', culture:'Eastern Europe · Klezmer'},
  {id:'egyptian', n:'Egyptian Pentatonic', alt:'Suspended pentatonic', cat:'pentatonic', mood:'cool',
   iv:[0,2,5,7,10], deg:['1','2','4','5','♭7'],
   read:'A five-note scale built entirely from seconds, fourths and fifths, no thirds at all.',
   ctx:'A rotation of the major pentatonic. Because it has no third it sounds open and unresolved, which is why it turns up constantly in ambient and modal writing.',
   trap:'Rotations of the same five notes are not the same scale. Which note you treat as home changes everything you hear.', culture:'Widespread · Asia and Africa'}
);

/* ------------------------------------------------------------
   2 · MORE RHYTHM — odd meters and world grooves
   steps are 16ths unless the pattern says otherwise
   ------------------------------------------------------------ */
OT.RHYTHMS.push(
  {id:'son-clave', n:'Son Clave (3-2)', bpm:96, sig:'4/4', cat:'latin', beats:4,
   k:[1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0],
   s:[1,0,0,1,0,0,1,0,0,0,1,0,1,0,0,0],
   h:[1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0],
   read:'The five-stroke key of Afro-Cuban music, spread across two bars in a three-then-two grouping.',
   ctx:'Everything in a salsa arrangement aligns to it. It arrived in Cuba from West Africa and from there shaped nearly all popular music in the Americas.',
   trap:'Direction is not decorative. Playing 2-3 clave over a 3-2 arrangement is an actual error that every musician in the room will hear.'},
  {id:'rumba-clave', n:'Rumba Clave (3-2)', bpm:100, sig:'4/4', cat:'latin', beats:4,
   k:[1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0],
   s:[1,0,0,1,0,0,0,1,0,0,1,0,1,0,0,0],
   h:[1,0,1,1,0,1,1,0,1,0,1,1,0,1,1,0],
   read:'Like son clave, but the third stroke lands a sixteenth later.',
   ctx:'Older and more African than son clave, used in rumba and much sacred drumming. That single displaced stroke changes the entire feel.',
   trap:'The difference from son clave is one sixteenth note. It is also the difference between two entire genres.'},
  {id:'tresillo', n:'Tresillo', bpm:100, sig:'4/4', cat:'latin', beats:4,
   k:[1,0,0,1,0,0,1,0,1,0,0,1,0,0,1,0],
   s:[0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0],
   h:[1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0],
   read:'Three strokes across four beats, at 3+3+2 sixteenths.',
   ctx:'The most widespread rhythmic cell on earth. It underlies reggaeton, dancehall, trap hi-hats, New Orleans piano and half of pop radio.',
   trap:'It is felt as a lopsided pulse rather than counted. Count it too carefully and you will play it stiffly.'},
  {id:'samba', n:'Samba', bpm:100, sig:'4/4', cat:'latin', beats:4,
   k:[1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1],
   s:[0,0,1,0,0,1,0,0,0,0,1,0,0,1,0,1],
   h:[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
   read:'Continuous sixteenths with the surdo accenting beat two rather than beat one.',
   ctx:'Brazilian, and rhythmically the opposite of a rock backbeat: the weight falls on the second beat, which is why samba feels like it is always leaning forward.',
   trap:'Written in 2/4 in Brazil and 4/4 everywhere else. The notation differs; the feel does not.'},
  {id:'bembe', n:'Bembé Bell (6/8)', bpm:104, sig:'6/8', cat:'african', beats:6,
   k:[1,0,0,1,0,0,1,0,0,1,0,0],
   s:[1,0,1,0,1,1,0,1,0,1,0,1],
   h:[1,0,1,0,1,0,1,0,1,0,1,0],
   read:'The standard West African bell pattern, twelve pulses grouped in six.',
   ctx:'The organising pattern for a huge amount of West African drumming and the ancestor of clave. Everything in the ensemble locks to the bell.',
   trap:'It can be heard starting in several places and each is valid within its own tradition. Where you feel "one" is a cultural choice, not an objective fact.'},
  {id:'afrobeat', n:'Afrobeat', bpm:112, sig:'4/4', cat:'african', beats:4,
   k:[1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0],
   s:[0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1],
   h:[1,0,1,1,1,0,1,1,1,0,1,1,1,0,1,1],
   read:'Interlocking parts over a steady pulse, with the kit deliberately leaving gaps for percussion.',
   ctx:'Fela Kuti\u2019s fusion of Yoruba rhythm, highlife and James Brown\u2019s funk. Parts are built to interlock rather than to be complete alone.',
   trap:'No single part sounds like the groove. Afrobeat is a system of parts, which is why one drummer cannot play it.'},
  {id:'reggae', n:'One Drop', bpm:76, sig:'4/4', cat:'caribbean', beats:4,
   k:[0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0],
   s:[0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0],
   h:[0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0],
   read:'Beat one is left empty. The kick and rim hit together on beat three.',
   ctx:'Jamaican, and the clearest example anywhere of a groove defined by absence. The missing downbeat is the entire identity.',
   trap:'Adding a kick on beat one makes it a completely different rhythm. The hole is not a gap to fill.'},
  {id:'secondline', n:'Second Line', bpm:92, sig:'4/4', cat:'american', beats:4,
   k:[1,0,0,1,0,0,1,0,0,0,1,0,0,1,0,0],
   s:[0,0,1,0,1,0,0,1,0,1,0,0,1,0,1,0],
   h:[1,0,1,1,1,0,1,1,1,0,1,1,1,0,1,1],
   read:'A New Orleans parade groove built on tresillo with a loose, rolling snare.',
   ctx:'From brass band street processions. It sits between march and swing, and it is the rhythmic root of most New Orleans piano.',
   trap:'It should feel like it is falling forward and just catching itself. Played straight it turns into a march.'},
  {id:'taiko', n:'Taiko · Matsuri', bpm:120, sig:'4/4', cat:'asian', beats:4,
   k:[1,0,0,0,1,0,1,0,1,0,0,0,1,0,1,1],
   s:[0,0,1,0,0,0,0,1,0,0,1,0,0,1,0,0],
   h:[1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0],
   read:'Big drum patterns built from call and response between low and high drums.',
   ctx:'Japanese festival drumming. Modern ensemble taiko is a twentieth-century form built from much older ritual practice.',
   trap:'Dynamics and silence carry the piece. Taiko played at one constant volume loses almost everything.'},
  {id:'teental', n:'Teental (16 beats)', bpm:110, sig:'16 mātrā', cat:'asian', beats:4,
   k:[1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0],
   s:[0,0,1,0,0,0,1,0,1,0,1,0,0,0,1,0],
   h:[1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0],
   read:'The most common tāl in North Indian classical music: sixteen beats in four groups of four.',
   ctx:'Beat one, the sam, is the point everything resolves to. The ninth beat, khali, is deliberately open and unstressed, a marker you feel rather than hear.',
   trap:'It is a cycle, not a bar. Improvisation can run for many minutes and still be counted toward the next sam.'},
  {id:'bulerias', n:'Bulerías (12 count)', bpm:190, sig:'12/8', cat:'european', beats:12,
   k:[1,0,0,1,0,0,1,0,1,0,1,0],
   s:[0,0,1,0,0,1,0,0,1,0,0,1],
   h:[1,1,1,1,1,1,1,1,1,1,1,1],
   read:'A twelve-count flamenco cycle with accents on 12, 3, 6, 8 and 10.',
   ctx:'Andalusian. The compás is clapped, and knowing where the accents fall is what separates participants from spectators at a flamenco gathering.',
   trap:'The cycle is usually counted starting from 12 rather than 1. That is not a quirk; it is how the accents make sense.'},
  {id:'karsilama', n:'Karşılama (9/8)', bpm:150, sig:'9/8', cat:'european', beats:9,
   k:[1,0,0,1,0,0,1,0,0], s:[0,0,1,0,0,1,0,1,0], h:[1,0,1,1,0,1,1,0,1],
   read:'Nine beats grouped 2+2+2+3: three even steps and one long one.',
   ctx:'Turkish and Balkan wedding music. The limp at the end of each cycle is what dancers step to.',
   trap:'Grouping is everything. The same nine beats as 3+2+2+2 is a different dance entirely.'},
  {id:'rachenitsa', n:'Rachenitsa (7/8)', bpm:160, sig:'7/8', cat:'european', beats:7,
   k:[1,0,1,0,1,0,0], s:[0,0,0,0,1,0,0], h:[1,1,1,1,1,1,1],
   read:'Seven beats grouped 2+2+3, with the long group at the end.',
   ctx:'Bulgarian. Odd meters are the default across the Balkans rather than an experiment, and children learn to dance them before they can count them.',
   trap:'Counting to seven will not get you there. Feel it as short–short–long and it becomes obvious.'},
  {id:'jazzswing', n:'Jazz Ride (swing)', bpm:140, sig:'4/4', cat:'jazz', beats:4,
   k:[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
   s:[0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0],
   h:[1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,1],
   read:'The ride cymbal carries the time with a swung triplet feel; the kick mostly stays out of the way.',
   ctx:'From the 1940s onward the ride became the timekeeper and the bass drum became a punctuation instrument rather than a pulse.',
   trap:'Turn the swing slider up. Played straight this pattern is not jazz, it is a rock beat with the wrong accents.'},
  {id:'waltz-jazz', n:'Jazz Waltz (3/4)', bpm:170, sig:'3/4', cat:'jazz', beats:3,
   k:[1,0,0,0,0,0,0,0,0], s:[0,0,0,1,0,0,1,0,0], h:[1,0,1,1,0,1,1,0,1],
   read:'Three beats with a swung ride pattern layered over them.',
   ctx:'Three-four does not have to be a Viennese waltz. Once jazz took it on it became fluid and floating instead of rotating.',
   trap:'Keep the weight on beat one or it stops spinning and becomes an ambiguous 6/8.'},
  {id:'fivefour', n:'Five (3+2)', bpm:150, sig:'5/4', cat:'odd', beats:5,
   k:[1,0,0,0,0,0,1,0,0,0,0,0,0,0,0], s:[0,0,0,1,0,0,0,0,0,1,0,0,0,0,0],
   h:[1,0,1,1,0,1,1,0,1,1,0,1,1,0,1],
   read:'Five beats felt as a group of three followed by a group of two.',
   ctx:'Odd meters feel unstable only until you stop counting. Grouped this way, five becomes as natural as four.',
   trap:'5/4 grouped 2+3 sounds completely different from 3+2. Decide which one you are playing before you start.'},
  {id:'seveneight', n:'Seven (2+2+3)', bpm:160, sig:'7/8', cat:'odd', beats:7,
   k:[1,0,1,0,1,0,0], s:[0,0,0,0,1,0,0], h:[1,1,1,1,1,1,1],
   read:'Two, two, three. The bar ends one eighth note later than your body expects.',
   ctx:'Common across the Balkans, in progressive rock, jazz fusion and contemporary composition whenever the pulse should feel uneven but still danceable.',
   trap:'Say a three-syllable word on the last group. Language carries odd meter better than numbers do.'},
  {id:'sixeight', n:'Six-Eight Lilt', bpm:120, sig:'6/8', cat:'classical', beats:6,
   k:[1,0,0,0,0,0,1,0,0,0,0,0], s:[0,0,0,1,0,0,0,0,0,1,0,0], h:[1,0,1,1,0,1,1,0,1,1,0,1],
   read:'Six eighth notes counted in two groups of three.',
   ctx:'Jigs, marches and ballads use it naturally. Compound meter swings without needing a separate swing feel.',
   trap:'It is felt in two, not six. Counting all six turns a lilting dance into a slow crawl.'},
  {id:'trap', n:'Trap', bpm:70, sig:'4/4', cat:'hiphop', beats:4,
   k:[1,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0],
   s:[0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0],
   h:[1,0,1,1,1,1,1,0,1,0,1,1,1,1,1,1],
   read:'Half-time snare with rapid, subdividing hi-hats over a sparse 808 pattern.',
   ctx:'The hats do the rhythmic work while the snare marks half-time, which is why the tempo feels ambiguous: slow and fast at once.',
   trap:'The written tempo is misleading. Trap at 70 BPM and 140 BPM are often the same groove notated differently.'},
  {id:'dnb', n:'Drum & Bass', bpm:174, sig:'4/4', cat:'electronic', beats:4,
   k:[1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0],
   s:[0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0],
   h:[1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0],
   read:'A fast two-step skeleton at around 174 BPM with a half-time feel on top.',
   ctx:'Descended from chopped funk breaks. The bass moves at half the speed of the drums, which is what makes it feel heavy rather than frantic.',
   trap:'The snare on 2 and 4 of a half-time feel is what stops it sounding like a runaway train.'}
);

/* ------------------------------------------------------------
   3 · PLAYABLE PHRASES
   ------------------------------------------------------------ */
OT.MOTIFS=[
/* ---- original études, one per device ---- */
{id:'e-lydian', kind:'etude', n:'Lydian Lift', dev:'Raised 4th over a static bass',
 scale:'lydian', root:0, bpm:143, inst:'string_ensemble_1',
 mel:[[0,1],[4,1],[6,2],[4,1],[7,1],[11,2],[9,1],[7,1],[6,2],[4,1],[2,1],[0,4]],
 bass:[[0,4],[0,4],[0,4],[0,4]],
 note:'The bass never moves. Every bit of colour comes from the ♯4 leaning against it. That is the whole Lydian effect in one phrase.'},
{id:'e-mixo', kind:'etude', n:'Mixolydian Road', dev:'♭VII resolving up to I',
 scale:'mixolydian', root:2, bpm:176, inst:'overdriven_guitar',
 mel:[[0,1],[2,1],[4,1],[7,1],[10,2],[7,1],[4,1],[2,2],[0,2],[10,-1],[0,4]],
 bass:[[0,2],[10,2],[0,2],[10,2],[0,4]],
 note:'The chord a whole step below the root replaces the dominant. Nothing pulls hard, so the phrase sounds like travelling rather than arriving.'},
{id:'e-dorian', kind:'etude', n:'Dorian Walk', dev:'Minor with a bright 6th',
 scale:'dorian', root:2, bpm:188, inst:'electric_piano_1',
 mel:[[0,1],[3,1],[5,1],[7,1],[9,2],[7,1],[5,1],[3,1],[2,1],[0,2],[9,1],[7,1],[0,4]],
 bass:[[0,4],[0,4],[5,4],[0,4]],
 note:'Listen for the 6th. Flatten that one note and this becomes ordinary minor. It is doing all the work of keeping the phrase hopeful.'},
{id:'e-phryg', kind:'etude', n:'Phrygian Descent', dev:'♭2 falling onto the root',
 scale:'phrygian', root:4, bpm:158, inst:'acoustic_guitar_nylon',
 mel:[[12,1],[10,1],[8,1],[7,2],[5,1],[3,1],[1,2],[0,4],[1,1],[0,3]],
 bass:[[0,4],[0,4],[0,4],[0,4]],
 note:'The half-step above the root, falling onto it, over and over. That single interval is the entire Spanish and metal association.'},
{id:'e-harm', kind:'etude', n:'The Augmented Second', dev:'Harmonic minor ♭6 to 7',
 scale:'harmonic', root:9, bpm:150, inst:'church_organ',
 mel:[[0,1],[2,1],[3,1],[5,1],[7,1],[8,2],[11,2],[12,2],[11,1],[8,1],[7,2],[0,4]],
 bass:[[0,4],[5,2],[7,2],[0,4]],
 note:'The leap from ♭6 up to the raised 7th is a step and a half. That gap is what every gothic and every desert cue is built from.'},
{id:'e-aeolian', kind:'etude', n:'Falling Bass Lament', dev:'Stepwise descent under a static melody',
 scale:'aeolian', root:9, bpm:220, inst:'cello',
 mel:[[12,2],[12,1],[10,1],[12,4],[11,2],[10,2],[9,4],[7,2],[9,2],[12,4]],
 bass:[[0,2],[10,2],[8,2],[7,2],[0,2],[10,2],[8,2],[7,2]],
 note:'The tune stays roughly put while the bass sinks by step. Purcell used this for grief and so does every fallen-kingdom theme since.'},
{id:'e-wholetone', kind:'etude', n:'No Ground to Stand On', dev:'Whole tone symmetry',
 scale:'wholetone', root:0, bpm:136, inst:'celesta',
 mel:[[0,1],[2,1],[4,1],[6,1],[8,1],[10,1],[12,2],[10,1],[8,1],[6,1],[4,1],[2,1],[0,2]],
 bass:[[0,4],[6,4],[0,4],[6,4]],
 note:'Every step is identical, so no note can claim to be home. That is why it reads as dreams, vertigo and things that should not exist.'},
{id:'e-octatonic', kind:'etude', n:'Machine Tension', dev:'Octatonic cells',
 scale:'octatonic', root:4, bpm:130, inst:'overdriven_guitar',
 mel:[[0,.5],[1,.5],[3,.5],[4,.5],[0,.5],[1,.5],[3,.5],[4,.5],[6,.5],[7,.5],[9,.5],[10,.5],[6,1],[0,2]],
 bass:[[0,1],[0,1],[0,1],[0,1],[6,1],[6,1],[0,2]],
 note:'Short cells repeated rather than a melody developed. Symmetry plus repetition is how you make music sound mechanical and enormous.'},
{id:'e-minpent', kind:'etude', n:'Five Notes, All Attitude', dev:'Minor pentatonic riff',
 scale:'minpent', root:9, bpm:150, inst:'overdriven_guitar',
 mel:[[0,.5],[3,.5],[5,1],[3,.5],[0,.5],[10,1],[0,.5],[3,.5],[5,.5],[7,.5],[5,1],[3,1],[0,2]],
 bass:[[0,2],[0,2],[5,2],[0,2]],
 note:'Rhythm is carrying this, not the notes. Five pitches is all a lead needs when the placement is right, which is why chip composers loved it.'},
{id:'e-majpent', kind:'etude', n:'Nothing Can Clash', dev:'Major pentatonic',
 scale:'majpent', root:0, bpm:176, inst:'marimba',
 mel:[[0,1],[2,1],[4,1],[7,1],[9,2],[7,1],[4,1],[9,1],[12,1],[9,1],[7,1],[4,2],[0,2]],
 bass:[[0,2],[7,2],[0,2],[7,2]],
 note:'The two half-steps have been removed, so no combination can sound wrong. Cultures all over the world arrived at this independently.'},
{id:'e-blues', kind:'etude', n:'Through the Blue Note', dev:'♭5 as a passing tone',
 scale:'blues', root:5, bpm:100, inst:'electric_piano_1',
 mel:[[0,.5],[3,.5],[5,.5],[6,.5],[7,1],[5,.5],[3,.5],[0,1],[10,.5],[7,.5],[6,.5],[5,.5],[3,1],[0,2]],
 bass:[[0,1],[0,1],[5,1],[0,1],[7,1],[5,1],[0,2]],
 note:'The ♭5 never lands. It is passed through on the way somewhere, which is exactly how a bent note behaves on a guitar or a voice.'},
{id:'e-royalroad', kind:'etude', n:'The Royal Road', dev:'IV–V–iii–vi',
 scale:'ionian', root:0, bpm:143, inst:'acoustic_grand_piano', prog:'royalroad',
 mel:[[9,1],[7,1],[5,2],[7,1],[9,1],[11,2],[7,1],[4,1],[2,2],[9,1],[7,1],[9,4]],
 bass:[[5,2],[7,2],[4,2],[9,2],[5,2],[7,2],[4,2],[9,2]],
 note:'It begins on IV, so the phrase is already moving before you notice it started, and it lands on vi instead of home. Postponed arrival is the feeling.'},
{id:'e-251', kind:'etude', n:'The Cadence', dev:'ii–V–I with voice leading',
 scale:'ionian', root:0, bpm:150, inst:'acoustic_grand_piano', prog:'251',
 mel:[[2,1],[5,1],[9,1],[12,1],[11,2],[7,1],[5,1],[4,4]],
 bass:[[2,2],[7,2],[0,4]],
 note:'Every voice moves as little as possible. The tritone inside the V7 spreads outward into the I chord and the whole thing feels like gravity.'},
{id:'e-arp', kind:'etude', n:'Harmony Played Sideways', dev:'Arpeggio as melody',
 scale:'ionian', root:0, bpm:120, inst:'harpsichord',
 mel:[[0,.5],[4,.5],[7,.5],[12,.5],[16,.5],[12,.5],[7,.5],[4,.5],
      [-3,.5],[2,.5],[5,.5],[9,.5],[14,.5],[9,.5],[5,.5],[2,.5],[0,2]],
 bass:[[0,4],[-3,4],[0,2]],
 note:'There is no tune here at all, only chord tones in sequence. The same device appears throughout classical preludes, harp writing and modern ambient arranging.'},
{id:'e-sus', kind:'etude', n:'Refusing to Decide', dev:'Suspended chords over a pedal',
 scale:'ionian', root:7, bpm:207, inst:'string_ensemble_1',
 mel:[[2,2],[7,2],[9,4],[7,2],[5,2],[2,4],[0,2],[2,2],[7,4]],
 bass:[[0,4],[0,4],[0,4],[0,4]],
 note:'No thirds anywhere, so nothing commits to major or minor. Held bass underneath turns that indecision into weather rather than a problem.'},
{id:'e-hijaz', kind:'etude', n:'Hijaz Turn', dev:'♭2 above a major 3rd',
 scale:'hijaz', root:4, bpm:167, inst:'acoustic_guitar_nylon',
 mel:[[0,.5],[1,.5],[4,1],[5,.5],[4,.5],[1,1],[0,2],[7,1],[8,1],[7,1],[5,1],[4,2],[1,1],[0,3]],
 bass:[[0,4],[0,4],[0,4],[0,4]],
 note:'A bright major third with a half-step crowded above the root. That contradiction is the sound of flamenco, klezmer and every desert level.'},
{id:'e-insen', kind:'etude', n:'Koto Air', dev:'Japanese pentatonic',
 scale:'insen', root:2, bpm:111, inst:'koto',
 mel:[[0,2],[1,1],[5,1],[7,2],[5,1],[1,1],[0,4],[7,1],[10,1],[12,2],[10,1],[7,1],[5,2],[0,4]],
 bass:[[0,4],[0,4],[7,4],[0,4]],
 note:'Long notes and generous silence. In this tradition the space between notes is material, not absence. Try humming it with the gaps intact.'},
{id:'e-bhairav', kind:'etude', n:'Morning Rāga Sketch', dev:'Two augmented seconds',
 scale:'bhairav', root:2, bpm:107, inst:'pan_flute',
 mel:[[0,2],[1,1],[4,1],[5,2],[7,2],[8,1],[11,1],[12,4],[11,1],[8,1],[7,2],[5,1],[4,1],[1,1],[0,4]],
 bass:[[0,8],[0,8]],
 note:'A single held drone underneath, which is how this music actually works. No chord changes, so wide intervals stay stable.'},
{id:'e-romanian', kind:'etude', n:'Klezmer Turn', dev:'Dorian with a raised 4th',
 scale:'romanian', root:2, bpm:214, inst:'alto_sax',
 mel:[[0,.5],[2,.5],[3,1],[6,.5],[7,.5],[6,1],[3,.5],[2,.5],[0,2],[9,1],[10,1],[9,.5],[7,.5],[6,1],[3,1],[0,2]],
 bass:[[0,2],[0,2],[7,2],[0,2]],
 note:'A tritone against a minor third. Lydian has the sharp fourth too, but the flat third here puts it somewhere completely different.'},

/* ---- traditional and public-domain melodies, played in full ---- */
{id:'t-sakura', kind:'trad', n:'Sakura Sakura', origin:'Japan · traditional, Edo period',
 dev:'In Sen pentatonic', scale:'insen', root:9, bpm:120, inst:'koto',
 mel:[[0,1],[0,1],[1,2],[0,1],[0,1],[1,2],[0,1],[1,1],[5,1],[3,1],[1,2],[0,2],
      [5,1],[5,1],[7,1],[7,1],[5,1],[5,1],[3,2],[1,1],[3,1],[1,1],[0,1],[1,4]],
 bass:[[0,4],[0,4],[0,4],[0,4],[0,4],[0,4]],
 note:'A folk song about cherry blossom, and the clearest example of the Japanese pentatonic there is. The half-step above the root gives it the ache.'},
{id:'t-greensleeves', kind:'trad', n:'Greensleeves', origin:'England · 16th century',
 dev:'Dorian and Aeolian alternating', scale:'dorian', root:9, bpm:143, inst:'orchestral_harp',
 mel:[[0,1],[3,2],[5,1],[7,1.5],[8,.5],[7,1],[5,2],[2,1],[-1,1.5],[0,.5],[2,1],[3,2],[0,1],
      [0,1.5],[-1,.5],[0,1],[2,2],[-1,1],[-4,3]],
 bass:[[0,3],[5,3],[0,3],[7,3],[0,3],[5,3],[0,3],[7,3]],
 note:'The sixth degree keeps switching between raised and lowered. That flicker between Dorian and natural minor is why it sounds both old and unsettled.'},
{id:'t-odejoy', kind:'trad', n:'Ode to Joy', origin:'Beethoven · 1824 · public domain',
 dev:'Stepwise major melody', scale:'ionian', root:0, bpm:143, inst:'string_ensemble_1',
 mel:[[4,1],[4,1],[5,1],[7,1],[7,1],[5,1],[4,1],[2,1],[0,1],[0,1],[2,1],[4,1],[4,1.5],[2,.5],[2,2],
      [4,1],[4,1],[5,1],[7,1],[7,1],[5,1],[4,1],[2,1],[0,1],[0,1],[2,1],[4,1],[2,1.5],[0,.5],[0,2]],
 bass:[[0,2],[0,2],[5,2],[0,2],[0,2],[7,2],[0,4],
       [0,2],[0,2],[5,2],[0,2],[0,2],[7,2],[0,4]],
 note:'Almost the entire tune moves by step, and it stays inside a fifth for most of its length. Singable by design. That was the point.'},
{id:'t-amazing', kind:'trad', n:'Amazing Grace', origin:'England / USA · 1779 · traditional',
 dev:'Major pentatonic', scale:'majpent', root:0, bpm:120, inst:'acoustic_guitar_steel',
 mel:[[-5,1],[0,2],[4,.5],[0,.5],[4,2],[2,1],[0,2],[-3,1],[-5,3],
      [-5,1],[0,2],[4,.5],[0,.5],[4,2],[2,1],[7,3],[7,1],[7,3]],
 bass:[[0,3],[0,3],[5,3],[0,3],[0,3],[7,3],[0,3],[0,3]],
 note:'Five notes, no half-steps, and it has survived in every tradition it touched. Pentatonic melodies travel across cultures more easily than any other kind.'},
{id:'t-frere', kind:'trad', n:'Frère Jacques', origin:'France · traditional',
 dev:'Round: the same tune against itself', scale:'ionian', root:0, bpm:167, inst:'music_box',
 mel:[[0,1],[2,1],[4,1],[0,1],[0,1],[2,1],[4,1],[0,1],
      [4,1],[5,1],[7,2],[4,1],[5,1],[7,2],
      [7,.5],[9,.5],[7,.5],[5,.5],[4,1],[0,1],[7,.5],[9,.5],[7,.5],[5,.5],[4,1],[0,1],
      [0,1],[-5,1],[0,2],[0,1],[-5,1],[0,2]],
 bass:[[0,4],[0,4],[0,4],[0,4],[0,4],[0,4],[0,4],[0,4]],
 note:'Written so it harmonises with a delayed copy of itself. Every bar works against every other bar. That is what makes a round possible.'},
{id:'t-scarborough', kind:'trad', n:'Scarborough Fair', origin:'England · traditional ballad',
 dev:'Dorian mode', scale:'dorian', root:2, bpm:220, inst:'pan_flute',
 mel:[[-5,1],[-5,1],[-5,2],[2,2],[-1,1],[0,1],[2,3],[-5,1],[-1,2],
      [-3,1],[-5,1],[-8,2],[-5,3],[-5,3]],
 bass:[[0,3],[0,3],[5,3],[0,3],[10,3],[0,3]],
 note:'A minor-flavoured tune that keeps landing on a raised sixth. Dorian is why it sounds ancient rather than merely sad.'},
{id:'t-canon', kind:'trad', n:'Pachelbel\u2019s Canon (bass)', origin:'Germany · c.1680 · public domain',
 dev:'Descending ground bass', scale:'ionian', root:2, bpm:220, inst:'cello', prog:'canon',
 mel:[[0,2],[-3,2],[-4,2],[-7,2],[-5,2],[-9,2],[-5,2],[-7,2]],
 bass:[[0,2],[-3,2],[-4,2],[-7,2],[-5,2],[-9,2],[-5,2],[-7,2]],
 note:'Eight notes that loop forever. Three hundred years of pop music has been built on this exact descending pattern.'},
{id:'t-hava', kind:'trad', n:'Hava Nagila', origin:'Jewish · traditional Hasidic melody',
 dev:'Phrygian dominant / Hijaz', scale:'phrygdom', root:4, bpm:200, inst:'alto_sax',
 mel:[[0,1],[1,1],[4,2],[1,1],[4,1],[5,2],[4,1],[1,1],[0,2],
      [0,1],[1,1],[4,1],[5,1],[7,2],[5,1],[4,1],[1,1],[0,3]],
 bass:[[0,2],[0,2],[5,2],[0,2],[0,2],[7,2],[0,4]],
 note:'The half-step above the root sitting under a major third. Same interval pattern as flamenco: two traditions arriving at one sound.'},
{id:'t-house', kind:'trad', n:'House of the Rising Sun', origin:'USA · traditional folk',
 dev:'Minor with a major IV', scale:'aeolian', root:9, bpm:125, inst:'acoustic_guitar_nylon',
 mel:[[0,1],[4,1],[7,1],[9,2],[7,1],[4,2],[0,2],[7,1],[9,1],[12,2],[9,1],[7,1],[4,2],[0,4]],
 bass:[[0,3],[4,3],[7,3],[9,3],[0,3],[4,3],[7,3],[0,3]],
 note:'A minor key with a major chord on the fourth degree, borrowed from Dorian. That one bright chord in the middle is the whole character.'}
];

/* ------------------------------------------------------------
   4 · THE REGIONAL GUIDE
   ------------------------------------------------------------ */
OT.WORLD=[
  {id:'westafrica', region:'West Africa', cont:'Africa',
   blurb:'Rhythm organised around a repeating bell pattern, with every drum playing a part that interlocks rather than a part that stands alone. Almost all popular music in the Americas descends from this.',
   idea:'Polyrhythm as the default. Two or three groupings run at once and the listener chooses where to feel the pulse.',
   scales:['majpent','minpent'], rhythms:['bembe','afrobeat'], motifs:['e-majpent'],
   inst:'Djembe, dundun, kora, balafon, agogô bell'},
  {id:'northafrica', region:'North Africa & the Middle East', cont:'Africa · Asia',
   blurb:'Melody organised into maqamat: modes carrying required phrases, ornaments and emotional associations rather than just a set of notes.',
   idea:'Microtones. Many maqamat use intervals that fall between the keys of a piano, so any keyboard version is an approximation.',
   scales:['hijaz','phrygdom'], rhythms:['bulerias'], motifs:['e-hijaz','t-hava'],
   inst:'Oud, ney, qanun, darbuka, riq'},
  {id:'india', region:'India', cont:'Asia',
   blurb:'Rāga for melody and tāl for rhythm, performed over a constant drone with extensive improvisation inside strict rules.',
   idea:'No chord changes at all. Harmony as the West understands it is absent, and the drone is what makes complex melody legible.',
   scales:['bhairav'], rhythms:['teental'], motifs:['e-bhairav'],
   inst:'Sitar, sarod, bansuri, tabla, tanpura'},
  {id:'japan', region:'Japan', cont:'Asia',
   blurb:'Pentatonic melody with a strong emphasis on space, attack and decay; the shape of each individual note matters as much as the sequence.',
   idea:'Ma: the interval of silence. Space is treated as material rather than as the absence of material.',
   scales:['insen','majpent-jp'], rhythms:['taiko'], motifs:['e-insen','t-sakura'],
   inst:'Koto, shamisen, shakuhachi, taiko'},
  {id:'indonesia', region:'Java & Bali', cont:'Asia',
   blurb:'Gamelan orchestras of tuned metallophones and gongs, playing cyclic structures where the largest gong marks the largest unit of time.',
   idea:'The ensemble is tuned as a single instrument, and no two gamelans match. Tuning is a property of the orchestra, not of music in general.',
   scales:['pelog'], rhythms:['bembe'], motifs:[],
   inst:'Saron, bonang, gendèr, kendang, gong ageng'},
  {id:'balkans', region:'The Balkans & Turkey', cont:'Europe',
   blurb:'Dance music in additive meters (sevens, nines and elevens built from groups of two and three) with modal melody above.',
   idea:'Odd meters as the norm rather than the experiment. Children dance them before they can count them.',
   scales:['romanian','phrygdom'], rhythms:['karsilama','rachenitsa'], motifs:['e-romanian'],
   inst:'Kaval, gaida, tapan, accordion, clarinet'},
  {id:'iberia', region:'Andalusia', cont:'Europe',
   blurb:'Flamenco: a twelve-count cycle, Phrygian-flavoured harmony, and guitar technique built around percussive attack.',
   idea:'Compás. The rhythmic cycle is clapped by everyone present, and knowing it is what separates participation from spectating.',
   scales:['phrygdom','phrygian'], rhythms:['bulerias'], motifs:['e-phryg','e-hijaz'],
   inst:'Flamenco guitar, cajón, palmas, voice'},
  {id:'britain', region:'Britain & Ireland', cont:'Europe',
   blurb:'Modal folk melody (Dorian and Mixolydian far more than major) carried by voice, fiddle and pipes in jigs and reels.',
   idea:'Modes survived here after Western art music narrowed to major and minor, which is why the tunes sound older than they are.',
   scales:['dorian','mixolydian'], rhythms:['sixeight'], motifs:['t-greensleeves','t-scarborough'],
   inst:'Fiddle, uilleann pipes, bodhrán, tin whistle, concertina'},
  {id:'cuba', region:'Cuba & the Caribbean', cont:'Americas',
   blurb:'West African rhythm meeting Spanish harmony and song form. Everything aligns to clave.',
   idea:'Clave is a key, not a pattern to play. It is a rule the whole arrangement obeys whether or not anyone strikes it.',
   scales:['ionian','mixolydian'], rhythms:['son-clave','rumba-clave','tresillo','reggae'], motifs:[],
   inst:'Congas, timbales, tres, bongó, claves'},
  {id:'brazil', region:'Brazil', cont:'Americas',
   blurb:'Samba and bossa nova: continuous sixteenth-note motion, weight on the second beat, and jazz-derived harmony played very quietly.',
   idea:'Bossa nova put dense extended chords under a whisper. The sophistication is in the harmony, never in the volume.',
   scales:['ionian','melodic'], rhythms:['samba','bossa'], motifs:['e-251'],
   inst:'Nylon guitar, surdo, pandeiro, cuíca, agogô'},
  {id:'usa', region:'The United States', cont:'Americas',
   blurb:'Blues, jazz, gospel and everything downstream: African rhythmic practice meeting European harmony under specific historical conditions.',
   idea:'The blue note. A pitch that lives between the keys, which is why the blues can never be fully written down.',
   scales:['blues','blues-maj','minpent'], rhythms:['shuffle','secondline','jazzswing','boom','trap'],
   motifs:['e-blues','t-amazing','t-house'],
   inst:'Guitar, piano, drum kit, saxophone, voice'},
  {id:'europe-art', region:'European Art Music', cont:'Europe',
   blurb:'The written tradition: functional harmony, counterpoint, and large forms built to be performed by people who have never met the composer.',
   idea:'Notation as the carrier. Music that can be transmitted precisely across centuries behaves differently from music transmitted by ear.',
   scales:['ionian','aeolian','harmonic','melodic'], rhythms:['waltz','sixeight'],
   motifs:['t-odejoy','t-canon','e-harm'],
   inst:'Orchestra, organ, piano, string quartet'}
];

/* ------------------------------------------------------------
   5 · METERS for the ear-training drill
   ------------------------------------------------------------ */
OT.METERS=[
  {n:'2/4',   beats:2, group:[2],       hint:'March. Two beats, strong–weak.'},
  {n:'3/4',   beats:3, group:[3],       hint:'Waltz. It rotates.'},
  {n:'4/4',   beats:4, group:[4],       hint:'The default. Four square beats.'},
  {n:'5/4',   beats:5, group:[3,2],     hint:'Three then two. One beat too many.'},
  {n:'6/8',   beats:6, group:[3,3],     hint:'Counted in two, felt in six. Lilting.'},
  {n:'7/8',   beats:7, group:[2,2,3],   hint:'Short, short, long. Ends early.'},
  {n:'9/8',   beats:9, group:[2,2,2,3], hint:'Three even steps and a limp.'},
  {n:'12/8',  beats:12,group:[3,3,3,3], hint:'Four groups of three. Blues shuffle.'}
];
