-- ─────────────────────────────────────────────────────────────────────────
-- Commerce schema — generated by Backplane
-- Orders, download entitlements, licenses, webhook idempotency, email log,
-- an event timeline for Backplane's unified log, and a probe table used only
-- by synthetic health tests.
--
-- Security model: row level security is ON for every table. Customers who
-- sign in (Supabase Auth) can read only their own orders, downloads and
-- licenses. Nothing is writable from the browser: all writes come from the
-- Worker with the server key. Re-running this file is safe.
-- ─────────────────────────────────────────────────────────────────────────

create extension if not exists pgcrypto;

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  stripe_session_id text not null unique,
  stripe_payment_intent text,
  email text not null,
  customer_name text,
  product text not null,
  amount_total bigint not null default 0,
  currency text not null default 'usd',
  status text not null default 'paid' check (status in ('paid', 'refunded', 'disputed', 'canceled')),
  user_id uuid references auth.users (id) on delete set null,
  is_probe boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
-- Physical goods (E-commerce preset): where and to whom the order ships.
alter table public.orders add column if not exists shipping_name text;
alter table public.orders add column if not exists shipping_address jsonb;
alter table public.orders add column if not exists phone text;
alter table public.orders add column if not exists fulfillment_status text not null default 'unfulfilled';
create index if not exists orders_email_idx on public.orders (lower(email));
create index if not exists orders_payment_intent_idx on public.orders (stripe_payment_intent);

create table if not exists public.downloads (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders (id) on delete cascade,
  stripe_session_id text not null,
  object_key text not null,
  download_count integer not null default 0,
  max_downloads integer not null default 10,
  last_downloaded_at timestamptz,
  expires_at timestamptz not null,
  revoked boolean not null default false,
  created_at timestamptz not null default now(),
  unique (stripe_session_id, object_key)
);
create index if not exists downloads_order_idx on public.downloads (order_id);

create table if not exists public.licenses (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders (id) on delete cascade,
  key_hash text not null unique,
  key_hint text not null,
  product text not null,
  revoked boolean not null default false,
  is_probe boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists licenses_order_idx on public.licenses (order_id);

create table if not exists public.webhook_events (
  event_id text primary key,
  type text not null,
  livemode boolean not null default false,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  outcome text
);

create table if not exists public.email_log (
  id uuid primary key default gen_random_uuid(),
  resend_email_id text unique,
  stripe_session_id text,
  recipient text not null,
  kind text not null,
  status text not null default 'sent',
  last_event_at timestamptz default now(),
  created_at timestamptz not null default now()
);
create index if not exists email_log_session_idx on public.email_log (stripe_session_id, kind);

create table if not exists public.bp_events (
  id bigint generated always as identity primary key,
  at timestamptz not null default now(),
  source text not null,
  kind text not null,
  message text not null,
  ref text,
  is_probe boolean not null default false
);
create index if not exists bp_events_at_idx on public.bp_events (at desc);

create table if not exists public.backplane_probe (
  id text primary key,
  note text,
  created_at timestamptz not null default now()
);

-- Row level security on every table.
alter table public.orders enable row level security;
alter table public.downloads enable row level security;
alter table public.licenses enable row level security;
alter table public.webhook_events enable row level security;
alter table public.email_log enable row level security;
alter table public.bp_events enable row level security;
alter table public.backplane_probe enable row level security;

-- Signed-in customers may read their own purchases (by account or by the
-- verified email on their account). No insert/update/delete policies exist,
-- so only the server key can write.
drop policy if exists "orders: customers read their own" on public.orders;
create policy "orders: customers read their own" on public.orders
  for select to authenticated
  using (user_id = (select auth.uid()) or lower(email) = lower((select auth.jwt() ->> 'email')));

drop policy if exists "downloads: customers read their own" on public.downloads;
create policy "downloads: customers read their own" on public.downloads
  for select to authenticated
  using (exists (
    select 1 from public.orders o
    where o.id = downloads.order_id
      and (o.user_id = (select auth.uid()) or lower(o.email) = lower((select auth.jwt() ->> 'email')))
  ));

drop policy if exists "licenses: customers read their own" on public.licenses;
create policy "licenses: customers read their own" on public.licenses
  for select to authenticated
  using (exists (
    select 1 from public.orders o
    where o.id = licenses.order_id
      and (o.user_id = (select auth.uid()) or lower(o.email) = lower((select auth.jwt() ->> 'email')))
  ));

-- Download counter used by the Worker (server key only).
create or replace function public.bp_record_download(p_session text, p_key text)
returns void
language sql
security definer
set search_path = public
as $$
  update public.downloads
     set download_count = download_count + 1, last_downloaded_at = now()
   where stripe_session_id = p_session and object_key = p_key;
$$;
revoke all on function public.bp_record_download(text, text) from public, anon, authenticated;
grant execute on function public.bp_record_download(text, text) to service_role;

-- Keep updated_at honest.
create or replace function public.bp_touch_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;
drop trigger if exists orders_touch_updated_at on public.orders;
create trigger orders_touch_updated_at before update on public.orders
  for each row execute function public.bp_touch_updated_at();
