"use client";
import {useEffect,useState} from "react";
import {Sheet,SheetContent,SheetTitle,SheetDescription} from "@/components/ui/sheet";
import {Plus,Bookmark,BookmarkCheck,ExternalLink,MapPin,Tent,LoaderCircle,Wind,Navigation} from "lucide-react";
import type {Place,Trip,Route,Weather,Alert} from "@/lib/trippr/types";
import {CATEGORY_LABELS} from "@/lib/trippr/data";
import {REFERENCE_PLACES} from "@/lib/trippr/data";
import {providers,api,weatherDescription,ageLabel} from "@/lib/trippr/adapters";
import {distanceToRoute,milesBetween,safeUrl} from "@/lib/trippr/geo";
import {PlaceIcon,WeatherIcon} from "./icons";
const campAmenities=["Classification","Tents","RV / caravan","Restrooms","Drinking water","Showers","Electricity","Dump station","Reservations","Elevation"];
export function WeatherDisplay({weather,date}:{weather:Weather;date?:string}){const day=date?weather.days.find(d=>d.date===date):undefined;return <><div className="weather-current"><WeatherIcon code={day?.code??weather.code}/><div><strong>{Math.round(day?.high??weather.temperature)}°<span style={{display:"inline",fontSize:18}}>F</span></strong><span>{weatherDescription(day?.code??weather.code)}{day?` · forecast for ${new Date(date+"T12:00:00").toLocaleDateString("en-US",{month:"short",day:"numeric"})}`:" · modeled current conditions"}</span><small>{day?`Low ${Math.round(day.low)}° · ${day.precipitation}% rain chance`:`Wind ${Math.round(weather.wind)} mph`}</small></div></div>{date&&!day&&<p className="data-note">No forecast is available for {date}. Current conditions are shown separately.</p>}<div className="forecast-row">{weather.days.slice(0,5).map(d=><div className="forecast-day" key={d.date}><span>{new Date(d.date+"T12:00:00").toLocaleDateString("en-US",{weekday:"short"})}</span><WeatherIcon code={d.code}/><strong>{Math.round(d.high)}°</strong><small>{Math.round(d.low)}°</small></div>)}</div><p className="data-note">{weather.source} · {ageLabel(weather.updated)}</p></>;}
interface ParkLive{alerts:Alert[];campgrounds:Place[];visitorCenters:{name:string;description:string;url?:string}[];partial:boolean;updated:string;}
export default function PlaceDetails({place,onClose,trip,route,onAdd,onSave,onNote,onNearby,onRouteHere}:{place:Place|null;onClose():void;trip:Trip;route:Route|null;onAdd(p:Place,overnight?:boolean):void;onSave(p:Place):void;onNote(id:string,text:string):void;onNearby(p:Place,kind:"camp"|"fuel"):void;onRouteHere(p:Place):void;}){
 const[weather,setWeather]=useState<Weather|null>(null),[weatherError,setWeatherError]=useState(""),[air,setAir]=useState<{aqi:number;source:string;updated:string}|null>(null),[park,setPark]=useState<ParkLive|null>(null),[parkError,setParkError]=useState("");
 useEffect(()=>{setWeather(null);setWeatherError("");setAir(null);setPark(null);setParkError("");if(!place)return;const ac=new AbortController();providers.weather.get(place.coordinates,ac.signal).then(setWeather).catch(e=>{if(!ac.signal.aborted)setWeatherError(e.message);});api<{aqi:number;source:string;updated:string}>("air",{lat:place.coordinates[1].toFixed(3),lon:place.coordinates[0].toFixed(3)},ac.signal).then(setAir).catch(()=>{});if(place.parkCode)api<ParkLive>("park",{park:place.parkCode},ac.signal).then(setPark).catch(e=>{if(!ac.signal.aborted)setParkError(e.message);});return()=>ac.abort();},[place?.id]);
 const p=place;if(!p)return null;const parkCamps=[...new Map([...(park?.campgrounds||[]),...REFERENCE_PLACES.filter(c=>c.kind==="camp"&&c.parkCode===p.parkCode&&p.parkCode)].map(c=>[c.id,c])).values()];const isSaved=trip.savedPlaces.some(s=>s.id===p.id),distance=route?distanceToRoute(p.coordinates,route.coordinates):undefined,near=trip.stops.length?Math.min(...trip.stops.map(s=>milesBetween(s.coordinates,p.coordinates))):undefined,url=safeUrl(p.website),sourceUrl=safeUrl(p.sourceUrl),stop=trip.stops.find(s=>s.id===p.id),amenities={...p.amenities,Classification:p.tags?.operator_type||p.amenities?.Classification||null};
 return <Sheet open={!!place} modal={false} onOpenChange={v=>{if(!v)onClose();}}><SheetContent className="detail-sheet" onOpenAutoFocus={e=>e.preventDefault()}><SheetDescription className="sr-only">Details, weather, and trip actions for {p.name}.</SheetDescription><div className={`detail-hero ${!p.image?"detail-plain":""}`}>{p.image?<img src={p.image} alt={p.name} onError={e=>{e.currentTarget.style.display="none";}}/>:<PlaceIcon kind={p.kind}/>}<div className="hero-caption"><span>{CATEGORY_LABELS[p.kind]} · {p.region||"United States"}</span><SheetTitle asChild><h2>{p.name}</h2></SheetTitle></div>{p.imageCredit&&<span className="image-credit">{p.imageCredit}</span>}</div><div className="detail-scroll"><div className="detail-actions"><button className="primary-button" onClick={()=>onAdd(p,p.kind==="camp")} disabled={trip.stops.length>=20}>{p.kind==="camp"?<Tent/>:<Plus/>}{p.kind==="camp"?"Add overnight stop":"Add to trip"}</button><button className="icon-button" aria-label={isSaved?"Remove from saved places":"Save this place"} onClick={()=>onSave(p)}>{isSaved?<BookmarkCheck/>:<Bookmark/>}</button></div><div className="detail-kind"><MapPin size={13}/>{p.coordinates[1].toFixed(4)}°, {p.coordinates[0].toFixed(4)}°{distance!==undefined&&<span> · {distance.toFixed(1)} mi from route</span>}</div>{p.description&&<p className="detail-description">{p.description}</p>}{url&&<a className="official-link" href={url} target="_blank" rel="noopener noreferrer"><ExternalLink/>{p.kind==="camp"?"Booking / campground information":p.parkCode?"Official park website":"Website & information"}</a>}
 <div className="detail-section" style={{marginTop:19}}><h3>Weather for the stop</h3>{weather?<WeatherDisplay weather={weather} date={stop?.date}/>:weatherError?<p className="muted-copy">{weatherError}</p>:<p className="muted-copy"><LoaderCircle className="spin" size={14} style={{display:"inline"}}/> Checking the forecast…</p>}{air&&<div className="setting-row" style={{marginTop:13}}><span><Wind size={14} style={{display:"inline",marginRight:6}}/>Air quality <small>{air.source}</small></span><strong>AQI {Math.round(air.aqi)}</strong></div>}</div>
 {p.kind==="camp"&&<div className="detail-section"><h3>Camping, without the guessing</h3><div className="amenities">{campAmenities.map(key=>{const value=(amenities as Record<string,unknown>)[key];return <div className="amenity" key={key}><span>{key}</span><strong className={value===null||value===undefined?"unknown":""}>{value===true?"Yes":value===false?"No":typeof value==="string"?value:"Unknown"}</strong></div>;})}</div>{near!==undefined&&<p className="data-note">{near.toFixed(1)} straight-line miles from the nearest trip stop.</p>}<p className="data-note">Amenities are reported by the source. Campsite vacancy is not available here. Confirm access and reservations with the campground.</p></div>}
 {p.kind==="ev"&&<div className="detail-section"><h3>Charging details</h3><div className="amenities">{[["Network",p.tags?.network||p.tags?.operator||"Unknown"],["Connectors",p.tags?.connectors||Object.keys(p.tags||{}).filter(k=>k.startsWith("socket:")&&p.tags![k]!=="0"&&p.tags![k]!=="no").map(k=>k.replace("socket:","")).join(", ")||"Unknown"],["Access",p.tags?.access||p.tags?.opening_hours||"Unknown"]].map(([k,v])=><div className="amenity" key={k}><span>{k}</span><strong>{v}</strong></div>)}</div><p className="data-note">Live charger availability is not provided. Confirm connector compatibility and operation before relying on a stop.</p></div>}
 {p.kind==="fuel"&&<div className="detail-section"><h3>Fuel stop</h3><p className="muted-copy">{p.tags?.brand||p.tags?.operator||p.name}{p.tags?.opening_hours?` · ${p.tags.opening_hours}`:""}</p><p className="data-note">Live fuel prices are not available.</p></div>}
 {p.parkCode&&<><div className="detail-section"><h3>Official park notices</h3>{park?.alerts.map(a=><article className={`alert-item ${a.severity==="Severe"?"severe":""}`} key={a.id}><h3>{a.title}</h3><p>{a.description}</p>{safeUrl(a.url)&&<a className="official-link" href={safeUrl(a.url)} target="_blank" rel="noopener noreferrer">NPS notice <ExternalLink/></a>}</article>)}{park&&!park.alerts.length&&<p className="muted-copy">{park.partial?"Some park notices could not be checked.":"The connected NPS feed returned no current notices."}</p>}{parkError&&<p className="muted-copy">{parkError}</p>}{!park&&!parkError&&<p className="muted-copy">Checking the park source…</p>}<a className="official-link" href={`https://www.nps.gov/${p.parkCode}/planyourvisit/conditions.htm`} target="_blank" rel="noopener noreferrer">Check NPS conditions <ExternalLink/></a></div>{p.fees&&p.fees.length>0&&<div className="detail-section"><h3>Entrance information</h3>{p.fees.slice(0,3).map((f,i)=><div className="fee" key={i}><strong>{f.title}{Number(f.cost)>0?` · $${Number(f.cost).toFixed(0)}`:""}</strong><p style={{margin:"5px 0"}}>{f.description}</p></div>)}<p className="data-note">Reference information · verify current fees and entry arrangements with NPS.</p></div>}{p.operatingInfo&&<div className="detail-section"><h3>Planning your visit</h3><p className="muted-copy">{p.operatingInfo}</p><p className="data-note">Reference operating information, not a live open / closed status.</p></div>}{parkCamps.length>0&&<div className="detail-section"><h3>Park campgrounds</h3>{parkCamps.map(c=><button className="place-result" key={c.id} onClick={()=>onAdd(c,true)}><span className="result-icon"><Tent/></span><span><strong>{c.name}</strong><small>Add as overnight stop</small></span></button>)}</div>}{park?.visitorCenters&&park.visitorCenters.length>0&&<div className="detail-section"><h3>Visitor centers</h3>{park.visitorCenters.map(v=><div className="fee" key={v.name}><strong>{v.name}</strong><p>{v.description}</p></div>)}</div>}{p.activities&&<div className="detail-section"><h3>What’s here</h3><div className="activity-tags">{p.activities.slice(0,12).map(a=><span key={a}>{a}</span>)}</div></div>}</>}
 <div className="detail-section"><h3>Make a little room</h3><div className="dialog-actions"><button className="outline-button" onClick={()=>onNearby(p,"camp")}><Tent/>Nearby camping</button><button className="outline-button" onClick={()=>onNearby(p,"fuel")}><PlaceIcon kind="fuel"/>Nearby fuel</button><button className="outline-button" onClick={()=>onRouteHere(p)}><Navigation/>Route here</button></div></div><div className="detail-section"><label className="field-label">A note for this place<textarea placeholder="Remember this for later…" value={trip.placeNotes[p.id]||""} maxLength={5000} onChange={e=>onNote(p.id,e.target.value)}/></label></div><div className="detail-section"><p className="data-note">{p.source} · {ageLabel(p.updated)}{sourceUrl&&<> · <a href={sourceUrl} target="_blank" rel="noopener noreferrer">Source</a></>}</p></div></div></SheetContent></Sheet>;
}
