"use client";
import {forwardRef,useEffect,useImperativeHandle,useRef,useState} from "react";
import type * as Leaflet from "leaflet";
import type {Coordinate,Place} from "@/lib/trippr/types";
import {boundsOf} from "@/lib/trippr/geo";
import {weatherDescription,weatherTone} from "@/lib/trippr/adapters";
import type {MapHandle,MapProps} from "./TripprMap";
import {rasterTileUrl,rasterAttribution} from "@/lib/trippr/raster";

// A real, geographically projected tile map for browsers without WebGL2.
export default forwardRef<MapHandle,MapProps>(function RasterMap(props,ref){
 const host=useRef<HTMLDivElement>(null),map=useRef<Leaflet.Map|null>(null),lib=useRef<typeof Leaflet|null>(null),latest=useRef(props),tiles=useRef<Leaflet.TileLayer|null>(null);latest.current=props;
 const [ready,setReady]=useState(false),[zoom,setZoom]=useState(4),[error,setError]=useState("");const firstFit=useRef(false);
 const ll=(p:Coordinate):Leaflet.LatLngTuple=>[p[1],p[0]];
 const animated=()=>!window.matchMedia("(prefers-reduced-motion: reduce)").matches;
 function flyTo(p:Coordinate,z=10){map.current?.flyTo(ll(p),z,{animate:animated(),duration:.7});}
 function fit(points?:Coordinate[]){const m=map.current,line=points||latest.current.route?.coordinates||latest.current.stops.map(s=>s.coordinates);if(!m||!line.length)return;const b=boundsOf(line),mobile=innerWidth<761;m.fitBounds([[b[1],b[0]],[b[3],b[2]]],{paddingTopLeft:mobile?[48,145]:[latest.current.panelOpen?420:100,155],paddingBottomRight:mobile?[48,latest.current.panelOpen?Math.min(innerHeight*.57+78,innerHeight*.7):220]:[125,210],maxZoom:11,animate:animated()});}
 useImperativeHandle(ref,()=>({flyTo,fit,zoom(d){map.current?.setZoom((map.current?.getZoom()||4)+d,{animate:animated()});},north(){},terrain(){return false;},locate(){navigator.geolocation?.getCurrentPosition(p=>flyTo([p.coords.longitude,p.coords.latitude],11),()=>setError("Location access is unavailable. Search for your starting point."),{timeout:10000});},getMap:()=>null}),[]);
 useEffect(()=>{let disposed=false,m:Leaflet.Map|undefined;(async()=>{try{const L=await import("leaflet");if(disposed||!host.current)return;lib.current=L;m=L.map(host.current,{zoomControl:false,attributionControl:true,minZoom:2,maxZoom:18,preferCanvas:false}).setView([38.2,-108.5],4);map.current=m;m.attributionControl.setPrefix(false);L.control.scale({imperial:true,metric:false,position:"bottomleft"}).addTo(m);m.on("click",(e:Leaflet.LeafletMouseEvent)=>latest.current.onPoint([e.latlng.lng,e.latlng.lat]));let timer:ReturnType<typeof setTimeout>;const changed=()=>{clearTimeout(timer);timer=setTimeout(()=>{if(disposed||!m)return;const b=m.getBounds();setZoom(m.getZoom());latest.current.onViewport([b.getWest(),b.getSouth(),b.getEast(),b.getNorth()],m.getZoom());},350);};m.on("moveend",changed);m.on("zoomend",changed);changed();host.current.setAttribute("aria-label","Interactive road-trip map");setReady(true);latest.current.onReady();}catch{if(!disposed)setError("The map could not load. Reload to try again; your saved trip is still available.");}})();return()=>{disposed=true;m?.remove();map.current=null;};},[]);
 useEffect(()=>{const m=map.current,L=lib.current;if(!ready||!m||!L)return;tiles.current?.remove();const layer=L.tileLayer(rasterTileUrl(props.theme),{attribution:rasterAttribution(props.theme),maxZoom:18,crossOrigin:"anonymous",className:props.theme==="atlas"?"atlas-tiles":""});tiles.current=layer;layer.on("load",()=>setError(""));layer.addTo(m);return()=>{layer.remove();};},[ready,props.theme]);
 useEffect(()=>{const m=map.current,L=lib.current;if(!ready||!m||!L)return;const group=L.layerGroup().addTo(m),line=props.route?.coordinates||props.stops.map(s=>s.coordinates);if(line.length>1){const path=line.map(ll);L.polyline(path,{color:"#bbed75",weight:15,opacity:.12,interactive:false}).addTo(group);L.polyline(path,{color:"#12281b",weight:7,interactive:false}).addTo(group);L.polyline(path,{color:"#c4f17b",weight:3.7,dashArray:props.route?undefined:"7 7",interactive:false}).addTo(group);}props.stops.forEach((s,i)=>{const button=document.createElement("button");button.className=`stop-marker ${i===0?"first":i===props.stops.length-1?"last":""}`;button.textContent=String(i+1);button.setAttribute("aria-label",`Stop ${i+1}: ${s.name}`);L.DomEvent.disableClickPropagation(button);button.onclick=()=>latest.current.onPlace(s);L.marker(ll(s.coordinates),{icon:L.divIcon({html:button,className:"trippr-div-marker",iconSize:[34,34],iconAnchor:[17,17]}),keyboard:false,zIndexOffset:1000}).addTo(group);});if(!firstFit.current&&line.length>1){firstFit.current=true;fit();}return()=>{group.remove();};},[ready,props.route,props.stops]);
 useEffect(()=>{const m=map.current,L=lib.current;if(!ready||!m||!L)return;const group=L.layerGroup().addTo(m),clusters=new Map<string,Place[]>();for(const p of props.places){if(p.geometry)L.geoJSON({type:"Feature",properties:{},geometry:p.geometry} as GeoJSON.Feature,{style:{color:"#9fbf77",weight:1,opacity:.55,fillColor:"#a3cc76",fillOpacity:.08}}).on("click",()=>latest.current.onPlace(p)).addTo(group);const projected=m.project(ll(p.coordinates),zoom),key=zoom<9?`${Math.floor(projected.x/40)}:${Math.floor(projected.y/40)}`:p.id;clusters.set(key,[...(clusters.get(key)||[]),p]);}for(const values of clusters.values()){const p=values[0];if(values.length>1){const button=document.createElement("button");button.className="poi-cluster";button.textContent=String(values.length);button.setAttribute("aria-label",`Explore ${values.length} places`);L.DomEvent.disableClickPropagation(button);button.onclick=()=>fit(values.map(p=>p.coordinates));L.marker(ll(p.coordinates),{icon:L.divIcon({html:button,className:"trippr-div-marker",iconSize:[34,34],iconAnchor:[17,17]}),keyboard:false}).addTo(group);}else{const button=document.createElement("button");button.className="poi-dot";button.dataset.kind=p.kind;button.setAttribute("aria-label",p.name);button.title=p.name;L.DomEvent.disableClickPropagation(button);button.onclick=()=>latest.current.onPlace(p);const marker=L.marker(ll(p.coordinates),{icon:L.divIcon({html:button,className:"trippr-div-marker",iconSize:[18,18],iconAnchor:[9,9]}),keyboard:false}).addTo(group);const label=document.createElement("span");label.textContent=p.name;if(zoom>=8)marker.bindTooltip(label,{direction:"bottom",offset:[0,9],permanent:zoom>=10});}}return()=>{group.remove();};},[ready,zoom,props.places]);
 useEffect(()=>{const m=map.current,L=lib.current;if(!ready||!m||!L)return;const group=L.layerGroup().addTo(m);const marker=(p:Coordinate,label:string,text:string,tone:string,click:()=>void,offset=0)=>{const button=document.createElement("button");button.className="weather-marker";button.dataset.tone=tone;button.textContent=text;button.title=label;button.setAttribute("aria-label",label);L.DomEvent.disableClickPropagation(button);button.onclick=click;L.marker(ll(p),{icon:L.divIcon({html:button,className:"trippr-div-marker",iconSize:[54,32],iconAnchor:[27,16+offset]}),keyboard:false,zIndexOffset:1200}).addTo(group);};props.weatherPoints.forEach(p=>marker(p.coordinates,`${p.name}: ${weatherDescription(p.weather.code)} · modeled current weather`,`${Math.round(p.weather.temperature)}°`,weatherTone(p.weather.code,p.weather.temperature),()=>latest.current.onWeather(p.coordinates,p.name),38));props.hazards.forEach(h=>marker(h.coordinates,h.title,h.kind==="fire"?"Heat":h.kind==="river"?"River":"Road",h.kind==="fire"?"heat":"rain",()=>latest.current.onHazard(h)));props.alerts.filter(a=>a.geometry).forEach(a=>L.geoJSON({type:"Feature",properties:{},geometry:a.geometry!} as GeoJSON.Feature,{style:{color:"#e6af79",weight:1.3,dashArray:"5 4",fillColor:"#edb174",fillOpacity:.12}}).addTo(group));return()=>{group.remove();};},[ready,props.weatherPoints,props.hazards,props.alerts]);
 return <><div className="map-surface raster-map" ref={host}/><div className="map-shade"/>{!ready&&!error&&<div className="map-loading"><span>Unfolding the atlas…</span></div>}{error&&<div className="map-error glass" role="alert">{error}</div>}</>;
});
