"use client";
import {forwardRef,useEffect,useImperativeHandle,useRef,useState} from "react";
import {createPortal} from "react-dom";
import type * as Leaflet from "leaflet";
import type {Coordinate,Place} from "@/lib/trippr/types";
import {boundsOf} from "@/lib/trippr/geo";
import {signFamily} from "@/lib/trippr/data";
import {ROUTE_COLORS} from "@/lib/trippr/map-style";
import {type MapHandle,type MapProps,FAMILY_COLORS,stopMarker,hazardMarker,weatherChip} from "./TripprMap";
import {rasterTileUrl,rasterAttribution} from "@/lib/trippr/raster";

// A real, geographically projected tile map for browsers without WebGL2.
export default forwardRef<MapHandle,MapProps>(function RasterMap(props,ref){
 const host=useRef<HTMLDivElement>(null),map=useRef<Leaflet.Map|null>(null),lib=useRef<typeof Leaflet|null>(null),latest=useRef(props),tiles=useRef<Leaflet.TileLayer|null>(null);latest.current=props;
 const [ready,setReady]=useState(false),[zoom,setZoom]=useState(4),[error,setError]=useState("");const firstFit=useRef(false);
 const ll=(p:Coordinate):Leaflet.LatLngTuple=>[p[1],p[0]];
 const animated=()=>!window.matchMedia("(prefers-reduced-motion: reduce)").matches;
 const icon=(L:typeof Leaflet,el:HTMLElement,size:[number,number],anchor:[number,number])=>{L.DomEvent.disableClickPropagation(el);return L.divIcon({html:el,className:"trippr-div-marker",iconSize:size,iconAnchor:anchor});};
 function flyTo(p:Coordinate,z=10){const i=latest.current.insets;map.current?.flyTo(ll(p),z,{animate:animated(),duration:.7});map.current?.panBy([(i.right-i.left)/2,(i.bottom-i.top)/2],{animate:false});}
 function fit(points?:Coordinate[]){const m=map.current,line=points||latest.current.route?.coordinates||latest.current.stops.map(s=>s.coordinates);if(!m||!line.length)return;const b=boundsOf(line),i=latest.current.insets;m.fitBounds([[b[1],b[0]],[b[3],b[2]]],{paddingTopLeft:[i.left+40,i.top+30],paddingBottomRight:[i.right+40,i.bottom+40],maxZoom:11,animate:animated()});}
 useImperativeHandle(ref,()=>({flyTo,fit,reveal(p){const m=map.current;if(!m)return;const pt=m.latLngToContainerPoint(ll(p)),size=m.getSize(),i=latest.current.insets;if(pt.x<i.left+24||pt.x>size.x-i.right-24||pt.y<i.top+24||pt.y>size.y-i.bottom-24)m.panTo(ll(p),{animate:animated()});},zoom(d){map.current?.setZoom((map.current?.getZoom()||4)+d,{animate:animated()});},north(){},terrain(){return false;},getMap:()=>null}),[]);
 useEffect(()=>{let disposed=false,m:Leaflet.Map|undefined;(async()=>{try{const L=await import("leaflet");if(disposed||!host.current)return;lib.current=L;m=L.map(host.current,{zoomControl:false,attributionControl:true,minZoom:2,maxZoom:18,preferCanvas:false}).setView([38.6,-104],4);map.current=m;m.attributionControl.setPrefix(false);L.control.scale({imperial:true,metric:false,position:"bottomleft"}).addTo(m);let clickTimer:ReturnType<typeof setTimeout>|undefined;m.on("dblclick movestart",()=>clearTimeout(clickTimer));m.on("click",(e:Leaflet.LeafletMouseEvent)=>{clearTimeout(clickTimer);const at:Coordinate=[e.latlng.lng,e.latlng.lat];clickTimer=setTimeout(()=>latest.current.onPoint(at),280);});let timer:ReturnType<typeof setTimeout>;const changed=()=>{clearTimeout(timer);timer=setTimeout(()=>{if(disposed||!m)return;const b=m.getBounds();setZoom(m.getZoom());latest.current.onViewport([b.getWest(),b.getSouth(),b.getEast(),b.getNorth()],m.getZoom());},350);};m.on("moveend",changed);m.on("zoomend",changed);changed();host.current.setAttribute("aria-label","Interactive road-trip map");setReady(true);latest.current.onReady();}catch{if(!disposed)setError("The map couldn’t load. Reload to try again — your trip is still saved.");}})();return()=>{disposed=true;m?.remove();map.current=null;};},[]);
 useEffect(()=>{const m=map.current,L=lib.current;if(!ready||!m||!L)return;tiles.current?.remove();const layer=L.tileLayer(rasterTileUrl(props.theme),{attribution:rasterAttribution(props.theme),maxZoom:18,crossOrigin:"anonymous",className:props.theme==="atlas"?"atlas-tiles":props.theme==="light"?"paper-tiles":""});tiles.current=layer;layer.on("load",()=>setError(""));layer.addTo(m);return()=>{layer.remove();};},[ready,props.theme]);
 useEffect(()=>{const m=map.current,L=lib.current;if(!ready||!m||!L)return;const group=L.layerGroup().addTo(m),line=props.route?.coordinates||props.stops.map(s=>s.coordinates),c=ROUTE_COLORS[props.theme],day=props.theme==="light";if(line.length>1){const path=line.map(ll);L.polyline(path,{color:c.glow,weight:day?14:18,opacity:day?.6:.16,interactive:false}).addTo(group);L.polyline(path,{color:c.edge,weight:day?6:8,interactive:false}).addTo(group);L.polyline(path,{color:c.line,weight:day?2.6:4,dashArray:props.route?undefined:"7 7",interactive:false}).addTo(group);}props.stops.forEach((s,i)=>{L.marker(ll(s.coordinates),{icon:icon(L,stopMarker(s,i,props.stops.length,()=>latest.current.onPlace(s)),[30,40],[15,38]),keyboard:false,zIndexOffset:1000}).addTo(group);});if(!firstFit.current&&line.length>1){firstFit.current=true;fit();}return()=>{group.remove();};},[ready,props.route,props.stops,props.theme]);
 useEffect(()=>{const m=map.current,L=lib.current;if(!ready||!m||!L)return;const group=L.layerGroup().addTo(m),clusters=new Map<string,Place[]>();for(const p of props.places){if(p.geometry)L.geoJSON({type:"Feature",properties:{},geometry:p.geometry} as GeoJSON.Feature,{style:{color:"#b07a4f",weight:1,opacity:.6,fillColor:"#8a4a24",fillOpacity:.1}}).on("click",()=>latest.current.onPlace(p)).addTo(group);const projected=m.project(ll(p.coordinates),zoom),key=zoom<9?`${Math.floor(projected.x/40)}:${Math.floor(projected.y/40)}`:p.id;clusters.set(key,[...(clusters.get(key)||[]),p]);}for(const values of clusters.values()){const p=values[0];const button=document.createElement("button");button.type="button";if(values.length>1){button.className="poi-cluster";button.textContent=String(values.length);button.setAttribute("aria-label",`Zoom to ${values.length} places`);button.onclick=()=>fit(values.map(p=>p.coordinates));L.marker(ll(p.coordinates),{icon:icon(L,button,[32,32],[16,16]),keyboard:false}).addTo(group);}else{button.className="poi-dot";button.style.background=FAMILY_COLORS[signFamily(p.kind)];button.setAttribute("aria-label",p.name);button.title=p.name;button.onclick=()=>latest.current.onPlace(p);const marker=L.marker(ll(p.coordinates),{icon:icon(L,button,[16,16],[8,8]),keyboard:false}).addTo(group);if(zoom>=8){const label=document.createElement("span");label.textContent=p.name;marker.bindTooltip(label,{direction:"bottom",offset:[0,8],permanent:zoom>=10,className:"poi-label"});}}}return()=>{group.remove();};},[ready,zoom,props.places]);
 useEffect(()=>{const m=map.current,L=lib.current;if(!ready||!m||!L)return;const group=L.layerGroup().addTo(m);const s=props.selected;if(s&&!props.stops.some(x=>x.id===s.id)){const el=document.createElement("div");el.className=`selected-pin fam-${signFamily(s.kind)}`;L.marker(ll(s.coordinates),{icon:L.divIcon({html:el,className:"trippr-div-marker",iconSize:[28,36],iconAnchor:[14,36]}),keyboard:false,interactive:false,zIndexOffset:900}).addTo(group);}props.weatherPoints.forEach(p=>L.marker(ll(p.coordinates),{icon:icon(L,weatherChip(p,()=>latest.current.onWeather(p.name)),[46,26],[-6,60]),keyboard:false,zIndexOffset:1200}).addTo(group));props.hazards.forEach(h=>L.marker(ll(h.coordinates),{icon:icon(L,hazardMarker(h,()=>latest.current.onHazard(h)),[26,26],[13,13]),keyboard:false,zIndexOffset:1100}).addTo(group));props.alerts.filter(a=>a.geometry).forEach(a=>{const severe=["Severe","Extreme"].includes(a.severity);L.geoJSON({type:"Feature",properties:{},geometry:a.geometry!} as GeoJSON.Feature,{style:{color:severe?"#e2563f":"#f4c430",weight:1.4,dashArray:"5 4",fillColor:severe?"#d9412b":"#f4c430",fillOpacity:.14}}).addTo(group);});return()=>{group.remove();};},[ready,props.weatherPoints,props.hazards,props.alerts,props.selected,props.stops]);
 const peekEl=useRef<HTMLDivElement|null>(null);if(!peekEl.current&&typeof document!=="undefined"){peekEl.current=document.createElement("div");peekEl.current.className="peek-anchor";}
 const peekKey=props.peekAt?props.peekAt.join(","):"";
 useEffect(()=>{const m=map.current,L=lib.current,el=peekEl.current;if(!ready||!m||!L||!el||!props.peekAt)return;const marker=L.marker(ll(props.peekAt),{icon:L.divIcon({html:el,className:"trippr-div-marker",iconSize:[0,0],iconAnchor:[0,0]}),keyboard:false,zIndexOffset:2000}).addTo(m);return()=>{marker.remove();};},[ready,peekKey]);
 return <><div className="map-surface raster-map" ref={host}/>{props.peekAt&&ready&&peekEl.current&&createPortal(props.peekContent,peekEl.current)}{!ready&&!error&&<div className="map-loading"><span>Unfolding the atlas…</span></div>}{error&&<div className="map-error" role="alert">{error}</div>}</>;
});
