"use client";
import {useEffect,useMemo,useState} from "react";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Command,CommandInput,CommandList,CommandGroup,CommandItem,CommandEmpty} from "@/components/ui/command";
import {REFERENCE_PLACES,CATEGORY_LABELS} from "@/lib/trippr/data";
import {providers} from "@/lib/trippr/adapters";
import type {Place} from "@/lib/trippr/types";
import {PlaceIcon} from "./icons";
import {LoaderCircle,Plus} from "lucide-react";
export default function Search({open,onClose,onSelect,addMode,nearby}:{open:boolean;onClose():void;onSelect(p:Place):void;addMode:boolean;nearby:Place[]}){
 const [query,setQuery]=useState(""),[remote,setRemote]=useState<Place[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState("");
 useEffect(()=>{if(open){setQuery("");setRemote([]);setError("");}},[open]);
 const local=useMemo(()=>{const q=query.toLowerCase().trim();const all=[...REFERENCE_PLACES,...nearby];return all.filter((p,i)=>all.findIndex(x=>x.id===p.id)===i&&(q?`${p.name} ${p.region||""} ${CATEGORY_LABELS[p.kind]}`.toLowerCase().includes(q):["grca","zion","yose","deva","arch","whsa"].includes(p.id))).slice(0,12);},[query,nearby]);
 useEffect(()=>{if(!open||query.trim().length<3){setRemote([]);setLoading(false);return;}const controller=new AbortController();setLoading(true);setError("");const timer=setTimeout(()=>{providers.search.get(query,controller.signal).then(d=>setRemote(d.places)).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});},420);return()=>{clearTimeout(timer);controller.abort();};},[query,open]);
 const choose=(p:Place)=>{onSelect(p);onClose();};
 return <Dialog open={open} onOpenChange={v=>{if(!v)onClose();}}><DialogContent className="search-dialog" showCloseButton={false}><DialogTitle className="sr-only">{addMode?"Add a trip stop":"Search destinations"}</DialogTitle><DialogDescription className="sr-only">Search cities, addresses, parks, landmarks, and discovered campgrounds. Choose a result to {addMode?"add it to your trip":"explore it on the map"}.</DialogDescription><Command shouldFilter={false} className="search-command"><CommandInput value={query} onValueChange={setQuery} placeholder={addMode?"Where’s the next stop?":"A city, park, address, or open road…"} autoFocus/><CommandList><CommandEmpty>{loading?"Searching…":"No locations found. Try a nearby town or map point."}</CommandEmpty>{local.length>0&&<CommandGroup heading={query?"Parks & discovered places":"A few good places to start"}>{local.map(p=><CommandItem key={p.id} value={p.id} onSelect={()=>choose(p)}><span className="result-icon"><PlaceIcon kind={p.kind}/></span><span><strong>{p.name}</strong><small>{CATEGORY_LABELS[p.kind]} · {p.region||"United States"}</small></span>{addMode&&<Plus style={{marginLeft:"auto"}}/>}</CommandItem>)}</CommandGroup>}{remote.length>0&&<CommandGroup heading="Cities, addresses & landmarks">{remote.filter(p=>!local.some(x=>x.name===p.name)).map(p=><CommandItem key={p.id} value={p.id} onSelect={()=>choose(p)}><span className="result-icon"><PlaceIcon kind={p.kind}/></span><span><strong>{p.name}</strong><small>{p.region||p.source}</small></span></CommandItem>)}</CommandGroup>}</CommandList>{loading&&<div className="search-status"><LoaderCircle size={13} className="spin" style={{display:"inline",marginRight:7}}/>Finding destinations</div>}{error&&<div className="search-status" role="status">{error} Park search remains available.</div>}<div className="search-help"><span>↑ ↓ to navigate</span><span>Enter to choose</span><span>Esc to close</span></div></Command></DialogContent></Dialog>;
}
