"use client";
import type * as GeoJSON from "geojson";
import {useEffect,useRef,useState,useImperativeHandle,forwardRef} from "react";
import type {Map as GLMap,Marker,GeoJSONSource} from "maplibre-gl";
import type {Place,Stop,Route,Coordinate,Weather,Hazard,Alert} from "@/lib/trippr/types";
import {buildMapStyle,addRouteLayers,loadMapLibre,type MapTheme} from "@/lib/trippr/map-style";
import {boundsOf} from "@/lib/trippr/geo";
import {weatherDescription,weatherTone} from "@/lib/trippr/adapters";
import {LoaderCircle,RefreshCw} from "lucide-react";
import RasterMap from "./RasterMap";
export interface MapHandle{flyTo(p:Coordinate,zoom?:number):void;fit(points?:Coordinate[]):void;zoom(delta:number):void;north():void;terrain(active:boolean):boolean;locate():void;getMap():GLMap|null;}
export interface MapProps{places:Place[];stops:Stop[];route:Route|null;weatherPoints:{coordinates:Coordinate;weather:Weather;name:string}[];hazards:Hazard[];alerts:Alert[];theme:MapTheme;panelOpen:boolean;onPlace(p:Place):void;onPoint(p:Coordinate):void;onViewport(bbox:number[],zoom:number):void;onWeather(p:Coordinate,name:string):void;onHazard(h:Hazard):void;onReady():void;}
type Props=MapProps;
const TripprMap=forwardRef<MapHandle,Props>(function TripprMap(props,ref){
 const rasterRef=useRef<MapHandle>(null);
 const container=useRef<HTMLDivElement>(null),mapRef=useRef<GLMap|null>(null),glRef=useRef<typeof import("maplibre-gl")|null>(null),latest=useRef(props),markers=useRef<Marker[]>([]),weatherMarkers=useRef<Marker[]>([]),hazardMarkers=useRef<Marker[]>([]);latest.current=props;
 const [ready,setReady]=useState(false),[error,setError]=useState(""),[retry,setRetry]=useState(0),[version,setVersion]=useState(0),[fallback,setFallback]=useState(false);const terrainRef=useRef(false),firstFit=useRef(false);
 const reduced=()=>window.matchMedia("(prefers-reduced-motion: reduce)").matches;
 function fit(points?:Coordinate[]){if(rasterRef.current){rasterRef.current.fit(points);return;}const map=mapRef.current,line=points||latest.current.route?.coordinates||latest.current.stops.map(s=>s.coordinates);if(!map||!line.length)return;const b=boundsOf(line),mobile=window.innerWidth<761,panel=latest.current.panelOpen;map.fitBounds([[b[0],b[1]],[b[2],b[3]]],{padding:mobile?{top:145,bottom:panel?Math.min(innerHeight*.57+78,innerHeight*.7):230,left:55,right:55}:{top:155,bottom:205,left:panel?420:100,right:125},maxZoom:11,duration:reduced()?0:1000});}
 function setTerrain(active:boolean){const map=mapRef.current;if(!map?.isStyleLoaded())return false;terrainRef.current=active;if(active){if(!map.getSource("terrain-dem"))map.addSource("terrain-dem",{type:"raster-dem",tiles:["https://elevation-tiles-prod.s3.amazonaws.com/terrarium/{z}/{x}/{y}.png"],encoding:"terrarium",tileSize:256,maxzoom:15,attribution:"Terrain © Mapzen / AWS Open Data"});map.setTerrain({source:"terrain-dem",exaggeration:1.4});map.easeTo({pitch:55,duration:reduced()?0:600});}else{map.setTerrain(null);map.easeTo({pitch:0,duration:reduced()?0:600});}return true;}
 useImperativeHandle(ref,()=>({flyTo(p,zoom=10){if(rasterRef.current){rasterRef.current.flyTo(p,zoom);return;}mapRef.current?.flyTo({center:p,zoom,duration:reduced()?0:1300,padding:window.innerWidth<761?{top:90,bottom:200,left:0,right:0}:{top:70,bottom:40,left:latest.current.panelOpen?280:0,right:0}});},fit,zoom(d){if(rasterRef.current){rasterRef.current.zoom(d);return;}const m=mapRef.current;if(m)m.easeTo({zoom:m.getZoom()+d,duration:reduced()?0:300});},north(){if(rasterRef.current){rasterRef.current.north();return;}mapRef.current?.easeTo({bearing:0,duration:reduced()?0:450});},terrain:setTerrain,locate(){if(rasterRef.current){rasterRef.current.locate();return;}navigator.geolocation?.getCurrentPosition(p=>mapRef.current?.flyTo({center:[p.coords.longitude,p.coords.latitude],zoom:11}),()=>setError("Location access was unavailable. You can still search for your starting point."),{timeout:10000});},getMap:()=>mapRef.current}),[]);
 useEffect(()=>{if(fallback)return;let disposed=false,m:GLMap|undefined,deadline:ReturnType<typeof setTimeout>|undefined;setError("");setReady(false);(async()=>{try{const probe=document.createElement("canvas");if(!probe.getContext("webgl2")){setFallback(true);return;}const gl=await loadMapLibre(),style=await buildMapStyle(latest.current.theme);if(disposed||!container.current)return;glRef.current=gl;m=new gl.Map({container:container.current,style,center:[-108.5,38.2],zoom:4.2,minZoom:2,maxZoom:18,attributionControl:{compact:true},canvasContextAttributes:{antialias:true,preserveDrawingBuffer:true},maxPitch:70});mapRef.current=m;deadline=setTimeout(()=>{if(!disposed&&!m?.loaded())setFallback(true);},18000);m.addControl(new gl.ScaleControl({unit:"imperial"}),"bottom-left");
 m.on("load",()=>{clearTimeout(deadline);if(disposed)return;setReady(true);setVersion(v=>v+1);latest.current.onReady();});
 m.on("style.load",()=>{if(disposed)return;setVersion(v=>v+1);if(terrainRef.current)setTerrain(true);});
 let timer:ReturnType<typeof setTimeout>;m.on("moveend",()=>{clearTimeout(timer);timer=setTimeout(()=>{if(disposed||!m)return;const b=m.getBounds();latest.current.onViewport([b.getWest(),b.getSouth(),b.getEast(),b.getNorth()],m.getZoom());},500);});
 m.on("click",e=>{const hits=m!.getLayer("trippr-pois")?m!.queryRenderedFeatures(e.point,{layers:["trippr-pois","trippr-clusters"]}):[];if(hits.length){const f=hits[0];if(f.properties?.cluster){const source=m!.getSource("trippr-places") as GeoJSONSource;source.getClusterExpansionZoom(f.properties.cluster_id).then(z=>m!.easeTo({center:(f.geometry as GeoJSON.Point).coordinates as Coordinate,zoom:z}));}else{const p=latest.current.places.find(x=>x.id===f.properties?.id);if(p)latest.current.onPlace(p);}return;}latest.current.onPoint([e.lngLat.lng,e.lngLat.lat]);});
 m.on("error",e=>{if((e.error?.message||"").includes("WebGL"))setError("Your browser could not start the interactive map. Enable hardware acceleration and reload.");});
 const canvas=m.getCanvas();canvas.setAttribute("aria-label","Interactive road-trip map. Search and itinerary controls provide keyboard access to destinations.");canvas.tabIndex=0;
 }catch(error){console.warn("Trippr map could not initialize",error);if(!disposed)setFallback(true);}})();return()=>{disposed=true;clearTimeout(deadline);m?.remove();mapRef.current=null;markers.current=[];weatherMarkers.current=[];hazardMarkers.current=[];};},[retry,fallback]);
 useEffect(()=>{let cancelled=false;const m=mapRef.current;if(!ready||!m)return;(async()=>{const s=await buildMapStyle(props.theme);if(!cancelled&&mapRef.current===m)m.setStyle(s);})();return()=>{cancelled=true;};},[props.theme]);
 useEffect(()=>{const m=mapRef.current;if(!ready||!m?.isStyleLoaded())return;addRouteLayers(m,props.route?.coordinates||props.stops.map(s=>s.coordinates),!props.route);if(!firstFit.current&&props.stops.length>1){firstFit.current=true;fit();}},[ready,version,props.route,props.stops]);
 useEffect(()=>{const m=mapRef.current;if(!ready||!m?.isStyleLoaded())return;const data:GeoJSON.FeatureCollection={type:"FeatureCollection",features:props.places.map(p=>({type:"Feature",properties:{id:p.id,name:p.name,kind:p.kind},geometry:{type:"Point",coordinates:p.coordinates}}))};if(m.getSource("trippr-places")){(m.getSource("trippr-places") as GeoJSONSource).setData(data);return;}m.addSource("trippr-places",{type:"geojson",data,cluster:true,clusterMaxZoom:8,clusterRadius:38});m.addLayer({id:"trippr-clusters",type:"circle",source:"trippr-places",filter:["has","point_count"],paint:{"circle-color":"#304b32","circle-stroke-color":"#9bbf74","circle-stroke-width":1,"circle-radius":["step",["get","point_count"],17,10,21,50,26]}});if(props.theme!=="satellite")m.addLayer({id:"trippr-cluster-count",type:"symbol",source:"trippr-places",filter:["has","point_count"],layout:{"text-field":["get","point_count_abbreviated"],"text-font":["Noto Sans Regular"],"text-size":12},paint:{"text-color":"#e2f0cb"}});m.addLayer({id:"trippr-pois",type:"circle",source:"trippr-places",filter:["!",["has","point_count"]],paint:{"circle-radius":["interpolate",["linear"],["zoom"],3,5,10,8],"circle-color":["match",["get","kind"],"camp","#dda979","ev","#93b7eb","fuel","#d9b868","park","#a3cc76","#bfceb6"],"circle-stroke-color":"#213224","circle-stroke-width":2,"circle-opacity":.95}});if(props.theme!=="satellite")m.addLayer({id:"trippr-poi-label",type:"symbol",source:"trippr-places",minzoom:7,filter:["!",["has","point_count"]],layout:{"text-field":["get","name"],"text-font":["Noto Sans Regular"],"text-size":12,"text-anchor":"top","text-offset":[0,1],"text-max-width":12},paint:{"text-color":"#deead4","text-halo-color":"#15261d","text-halo-width":2}});},[ready,version,props.places,props.theme]);
 useEffect(()=>{const m=mapRef.current,gl=glRef.current;if(!ready||!m||!gl)return;markers.current.forEach(x=>x.remove());markers.current=props.stops.map((s,i)=>{const el=document.createElement("button");el.type="button";el.className=`stop-marker ${i===0?"first":i===props.stops.length-1?"last":""}`;el.textContent=String(i+1);el.setAttribute("aria-label",`Stop ${i+1}: ${s.name}`);el.addEventListener("click",e=>{e.stopPropagation();latest.current.onPlace(s);});return new gl.Marker({element:el}).setLngLat(s.coordinates).addTo(m);});return()=>{markers.current.forEach(x=>x.remove());};},[ready,props.stops]);
 useEffect(()=>{const m=mapRef.current,gl=glRef.current;if(!ready||!m||!gl)return;weatherMarkers.current.forEach(x=>x.remove());weatherMarkers.current=props.weatherPoints.map(p=>{const el=document.createElement("button");el.type="button";el.className="weather-marker";el.dataset.tone=weatherTone(p.weather.code,p.weather.temperature);el.textContent=`${Math.round(p.weather.temperature)}°`;el.title=`${p.name}: ${weatherDescription(p.weather.code)} · modeled current weather`;el.setAttribute("aria-label",el.title);el.addEventListener("click",e=>{e.stopPropagation();latest.current.onWeather(p.coordinates,p.name);});return new gl.Marker({element:el,offset:[0,-38]}).setLngLat(p.coordinates).addTo(m);});return()=>{weatherMarkers.current.forEach(x=>x.remove());};},[ready,props.weatherPoints]);
 useEffect(()=>{const m=mapRef.current,gl=glRef.current;if(!ready||!m||!gl)return;hazardMarkers.current.forEach(x=>x.remove());hazardMarkers.current=props.hazards.map(h=>{const el=document.createElement("button");el.type="button";el.className="weather-marker";el.dataset.tone=h.kind==="fire"?"heat":h.kind==="river"?"rain":"storm";el.textContent=h.kind==="fire"?"Heat":h.kind==="river"?"River":"Road";el.setAttribute("aria-label",h.title);el.addEventListener("click",e=>{e.stopPropagation();latest.current.onHazard(h);});return new gl.Marker({element:el}).setLngLat(h.coordinates).addTo(m);});return()=>{hazardMarkers.current.forEach(x=>x.remove());};},[ready,props.hazards]);
 useEffect(()=>{const m=mapRef.current;if(!ready||!m?.isStyleLoaded())return;const data:GeoJSON.FeatureCollection={type:"FeatureCollection",features:props.alerts.filter(a=>a.geometry).map(a=>({type:"Feature",properties:{severity:a.severity},geometry:a.geometry!}))};if(m.getSource("trippr-alerts"))(m.getSource("trippr-alerts") as GeoJSONSource).setData(data);else{m.addSource("trippr-alerts",{type:"geojson",data});m.addLayer({id:"trippr-alert-fill",type:"fill",source:"trippr-alerts",paint:{"fill-color":"#edb174","fill-opacity":.12}});m.addLayer({id:"trippr-alert-outline",type:"line",source:"trippr-alerts",paint:{"line-color":"#e6af79","line-width":1.3,"line-dasharray":[3,2]}});}},[ready,version,props.alerts]);
 useEffect(()=>{const m=mapRef.current;if(!ready||!m?.isStyleLoaded())return;const data:GeoJSON.FeatureCollection={type:"FeatureCollection",features:props.places.filter(p=>p.geometry).map(p=>({type:"Feature",properties:{id:p.id},geometry:p.geometry!}))};if(m.getSource("trippr-lands"))(m.getSource("trippr-lands") as GeoJSONSource).setData(data);else{m.addSource("trippr-lands",{type:"geojson",data});const before=m.getLayer("trip-route-glow")?"trip-route-glow":undefined;m.addLayer({id:"trippr-land-fill",type:"fill",source:"trippr-lands",paint:{"fill-color":"#a3cc76","fill-opacity":.08}},before);m.addLayer({id:"trippr-land-edge",type:"line",source:"trippr-lands",paint:{"line-color":"#9fbf77","line-width":1,"line-opacity":.55}},before);}},[ready,version,props.places]);
 if(fallback)return <RasterMap {...props} ref={rasterRef}/>;
 return <><div className="map-surface" ref={container}/><div className="map-shade"/>{!ready&&!error&&<div className="map-loading"><span><LoaderCircle className="spin" size={18}/>Unfolding the atlas…</span></div>}{error&&<div role="alert" className="map-error glass">{error}<br/><button className="outline-button" onClick={()=>setRetry(r=>r+1)}><RefreshCw size={16}/>Retry map</button></div>}</>;
});export default TripprMap;
