"use client";
import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {Toaster,toast} from "sonner";
import {Search as SearchIcon,Route as RouteIcon,Binoculars,Share2,Layers as LayersIcon,Plus,Minus,LocateFixed,Maximize,Minimize,Mountain,Bookmark,Settings2,CloudSun,ShieldCheck,PanelLeftOpen,X,MapPin,Save,Map as MapIcon,Satellite,Compass} from "lucide-react";
import type {Place,Trip,Route,Coordinate,Weather,Alert,LayerState,Hazard,PlaceKind} from "@/lib/trippr/types";
import {REFERENCE_PLACES,INITIAL_LAYERS,createDemoTrip,createEmptyTrip,CATEGORY_LABELS} from "@/lib/trippr/data";
import {newId,validCoordinate,distanceToRoute,sampleLine,milesBetween} from "@/lib/trippr/geo";
import {providers,ProviderError,api} from "@/lib/trippr/adapters";
import {localTripRepository,readUI,writeUI} from "@/lib/trippr/storage";
import type {MapTheme} from "@/lib/trippr/map-style";
import TripprMap,{type MapHandle} from "./TripprMap";
import Planner from "./Planner";
import PlaceDetails from "./PlaceDetails";
import Search from "./Search";
import Layers from "./Layers";
import TripDialogs,{type DialogName} from "./TripDialogs";
import {PlaceIcon} from "./icons";
const uniquePlaces=(places:Place[])=>[...new Map(places.map(p=>[p.id,p])).values()];
function compatibleCharger(p:Place,connector:string){if(p.kind!=="ev"||connector==="all")return true;const t=p.tags||{},text=(t.connectors||Object.entries(t).filter(([k,v])=>k.startsWith("socket:")&&v!=="no"&&v!=="0").map(([k])=>k).join(" ")).toLowerCase();const names:Record<string,string[]>={J1772:["j1772","type1"],CCS:["ccs","type1_combo","type2_combo"],NACS:["nacs","tesla"],CHADEMO:["chademo"],TYPE2:["type2"]};return(names[connector]||[]).some(s=>text.includes(s));}
function campMatches(p:Place,filters:string[]){if(p.kind!=="camp"||!filters.length)return true;return filters.some(f=>f==="tents"?p.amenities?.Tents===true:f==="rv"?p.amenities?.["RV / caravan"]===true:p.tags?.backcountry==="yes"||p.tags?.camp_site==="basic"||p.tags?.camp_site==="wild"||p.tags?.camp_site==="backcountry");}
export default function Trippr(){
 const[trip,setTrip]=useState<Trip|null>(null),[saved,setSaved]=useState<Trip[]>([]),[route,setRoute]=useState<Route|null>(null),[routeLoading,setRouteLoading]=useState(false),[routeError,setRouteError]=useState(""),[panelOpen,setPanelOpen]=useState(true),[tab,setTab]=useState("stops"),[selected,setSelected]=useState<Place|null>(null),[searchOpen,setSearchOpen]=useState(false),[addMode,setAddMode]=useState(false),[layersOpen,setLayersOpen]=useState(false),[dialog,setDialog]=useState<DialogName>(null),[layers,setLayers]=useState(INITIAL_LAYERS),[layerStatus,setLayerStatus]=useState<Record<string,LayerState>>({}),[campFilters,setCampFilters]=useState<string[]>([]),[mapTheme,setMapTheme]=useState<MapTheme>("atlas"),[theme,setTheme]=useState("dark"),[fontSize,setFontSize]=useState(100),[terrain,setTerrain]=useState(false),[fullScreen,setFullScreen]=useState(false),[viewport,setViewport]=useState<number[]>([-123,29,-91,45]),[zoom,setZoom]=useState(4),[discovered,setDiscovered]=useState<Place[]>([]),[weather,setWeather]=useState<Record<string,Weather>>({}),[routeWeather,setRouteWeather]=useState<{coordinates:Coordinate;weather:Weather;name:string}[]>([]),[corridor,setCorridor]=useState(25),[filters,setFilters]=useState<PlaceKind[]>(["park","camp"]),[discoveryMode,setDiscoveryMode]=useState<"route"|"viewport">("route"),[discoveryLoading,setDiscoveryLoading]=useState(false),[discoveryError,setDiscoveryError]=useState(""),[alerts,setAlerts]=useState<Alert[]>([]),[alertLoading,setAlertLoading]=useState(false),[alertError,setAlertError]=useState(""),[alertChecked,setAlertChecked]=useState(""),[hazards,setHazards]=useState<Record<string,Hazard[]>>({}),[point,setPoint]=useState<Coordinate|null>(null),[welcome,setWelcome]=useState(false),[draftStatus,setDraftStatus]=useState("Saving draft…");
 const map=useRef<MapHandle>(null),latest=useRef({trip,route,viewport,zoom,filters,corridor,discoveryMode});latest.current={trip,route,viewport,zoom,filters,corridor,discoveryMode};const discoveryController=useRef<AbortController|null>(null),viewportController=useRef<AbortController|null>(null),alertsController=useRef<AbortController|null>(null),conditionControllers=useRef<Record<string,AbortController>>({});
 const update=useCallback((t:Trip)=>setTrip({...t,modifiedAt:new Date().toISOString()}),[]);
 useEffect(()=>{try{const current=localTripRepository.draft();setTrip(current||createDemoTrip());setSaved(localTripRepository.list());}catch(e){setTrip(createDemoTrip());toast.error(e instanceof Error?e.message:"Saved data is unavailable.");}const ui=readUI();if(ui.theme==="light"){setTheme("light");setMapTheme("light");}if(ui.fontSize)setFontSize(Math.max(90,Math.min(150,ui.fontSize)));return()=>{discoveryController.current?.abort();viewportController.current?.abort();alertsController.current?.abort();Object.values(conditionControllers.current).forEach(c=>c.abort());};},[]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;document.documentElement.style.fontSize=`${fontSize}%`;writeUI({theme,fontSize});},[theme,fontSize]);
 useEffect(()=>{if(!trip)return;setDraftStatus("Saving draft…");const timer=setTimeout(()=>{try{localTripRepository.writeDraft(trip);setDraftStatus("Draft saved on this device");}catch{setDraftStatus("Draft could not be saved");toast.error("Device storage is full or unavailable. Keep this tab open so your current trip is not lost.",{id:"storage-error"});}},350);return()=>clearTimeout(timer);},[trip]);
 const routingKey=JSON.stringify([trip?.stops.map(s=>s.coordinates),trip?.preferences.avoidTolls,trip?.preferences.avoidHighways,trip?.preferences.avoidFerries]);
 useEffect(()=>{const t=latest.current.trip;setRoute(null);setRouteError("");if(!t||t.stops.length<2){setRouteLoading(false);setDiscoveryMode("viewport");return;}const ac=new AbortController();setRouteLoading(true);const timer=setTimeout(()=>{providers.routing.get(t.stops.map(s=>s.coordinates),t.preferences,ac.signal).then(r=>{setRoute(r);setDiscoveryMode("route");}).catch(e=>{if(!ac.signal.aborted)setRouteError(e.message);}).finally(()=>{if(!ac.signal.aborted)setRouteLoading(false);});},450);return()=>{clearTimeout(timer);ac.abort();};},[routingKey]);
 const weatherKey=JSON.stringify(trip?.stops.map(s=>[s.id,s.coordinates]));
 useEffect(()=>{const t=latest.current.trip;if(!t)return;const ac=new AbortController();Promise.allSettled(uniquePlaces(t.stops).map(s=>providers.weather.get(s.coordinates,ac.signal).then(w=>{if(!ac.signal.aborted)setWeather(old=>({...old,[s.id]:w}));}))).then(()=>{});return()=>ac.abort();},[weatherKey]);
 const activeKinds=layers.filter(l=>l.enabled&&l.kind).map(l=>l.kind!),activeKindsKey=activeKinds.filter(k=>!["park","city"].includes(k)).sort().join(",");
 const onViewport=useCallback((b:number[],z:number)=>{setViewport(b);setZoom(z);setPoint(null);},[]);
 useEffect(()=>{viewportController.current?.abort();if(!trip||zoom<7.5||viewport[2]-viewport[0]>7||viewport[3]-viewport[1]>7||!activeKindsKey)return;const ac=new AbortController();viewportController.current=ac;const kinds=activeKindsKey.split(",");const timer=setTimeout(()=>{for(const l of layers.filter(l=>l.kind&&kinds.includes(l.kind)))setLayerStatus(old=>({...old,[l.id]:{status:"loading"}}));providers.places.viewport(viewport,kinds,ac.signal).then(d=>{if(ac.signal.aborted)return;setDiscovered(old=>uniquePlaces([...d.places,...old]).slice(0,4500));setLayerStatus(old=>{const next={...old};for(const l of layers.filter(l=>l.kind&&kinds.includes(l.kind)))next[l.id]={status:"ready",count:d.places.filter(p=>p.kind===l.kind).length,source:d.source||"OpenStreetMap",updated:d.updated};return next;});}).catch(e=>{if(ac.signal.aborted)return;setLayerStatus(old=>{const next={...old};for(const l of layers.filter(l=>l.kind&&kinds.includes(l.kind)))next[l.id]={status:"unavailable",message:e.message};return next;});});},650);return()=>{clearTimeout(timer);ac.abort();};},[viewport.map(n=>n.toFixed(2)).join(","),Math.floor(zoom),activeKindsKey,!!trip]);
 const allPlaces=useMemo(()=>uniquePlaces([...REFERENCE_PLACES,...discovered]),[discovered]);
 const visiblePlaces=useMemo(()=>allPlaces.filter(p=>activeKinds.includes(p.kind)&&campMatches(p,campFilters)&&compatibleCharger(p,trip?.preferences.connector||"all")),[allPlaces,activeKindsKey,layers,campFilters,trip?.preferences.connector]);
 const results=useMemo(()=>{if(!filters.length)return[];let places=allPlaces.filter(p=>filters.includes(p.kind)&&campMatches(p,campFilters)&&compatibleCharger(p,trip?.preferences.connector||"all"));if(discoveryMode==="route"&&route)places=places.map(p=>({...p,distanceFromRoute:distanceToRoute(p.coordinates,route.coordinates)})).filter(p=>p.distanceFromRoute<=corridor).sort((a,b)=>a.distanceFromRoute-b.distanceFromRoute);else places=places.filter(p=>p.coordinates[0]>=viewport[0]&&p.coordinates[0]<=viewport[2]&&p.coordinates[1]>=viewport[1]&&p.coordinates[1]<=viewport[3]);return places;},[allPlaces,filters,campFilters,trip?.preferences.connector,discoveryMode,route,corridor,viewport]);
 const selectPlace=useCallback((p:Place)=>{setPoint(null);setSelected(p);setWelcome(false);map.current?.flyTo(p.coordinates,["park","land","recreation"].includes(p.kind)?8.5:11);},[]);
 const addPlace=useCallback((p:Place,overnight=false,append=false)=>{const t=latest.current.trip;if(!t)return;if(t.stops.length>=20){toast.error("A trip can have up to 20 routing stops.");return;}let index=t.stops.length;if(!append&&t.stops.length>=2){let least=Infinity;for(let i=1;i<t.stops.length;i++){const a=t.stops[i-1].coordinates,b=t.stops[i].coordinates,extra=milesBetween(a,p.coordinates)+milesBetween(p.coordinates,b)-milesBetween(a,b);if(extra<least){least=extra;index=i;}}}const stops=[...t.stops];stops.splice(index,0,{...p,stopId:newId(),overnight});update({...t,stops});setPanelOpen(true);setTab("stops");setWelcome(false);setPoint(null);toast.success(`${p.name} added as stop ${index+1}.`);},[update]);
 function reorder(from:number,to:number){const t=latest.current.trip;if(!t||from===to||to<0||to>=t.stops.length)return;const stops=[...t.stops],[stop]=stops.splice(from,1);stops.splice(to,0,stop);update({...t,stops});}
 const runDiscover=useCallback(async(mode?:"route"|"viewport",area?:number[],chosen?:PlaceKind[])=>{const t=latest.current,kinds=(chosen||t.filters).filter(k=>!["park","city"].includes(k));if(!kinds.length){setDiscoveryError("");return;}const useRoute=(mode||t.discoveryMode)==="route";if(useRoute&&!t.route){setDiscoveryError("Create a driving route first, or search this map area.");return;}const b=area||t.viewport;if(!useRoute&&(b[2]-b[0]>7||b[3]-b[1]>7)){setDiscoveryError("Zoom closer, then search this area.");return;}discoveryController.current?.abort();const ac=new AbortController();discoveryController.current=ac;setDiscoveryLoading(true);setDiscoveryError("");try{const d=useRoute?await providers.places.corridor(sampleLine(t.route!.coordinates,Math.min(150,t.route!.coordinates.length)),t.corridor,kinds,ac.signal):await providers.places.viewport(b,kinds,ac.signal);if(ac.signal.aborted)return;setDiscovered(old=>uniquePlaces([...d.places,...old]).slice(0,4500));setLayers(old=>old.map(l=>!!l.kind&&kinds.includes(l.kind)?{...l,enabled:true}:l));setLayerStatus(old=>{const next={...old};for(const l of layers.filter(l=>!!l.kind&&kinds.includes(l.kind)))next[l.id]={status:"ready",count:d.places.filter(p=>p.kind===l.kind).length,source:d.source||"OpenStreetMap",updated:d.updated};return next;});if(d.limited)setDiscoveryError("This search has limited coverage. Try fewer filters or a smaller area.");else if(!d.places.length)toast("No additional mapped places were returned. Try another filter or a wider corridor.");}catch(e){if(!ac.signal.aborted)setDiscoveryError(e instanceof Error?e.message:"Place search is unavailable.");}finally{if(!ac.signal.aborted)setDiscoveryLoading(false);}},[layers]);
 async function fetchCondition(id:string){const t=latest.current;conditionControllers.current[id]?.abort();const ac=new AbortController();conditionControllers.current[id]=ac;setLayerStatus(old=>({...old,[id]:{status:"loading"}}));try{
 if(id==="weather"){const points=t.route?sampleLine(t.route.coordinates,6):t.trip?.stops.map(s=>s.coordinates).slice(0,6)||[];const rs=await Promise.allSettled(points.map(async(coordinates,i)=>({coordinates,weather:await providers.weather.get(coordinates,ac.signal),name:`Route weather point ${i+1}`})));if(ac.signal.aborted)return;const data=rs.filter((r):r is PromiseFulfilledResult<{coordinates:Coordinate;weather:Weather;name:string}>=>r.status==="fulfilled").map(r=>r.value);setRouteWeather(data);setLayerStatus(old=>({...old,[id]:{status:data.length?"ready":"unavailable",source:"Open-Meteo · modeled current weather",count:data.length,message:!data.length?"Weather is unavailable along this route.":undefined}}));return;}
 if(id==="air"){const center:Coordinate=[(t.viewport[0]+t.viewport[2])/2,(t.viewport[1]+t.viewport[3])/2];const d=await api<{aqi:number;source:string;updated:string}>("air",{lat:center[1],lon:center[0]},ac.signal);if(ac.signal.aborted)return;setLayerStatus(old=>({...old,[id]:{status:"ready",source:`AQI ${Math.round(d.aqi)} · ${d.source}`,updated:d.updated}}));toast(`Map center: AQI ${Math.round(d.aqi)} · ${d.source}`);return;}
 const d=await providers.hazards.get(id,t.viewport,ac.signal);if(ac.signal.aborted)return;setHazards(old=>({...old,[id]:d.hazards}));setLayerStatus(old=>({...old,[id]:{status:"ready",source:d.source,count:d.hazards.length,updated:d.updated,message:d.coverage}}));
 }catch(e){if(ac.signal.aborted)return;const err=e as ProviderError;setLayerStatus(old=>({...old,[id]:{status:err.code==="not_configured"?"unconfigured":"unavailable",message:err.message}}));toast(err.message);}}
 const checkAlerts=useCallback(async()=>{
  const t=latest.current;alertsController.current?.abort();const ac=new AbortController();alertsController.current=ac;setAlertLoading(true);setAlertError("");setLayerStatus(old=>({...old,alerts:{status:"loading"},park:{status:"loading"}}));
  const points=t.route?sampleLine(t.route.coordinates,8):t.trip?.stops.map(s=>s.coordinates).slice(0,8)||[];if(!points.length)points.push([(t.viewport[0]+t.viewport[2])/2,(t.viewport[1]+t.viewport[3])/2]);
  const parks=[...new Map(t.trip?.stops.filter(s=>s.parkCode).map(s=>[s.parkCode,s])||[]).values()];
  const [rs,parkResults]=await Promise.all([Promise.allSettled(points.map(p=>providers.alerts.get(p,ac.signal))),Promise.allSettled(parks.map(async(p):Promise<{alerts:Alert[];partial:boolean}>=>{const d=await api<{alerts:Alert[];partial:boolean}>("park",{park:p.parkCode!},ac.signal);return{...d,alerts:d.alerts.map(a=>({...a,area:p.name,coordinates:p.coordinates,nearRoute:!!t.route}))};}))]);if(ac.signal.aborted)return;
  const good=rs.filter((r):r is PromiseFulfilledResult<{alerts:Alert[];updated:string}>=>r.status==="fulfilled"),parkGood=parkResults.filter((r):r is PromiseFulfilledResult<{alerts:Alert[];partial:boolean}>=>r.status==="fulfilled");
  setAlerts([...new Map([...good.flatMap(r=>r.value.alerts.map(a=>({...a,nearRoute:!!t.route}))),...parkGood.flatMap(r=>r.value.alerts)].map(a=>[a.id,a])).values()]);setAlertLoading(false);setAlertChecked(new Date().toISOString());
  setLayerStatus(old=>({...old,alerts:{status:good.length?"ready":"unavailable",source:`NWS · ${good.length}/${points.length} route points checked`,message:!good.length?"NWS alerts are temporarily unavailable.":undefined},park:{status:parkGood.length?"ready":parks.length?"unconfigured":"idle",source:"National Park Service",message:!parkGood.length?"Live park notices are not connected. Check official park conditions.":parkGood.some(r=>r.value.partial)?"Some park sources could not be checked.":undefined}}));
  if(good.length<points.length)setAlertError(`${points.length-good.length} of ${points.length} weather points could not be checked. Available results are shown.`);
 },[]);

 function toggleLayer(id:string){const layer=layers.find(l=>l.id===id);if(!layer)return;setLayers(old=>old.map(l=>l.id===id?{...l,enabled:!l.enabled}:l));if(!layer.enabled&&!layer.kind){if(id==="alerts")void checkAlerts();else void fetchCondition(id);}}
 const saveCurrent=useCallback((silent=false)=>{const t=latest.current.trip;if(!t)return false;try{localTripRepository.save(t);setSaved(localTripRepository.list());if(!silent)toast.success("Trip saved on this device.");return true;}catch{toast.error("This trip could not be saved. Device storage may be full.");return false;}},[]);
 function loadTrip(t:Trip){if(!saveCurrent(true))return;setTrip(t);setRoute(null);setSelected(null);setDialog(null);setPanelOpen(true);setWelcome(!t.stops.length);setTimeout(()=>map.current?.fit(t.stops.map(s=>s.coordinates)),250);}
 function newTrip(demo=false){if(trip?.stops.length&&!saveCurrent(true))return;const t=demo?createDemoTrip():createEmptyTrip();setTrip(t);setRoute(null);setSelected(null);setDialog(null);setPanelOpen(!!demo);setWelcome(!demo);setTab("stops");setTimeout(()=>{if(demo)map.current?.fit(t.stops.map(s=>s.coordinates));else map.current?.flyTo([-108.5,38.2],4.2);},250);}
 function nearby(p:Place,kind:"camp"|"fuel"){setSelected(null);setPanelOpen(true);setTab("discover");setDiscoveryMode("viewport");setFilters([kind]);setLayers(old=>old.map(l=>l.kind===kind?{...l,enabled:true}:l));const lat=p.coordinates[1],lon=p.coordinates[0],b=[lon-.5,lat-.4,lon+.5,lat+.4];setViewport(b);map.current?.flyTo(p.coordinates,9);void runDiscover("viewport",b,[kind]);}
 useEffect(()=>{const listener=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setAddMode(false);setSearchOpen(true);}if(e.key==="Escape")setPoint(null);};window.addEventListener("keydown",listener);const full=()=>setFullScreen(!!document.fullscreenElement);document.addEventListener("fullscreenchange",full);return()=>{window.removeEventListener("keydown",listener);document.removeEventListener("fullscreenchange",full);};},[]);
 useEffect(()=>{if(!trip?.preferences.evMode)return;setFilters(old=>old.includes("ev")?old:[...old,"ev"]);setLayers(old=>old.map(l=>l.kind==="ev"?{...l,enabled:true}:l));},[trip?.preferences.evMode]);
 useEffect(()=>{const ctx=(document as unknown as {modelContext?:{registerTool(tool:unknown,options:{signal:AbortSignal}):unknown}}).modelContext;if(!ctx?.registerTool)return;const life=new AbortController();const done=()=>new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));const tools=[{name:"trippr_read_trip",title:"Read current trip",description:"Read the visible trip itinerary and its latest driving estimate.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>{const t=latest.current.trip;if(!t)throw Error("Trippr is loading.");return{name:t.name,stops:t.stops.map(s=>({name:s.name,coordinates:s.coordinates,date:s.date})),route:latest.current.route?{distanceMeters:latest.current.route.distance,driveSeconds:latest.current.route.duration,source:latest.current.route.source}:null};}},{name:"trippr_add_stops",title:"Add trip stops",description:"Append 1–20 named map locations to the current visible trip. Stops are saved in the local draft.",inputSchema:{type:"object",properties:{stops:{type:"array",minItems:1,maxItems:20,items:{type:"object",properties:{name:{type:"string",minLength:1,maxLength:120},longitude:{type:"number",minimum:-180,maximum:180},latitude:{type:"number",minimum:-85,maximum:85}},required:["name","longitude","latitude"],additionalProperties:false}}},required:["stops"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input:unknown){const data=input as {stops?:{name:string;longitude:number;latitude:number}[]},t=latest.current.trip;if(!t||!data||!Array.isArray(data.stops)||!data.stops.length||data.stops.length+t.stops.length>20||data.stops.some(s=>!s||typeof s.name!=="string"||!s.name.trim()||s.name.length>120||!validCoordinate([s.longitude,s.latitude])))throw Error("Provide named valid coordinates within the 20-stop trip limit.");const stops=data.stops.map(s=>({id:newId(),stopId:newId(),name:s.name.trim(),kind:"city" as const,coordinates:[s.longitude,s.latitude] as Coordinate,source:"User-provided map location"}));update({...t,stops:[...t.stops,...stops]});setPanelOpen(true);setTab("stops");await done();return{added:stops.length,totalStops:t.stops.length+stops.length};}}];for(const tool of tools)try{void Promise.resolve(ctx.registerTool(tool,{signal:life.signal})).catch(()=>{});}catch{}return()=>life.abort();},[update]);
 if(!trip)return <main className="trippr-app"><div className="topbar"><a className="wordmark" href="/trippr/"><img src="/trippr/favicon.svg" alt=""/><strong>Trippr</strong></a></div><div className="map-loading"><span>Unfolding the atlas…</span></div></main>;
 const shownHazards=Object.entries(hazards).filter(([id])=>layers.some(l=>l.id===id&&l.enabled)).flatMap(([,h])=>h),weatherLayer=layers.some(l=>l.id==="weather"&&l.enabled),alertsLayer=layers.some(l=>l.id==="alerts"&&l.enabled),enabledCount=layers.filter(l=>l.enabled).length;
 const conditionNotices:Alert[]=shownHazards.filter(h=>route&&distanceToRoute(h.coordinates,route.coordinates)<=corridor&&(h.kind!=="river"||/major|moderate|minor|action stage/i.test(h.detail))).map(h=>({id:h.id,title:h.title,severity:"Informational",description:h.detail,area:`${distanceToRoute(h.coordinates,route!.coordinates).toFixed(0)} miles from the route`,source:h.source,url:h.url,updated:h.updated,coordinates:h.coordinates,nearRoute:true}));
 const featured=results.filter(p=>p.image).slice(0,3),fallback=["grca","zion","yose"].map(id=>REFERENCE_PLACES.find(p=>p.id===id)!);const dockPlaces=featured.length>=2?featured:fallback;
 return <main className={`trippr-app ${!panelOpen?"exploring":""}`}>
 <TripprMap ref={map} places={visiblePlaces} stops={trip.stops} route={route} weatherPoints={weatherLayer?routeWeather:[]} hazards={shownHazards} alerts={alertsLayer?alerts:[]} theme={mapTheme} panelOpen={panelOpen} onPlace={selectPlace} onPoint={p=>{setPoint(p);setWelcome(false);}} onViewport={onViewport} onWeather={()=>setDialog("weather")} onHazard={h=>{toast(h.title,{description:`${h.detail}${route?` ${distanceToRoute(h.coordinates,route.coordinates).toFixed(1)} mi from the route.`:""} Source: ${h.source}`,duration:9000});}} onReady={()=>{}}/>
 <header className="topbar"><button className="wordmark" aria-label="Trippr: fit current trip" onClick={()=>map.current?.fit()}><img src="/trippr/favicon.svg" alt=""/><strong>Trippr</strong><span className="brand-note">A SAFISOLUTIONS<br/>PROJECT</span></button><div className="top-center"><button className="search-button" onClick={()=>{setAddMode(false);setSearchOpen(true);}} aria-label="Search for a city, park, campground, or address"><SearchIcon size={18}/><span>Where are we going?</span><kbd>⌘ K</kbd></button><nav className="top-nav" aria-label="Map workspace"><button className={panelOpen&&tab==="stops"?"active":""} onClick={()=>{setPanelOpen(true);setTab("stops");setWelcome(false);}}><RouteIcon size={15}/>My trip</button><button className={!panelOpen?"active":""} onClick={()=>{setPanelOpen(false);setWelcome(false);}}><Binoculars size={15}/>Explore</button></nav></div><div className="top-actions"><button className="icon-button alerts-btn" aria-label="Trip conditions and alerts" title="Trip conditions" onClick={()=>{setDialog("alerts");if(!alertChecked)void checkAlerts();}}><ShieldCheck/></button><button className="icon-button saved-btn" aria-label="Saved trips" title="Saved trips" onClick={()=>setDialog("saved")}><Bookmark/></button><button className="icon-button settings-btn" aria-label="Trip preferences" title="Preferences" onClick={()=>setDialog("settings")}><Settings2/></button><button className="primary-button share-button" onClick={()=>setDialog("share")}><Share2/>Share trip</button></div></header>
 {panelOpen?<Planner trip={trip} route={route} routeLoading={routeLoading} routeError={routeError} tab={tab} setTab={setTab} onChange={update} onSelect={selectPlace} onAdd={()=>{setAddMode(true);setSearchOpen(true);}} onCollapse={()=>setPanelOpen(false)} onSave={()=>saveCurrent()} onManage={()=>setDialog("saved")} onReorder={reorder} weather={weather} corridor={corridor} setCorridor={setCorridor} filters={filters} setFilters={setFilters} results={results} discoveryLoading={discoveryLoading} discoveryError={discoveryError} onDiscover={()=>void runDiscover()} discoveryMode={discoveryMode} setDiscoveryMode={setDiscoveryMode} draftStatus={draftStatus}/>:<div className="panel-collapsed glass"><button onClick={()=>{setPanelOpen(true);setTab("stops");setWelcome(false);}}><PanelLeftOpen size={18}/>{trip.name||"My trip"}<span style={{color:"var(--quiet)",fontSize:12}}>{trip.stops.length} stops</span></button></div>}
 <button className="map-top-note" onClick={()=>{setLayersOpen(true);}}><LayersIcon/>{enabledCount} layers on<span style={{color:"var(--quiet)",fontSize:12}}>· {zoom<7.5?"Zoom in for local places":"Explore this area"}</span></button>
 <div className="map-controls"><div className="control-stack glass"><button className="icon-button north-button" aria-label="Reset map north" onClick={()=>map.current?.north()}><span>N</span></button></div><div className="control-stack glass"><button className="icon-button" aria-label="Zoom in" onClick={()=>map.current?.zoom(1)}><Plus/></button><button className="icon-button" aria-label="Zoom out" onClick={()=>map.current?.zoom(-1)}><Minus/></button></div><div className="control-stack glass"><button className={`icon-button ${terrain?"selected":""}`} aria-label={terrain?"Turn off 3D terrain":"Turn on 3D terrain"} onClick={()=>{if(map.current?.terrain(!terrain))setTerrain(!terrain);else toast("3D terrain needs a browser with graphics acceleration. The 2D map remains available.");}}><Mountain/></button><button className="icon-button" aria-label="Locate me" onClick={()=>map.current?.locate()}><LocateFixed/></button><button className="icon-button" aria-label="Fit entire trip on map" onClick={()=>map.current?.fit()}><RouteIcon/></button><button className="icon-button expand-map" aria-label={fullScreen?"Exit fullscreen":"Fullscreen map"} onClick={async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{toast("Fullscreen is unavailable in this browser.");}}}>{fullScreen?<Minimize/>:<Maximize/>}</button></div><button className="icon-button glass" aria-label="Map layers" onClick={()=>setLayersOpen(true)}><LayersIcon/></button><button className="icon-button glass" aria-label="Weather along the route" onClick={()=>setDialog("weather")}><CloudSun/></button></div>
 {!welcome&&<section className="discovery-dock" aria-label="Places along the way"><div className="dock-heading"><span>{route?"Along the way":"A few roads worth taking"}</span><button onClick={()=>{setPanelOpen(true);setTab("discover");}}>Discover more <Binoculars size={14}/></button></div><div className="detour-list">{dockPlaces.map(p=>{const stop=trip.stops.findIndex(s=>s.id===p.id),d=route?distanceToRoute(p.coordinates,route.coordinates):undefined;return <button className={`detour ${!p.image?"detour-plain":""}`} key={p.id} onClick={()=>selectPlace(p)}>{p.image?<img src={p.image} alt={p.name} loading="lazy"/>:<PlaceIcon kind={p.kind}/>}<span className="detour-badge">{stop>=0?`Stop ${stop+1}`:d!==undefined?`${d.toFixed(0)} mi from route`:p.region}</span><span className="detour-text"><small>{CATEGORY_LABELS[p.kind]} / {p.region}</small><strong>{p.name.replace(/ National Park( & Preserve)?$/,"")}</strong></span></button>;})}</div></section>}
 <div className="map-modes glass" role="group" aria-label="Base map"><button className={mapTheme!=="satellite"?"active":""} aria-pressed={mapTheme!=="satellite"} onClick={()=>setMapTheme(theme==="light"?"light":"atlas")}><MapIcon/>Atlas</button><button className={mapTheme==="satellite"?"active":""} aria-pressed={mapTheme==="satellite"} onClick={()=>setMapTheme("satellite")}><Satellite/>Satellite</button></div>
 {welcome&&<div className="welcome glass"><span className="eyebrow">THERE’S A WHOLE MAP OUT THERE</span><h1>Where are<br/>we <em>going?</em></h1><button className="primary-button" onClick={()=>{setAddMode(true);setSearchOpen(true);setWelcome(false);}}><Plus/>Plan a road trip</button><button className="tiny-button" onClick={()=>setWelcome(false)}>Just exploring</button></div>}
 {point&&<div className="point-context glass"><div className="head-inline"><h3>A place on the map.</h3><button className="tiny-button" aria-label="Close map point" onClick={()=>setPoint(null)}><X size={16}/></button></div><p>{point[1].toFixed(4)}°, {point[0].toFixed(4)}°</p><button className="primary-button" onClick={()=>addPlace({id:newId(),name:`Map stop ${trip.stops.length+1}`,coordinates:point,kind:"city",source:"User-selected map location"},false,true)}><Plus/>Add this stop</button></div>}
 <a className="footer-brand" href="/projects/" style={{textDecoration:"none"}} aria-label="Back to Safi Solutions projects">SAFI SOLUTIONS · PROJECTS</a><nav className="mobile-nav" aria-label="Mobile map navigation"><button className={panelOpen&&tab==="stops"?"active":""} onClick={()=>{setPanelOpen(!panelOpen||tab!=="stops");setTab("stops");setWelcome(false);}}><RouteIcon/>Trip</button><button className={panelOpen&&tab==="discover"?"active":""} onClick={()=>{setPanelOpen(true);setTab("discover");setWelcome(false);}}><Binoculars/>Discover</button><button onClick={()=>setLayersOpen(true)}><LayersIcon/>Layers</button><button onClick={()=>setDialog("saved")}><Bookmark/>Saved</button><button onClick={()=>setDialog("settings")}><Settings2/>Settings</button></nav>
 <Search open={searchOpen} onClose={()=>setSearchOpen(false)} addMode={addMode} nearby={discovered} onSelect={p=>addMode?addPlace(p,false,true):selectPlace(p)}/><Layers open={layersOpen} onClose={()=>setLayersOpen(false)} layers={layers} onToggle={toggleLayer} status={layerStatus} campFilters={campFilters} onCampFilters={setCampFilters}/><PlaceDetails place={selected} onClose={()=>setSelected(null)} trip={trip} route={route} onAdd={addPlace} onSave={p=>{update({...trip,savedPlaces:trip.savedPlaces.some(s=>s.id===p.id)?trip.savedPlaces.filter(s=>s.id!==p.id):[...trip.savedPlaces,p]});}} onNote={(id,text)=>update({...trip,placeNotes:{...trip.placeNotes,[id]:text}})} onNearby={nearby} onRouteHere={p=>{addPlace(p,false,true);setSelected(null);}}/>
 <TripDialogs dialog={dialog} onClose={()=>setDialog(null)} trip={trip} route={route} saved={saved} onLoad={loadTrip} onNew={newTrip} onDelete={id=>{try{localTripRepository.remove(id);setSaved(localTripRepository.list());}catch{toast.error("The saved trip could not be removed.");}}} onPreferences={p=>update({...trip,preferences:p})} theme={theme} onTheme={()=>{setTheme(theme==="light"?"dark":"light");if(mapTheme!=="satellite")setMapTheme(theme==="light"?"atlas":"light");}} fontSize={fontSize} onFont={setFontSize} alerts={[...alerts,...conditionNotices]} alertLoading={alertLoading} alertError={alertError} alertChecked={alertChecked} onCheckAlerts={()=>void checkAlerts()} statuses={layerStatus} weather={weather}/><Toaster position="top-center" theme={theme==="light"?"light":"dark"} richColors closeButton toastOptions={{style:{fontFamily:"DM Sans, Arial",fontSize:14}}}/>
 </main>;
}
