package blueprints

import (
	"bytes"
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"safisolutions.org/backplane/internal/core"
)

// templateVars returns Resend variable declarations for a system template.
func templateVars(key string) []any {
	var index []struct {
		Key       string   `json:"key"`
		Variables []string `json:"variables"`
	}
	_ = json.Unmarshal([]byte(Asset("emails/index.json")), &index)
	for _, t := range index {
		if t.Key != key {
			continue
		}
		out := make([]any, 0, len(t.Variables))
		for _, v := range t.Variables {
			out = append(out, map[string]any{"key": v, "type": "string", "fallback_value": fallbackFor(v)})
		}
		return out
	}
	return nil
}

func fallbackFor(v string) string {
	switch v {
	case "CUSTOMER_NAME":
		return "there"
	case "LICENSE_KEY", "LOCATION":
		return ""
	case "BUSINESS_NAME":
		return "Our team"
	case "SUPPORT_EMAIL":
		return "us"
	case "INTERVAL":
		return "month"
	case "EXPIRES":
		return "24 hours"
	case "ACTION_LABEL":
		return "Open"
	case "DEPOSIT":
		return "—"
	}
	return ""
}

// SystemEmails lists the reusable email templates Backplane can add to Resend.
func SystemEmails() []map[string]any {
	var index []map[string]any
	_ = json.Unmarshal([]byte(Asset("emails/index.json")), &index)
	return index
}

// SystemEmailHTML returns a system email's HTML.
func SystemEmailHTML(key string) string { return Asset("emails/" + key + ".html") }

// GenerateFiles produces every generated file for a project (path → content).
// Files are written to the project's code folder; the engine reads them by
// path, and user-edited copies are detected by hash and never overwritten.
func GenerateFiles(p *core.Project) (map[string]string, error) {
	bp := &p.Blueprint
	t, ok := Get(bp.TemplateID)
	if !ok {
		return nil, fmt.Errorf("unknown template %s", bp.TemplateID)
	}
	files := map[string]string{}
	switch t.Engine {
	case "commerce":
		worker := strings.ReplaceAll(Asset("commerce/worker.js"), "{{PROJECT_NAME}}", p.Name)
		files["worker/src/index.js"] = worker
		files["worker/wrangler.jsonc"] = WranglerConfig(bp)
		files["supabase/schema.sql"] = Asset("commerce/schema.sql")
		files["emails/purchase.html"] = Asset("emails/purchase.html")
		files["README.md"] = commerceReadme(p, t)
	case "data":
		for k, v := range dataFiles(p, t) {
			files[k] = v
		}
	}
	if bp.Param("include_github") != "false" {
		files[".github/workflows/deploy.yml"] = Asset("shared/deploy.yml")
		files[".gitignore"] = Asset("shared/gitignore.txt")
	}
	return files, nil
}

// WranglerConfig renders worker/wrangler.jsonc from the Worker's blueprint
// spec, so a deploy from GitHub Actions carries exactly the vars, bindings and
// crons Backplane deploys (wrangler replaces vars on every deploy). Secrets
// are never written here. Placeholders are resolved when the file is
// committed, with each value JSON-escaped.
func WranglerConfig(bp *core.Blueprint) string {
	var spec *core.ResourceSpec
	for i := range bp.Resources {
		if bp.Resources[i].Kind == "cloudflare.worker" {
			spec = &bp.Resources[i]
			break
		}
	}
	if spec == nil {
		return ""
	}
	props := spec.Props
	str := func(m map[string]any, k string) string { s, _ := m[k].(string); return s }
	var b strings.Builder
	b.WriteString("// Worker configuration — generated by Backplane for {{param:project_name}} ({{env}}).\n")
	b.WriteString("// Secrets are NOT stored here. They live encrypted in Cloudflare (set by\n// Backplane) and survive every deploy.\n{\n")
	b.WriteString(`  "$schema": "node_modules/wrangler/config-schema.json",` + "\n")
	fmt.Fprintf(&b, "  \"name\": \"{{out:%s.name}}\",\n", spec.Key)
	b.WriteString(`  "main": "src/index.js",` + "\n")
	compat := str(props, "compatibility_date")
	if compat == "" {
		compat = CompatibilityDate
	}
	fmt.Fprintf(&b, "  \"compatibility_date\": %s,\n", jsonText(compat))
	if flags, _ := props["compatibility_flags"].([]any); len(flags) > 0 {
		fmt.Fprintf(&b, "  \"compatibility_flags\": %s,\n", jsonText(flags))
	}
	if wd, ok := props["workers_dev"].(bool); ok {
		fmt.Fprintf(&b, "  \"workers_dev\": %t,\n", wd)
	}
	b.WriteString(`  "observability": { "enabled": true, "head_sampling_rate": 1 },` + "\n")
	var kv, r2 []string
	bindings, _ := props["bindings"].([]any)
	for _, x := range bindings {
		m, _ := x.(map[string]any)
		switch str(m, "type") {
		case "kv_namespace":
			kv = append(kv, fmt.Sprintf(`{ "binding": %s, "id": %s }`, jsonText(str(m, "name")), jsonText(str(m, "namespace_id"))))
		case "r2_bucket":
			r2 = append(r2, fmt.Sprintf(`{ "binding": %s, "bucket_name": %s }`, jsonText(str(m, "name")), jsonText(str(m, "bucket_name"))))
		}
	}
	if len(kv) > 0 {
		b.WriteString("  \"kv_namespaces\": [\n    " + strings.Join(kv, ",\n    ") + "\n  ],\n")
	}
	if len(r2) > 0 {
		b.WriteString("  \"r2_buckets\": [\n    " + strings.Join(r2, ",\n    ") + "\n  ],\n")
	}
	if crons, _ := props["crons"].([]any); len(crons) > 0 {
		fmt.Fprintf(&b, "  \"triggers\": { \"crons\": %s },\n", jsonText(crons))
	}
	vars, _ := props["vars"].(map[string]any)
	keys := make([]string, 0, len(vars))
	for k := range vars {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	b.WriteString("  \"vars\": {")
	for i, k := range keys {
		if i > 0 {
			b.WriteString(",")
		}
		fmt.Fprintf(&b, "\n    %s: %s", jsonText(k), jsonText(fmt.Sprint(vars[k])))
	}
	b.WriteString("\n  }\n}\n")
	return b.String()
}

// jsonText is compact JSON without HTML escaping, so {{placeholders}} and
// URLs stay readable.
func jsonText(v any) string {
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	_ = enc.Encode(v)
	return strings.TrimSuffix(buf.String(), "\n")
}

func commerceReadme(p *core.Project, t Template) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s — backend\n\n", p.Name)
	b.WriteString("Generated and monitored by **Backplane** (Safi Solutions). Template: " + t.Name + ".\n\n")
	b.WriteString("## How it works\n\n```\n")
	for i, s := range t.Flow {
		if i > 0 {
			b.WriteString("      ↓\n")
		}
		b.WriteString(s + "\n")
	}
	b.WriteString("```\n\n")
	b.WriteString(`## Endpoints

| Method | Path | What it does |
| --- | --- | --- |
| GET / POST | /checkout | Creates a Stripe Checkout Session and redirects the customer (or returns JSON with ` + "`Accept: application/json`" + `). |
| GET | /thanks | Thank-you page after payment. |
| POST | /stripe/webhook | Verifies Stripe's signature, records the order once, issues a signed download link, sends the email. Refunds revoke access. |
| GET | /download?t=… | Streams the file from private R2 storage if the signed link is valid, unexpired and not refunded. |
| POST | /links | Emails fresh download links to a past customer (rate limited, never reveals whether an email has orders). |
| POST | /license/validate | Checks a license key (License Server template). |
| POST | /resend/webhook | Records delivery, bounce and complaint events (Svix signature verified). |
| GET | /__backplane/health | Health report for Backplane (requires the probe token). |

## Layout

- ` + "`worker/src/index.js`" + ` — the Cloudflare Worker.
- ` + "`worker/wrangler.jsonc`" + ` — bindings and settings (no secrets).
- ` + "`supabase/migrations/`" + ` — tables, indexes and row-level security.
- ` + "`emails/`" + ` — the purchase email (also published as a Resend template).
- ` + "`.github/workflows/deploy.yml`" + ` — deploys the Worker on every push to main.

## Secrets

Secrets never live in this repository. Backplane stores them encrypted on the owner's computer and sets them directly on
Cloudflare (Worker secrets) and GitHub (encrypted Actions secrets).

## Editing

You can edit anything. Backplane notices changed files, marks them **USER MODIFIED** and will not overwrite them
without asking.
`)
	return b.String()
}
