(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const polish=document.createElement('style');polish.textContent=`
.budget-bars i{transform-origin:left center;transform:scaleX(0);width:100%!important}.check-item p{margin:4px 0 0;color:#75978c;font-size:9px;line-height:1.45}.check-item.done{opacity:.58}.check-item.done b{text-decoration:line-through}.climate-title{padding:12px 13px;border-bottom:1px solid var(--line2)}.climate-title h3{font-size:18px;margin:0 0 4px}.climate-title span{font:500 7px var(--mono);color:#65857a}.climate-month{display:grid;grid-template-columns:34px 1fr 70px;gap:9px;align-items:center;padding:8px 11px;border-bottom:1px solid var(--line2)}.climate-month>span{font:500 7px var(--mono);color:#68897e}.climate-month>b{font:500 9px var(--mono);text-align:right}.temp-track{height:5px;border-radius:99px;background:#14273b;position:relative}.temp-range{position:absolute;top:0;bottom:0;border-radius:99px;background:linear-gradient(90deg,var(--blue),var(--cyan),var(--yellow))}.climate-summary{display:grid;grid-template-columns:repeat(3,1fr);border-top:1px solid var(--line2)}.climate-summary div{padding:10px;text-align:center;border-right:1px solid var(--line2)}.climate-summary div:last-child{border-right:0}.climate-summary span{display:block;font:500 6px var(--mono);color:#65867b}.climate-summary b{display:block;font-size:13px;margin-top:4px}`;document.head.appendChild(polish);
const STORE='movedesk.v2.local';
let lastDestination='';
let essentialsRequest=0;
function read(){try{return JSON.parse(localStorage.getItem(STORE)||'{}')}catch{return{}}}
function write(patch){localStorage.setItem(STORE,JSON.stringify({...read(),...patch}))}

const dateInput=$('#moveDate');
if(dateInput){const saved=read().moveDate;if(saved)dateInput.value=saved;dateInput.addEventListener('change',()=>{write({moveDate:dateInput.value});renderCountdown()});renderCountdown()}
function renderCountdown(){if(!dateInput)return;const out=$('#moveCountdown'),phase=$('#movePhase'),bar=$('#moveProgressBar'),txt=$('#moveProgressText');if(!dateInput.value){out.textContent='Set a date';phase.textContent='Build a timeline around your move.';bar.style.width='0%';txt.textContent='Timeline starts when you choose a date.';return}const target=new Date(dateInput.value+'T00:00:00'),now=new Date(),days=Math.round((Date.UTC(target.getFullYear(),target.getMonth(),target.getDate())-Date.UTC(now.getFullYear(),now.getMonth(),now.getDate()))/864e5);let pct=5,msg='Research, quotes and budget first.';if(days<=56){pct=15;msg='Lock the budget and shortlist movers.'}if(days<=42){pct=28;msg='Book movers, start records and address prep.'}if(days<=28){pct=45;msg='Utilities, packing and official changeovers.'}if(days<=14){pct=65;msg='Confirm reservations and finish core packing.'}if(days<=7){pct=82;msg='Final confirmations, essentials box and travel plan.'}if(days<=2){pct=94;msg='Move window: keep documents and essentials accessible.'}if(days<=0){pct=100;msg=days===0?'Move day.':'Arrival phase: finish local registrations and setup.'}out.textContent=days>0?`${days} day${days===1?'':'s'} to go`:days===0?'Move day':`${Math.abs(days)} days since move`;phase.textContent=msg;bar.style.width=pct+'%';txt.textContent=`Time window only ∙ See the action plan for completed tasks`}
setInterval(renderCountdown,3600000);

const savedPrep=read().prep||{};$$('[data-prep]').forEach(x=>{x.checked=!!savedPrep[x.dataset.prep];x.addEventListener('change',()=>{const p={...read().prep,[x.dataset.prep]:x.checked};write({prep:p})})});

async function loadEssentials(loc){const q=loc?`${loc.latitude},${loc.longitude}`:'';if(!q||q===lastDestination)return;lastDestination=q;const request=++essentialsRequest;const status=$('#essentialsStatus');if(status){status.textContent='LOADING';status.style.color=''};['essentialHospitals','essentialSchools','essentialGrocery','essentialParks','essentialPharmacy','essentialFuel'].forEach(id=>{const e=$('#'+id);if(e)e.textContent='…'});try{const lat=Number(loc.latitude).toFixed(5),lon=Number(loc.longitude).toFixed(5),radius=12000;const query=`[out:json][timeout:18];(nwr(around:${radius},${lat},${lon})[amenity=hospital];nwr(around:${radius},${lat},${lon})[amenity=clinic];nwr(around:${radius},${lat},${lon})[amenity=school];nwr(around:${radius},${lat},${lon})[shop=supermarket];nwr(around:${radius},${lat},${lon})[shop=convenience];nwr(around:${radius},${lat},${lon})[leisure=park];nwr(around:${radius},${lat},${lon})[amenity=pharmacy];nwr(around:${radius},${lat},${lon})[amenity=fuel];);out tags center;`;const r=await fetch('https://overpass-api.de/api/interpreter?data='+encodeURIComponent(query));if(!r.ok)throw new Error('OpenStreetMap data unavailable');const j=await r.json();if(request!==essentialsRequest)return;const c={hospital:0,school:0,grocery:0,park:0,pharmacy:0,fuel:0};(j.elements||[]).forEach(x=>{const t=x.tags||{};if(t.amenity==='hospital'||t.amenity==='clinic')c.hospital++;if(t.amenity==='school')c.school++;if(t.shop==='supermarket'||t.shop==='convenience')c.grocery++;if(t.leisure==='park')c.park++;if(t.amenity==='pharmacy')c.pharmacy++;if(t.amenity==='fuel')c.fuel++});$('#essentialHospitals').textContent=c.hospital;$('#essentialSchools').textContent=c.school;$('#essentialGrocery').textContent=c.grocery;$('#essentialParks').textContent=c.park;$('#essentialPharmacy').textContent=c.pharmacy;$('#essentialFuel').textContent=c.fuel;if(status){status.textContent='OSM LIVE';status.style.color='#46d5a0'}}catch(e){if(request!==essentialsRequest)return;lastDestination='';['essentialHospitals','essentialSchools','essentialGrocery','essentialParks','essentialPharmacy','essentialFuel'].forEach(id=>{const el=$('#'+id);if(el)el.textContent='—'});if(status){status.textContent='UNAVAILABLE';status.style.color='#ef5a4b'}}}

window.addEventListener('movedesk:ready',event=>{loadEssentials(event.detail.to);renderCountdown()});
})();
