(() => {
  const D = window.TRADE_DATA;
  if (!D) return;

  const extra = [
    {id:"ohms-law",category:"fundamentals",title:"Ohm's Law",eyebrow:"Electrical Fundamentals",oneLine:"The relationship between voltage, current and resistance: V = I × R.",plain:"Ohm's law is the basic relationship that lets you predict how voltage, resistance and current interact in a simple resistive circuit. If two values are known, the third can be calculated.",analogy:"Pressure, pipe restriction and flow are linked; change one and the others respond.",where:["Control circuits","Heaters","Troubleshooting","Voltage-drop checks"],failures:["Using the formula without understanding the circuit","Applying simple resistance math to loads with significant impedance","Ignoring changes under load"],safety:"Calculations never replace safe measurement and isolation practices.",related:["voltage","current","resistance","power"],lesson:"ohms"},
    {id:"voltage-drop",category:"circuits",title:"Voltage Drop",eyebrow:"Circuit Behavior",oneLine:"Voltage lost across resistance while current is flowing.",plain:"Every conductor and connection has some resistance. When current flows, that resistance produces a voltage difference. Excessive voltage drop is often a sign of undersized conductors, long runs, loose connections or damaged contacts.",analogy:"Pressure falls as water moves through a restrictive pipe or fitting.",where:["Long cable runs","Motor circuits","Control wiring","Loose terminals"],failures:["Hot terminals","Slow contactor pull-in","Motor undervoltage","Intermittent control faults"],safety:"Voltage-drop testing may require energized measurements and must only be done using appropriate procedures and qualifications.",related:["voltage","current","resistance","multimeter"],lesson:"none"},
    {id:"kirchhoff-current",category:"circuits",title:"Kirchhoff's Current Law",eyebrow:"Circuit Behavior",oneLine:"Current entering a junction equals current leaving it.",plain:"Charge does not disappear at a node. In a branching circuit, the current arriving at a junction divides among branches and the branch currents add back together downstream.",analogy:"Traffic splits at an interchange, but the total number of cars is conserved.",where:["Parallel circuits","Control panels","Current analysis","Sensor networks"],failures:["Adding branch currents incorrectly","Assuming equal current in unequal branches"],safety:"Circuit laws describe behavior; they do not determine whether a circuit is safe to approach.",related:["current","series-parallel","ohms-law"],lesson:"series"},
    {id:"kirchhoff-voltage",category:"circuits",title:"Kirchhoff's Voltage Law",eyebrow:"Circuit Behavior",oneLine:"The voltage rises and drops around a closed loop balance to zero.",plain:"Energy added by sources is accounted for by voltage drops across loads and conductors around the loop. This gives technicians a powerful way to reason about what voltage should appear at each point.",analogy:"If you climb 100 feet, the total descent needed to return to the same elevation is 100 feet.",where:["Series circuits","Control loops","Voltage-drop troubleshooting"],failures:["Using ground as an assumed reference without checking","Ignoring multiple sources"],safety:"Know the actual reference points and sources before measuring.",related:["voltage","series-parallel","voltage-drop"],lesson:"series"},
    {id:"frequency",category:"fundamentals",title:"Frequency",eyebrow:"AC Fundamentals",oneLine:"How many AC cycles occur each second, measured in hertz.",plain:"Frequency tells you how quickly an alternating waveform repeats. Utility power is commonly 60 Hz in the U.S.; VFDs intentionally vary frequency to control AC motor speed.",analogy:"Frequency is the tempo of an electrical waveform.",where:["AC power","VFD outputs","Generators","Timing systems"],failures:["Wrong motor speed","Generator frequency instability","VFD parameter errors"],safety:"Variable-frequency outputs can behave differently from utility sine waves and require appropriate instruments.",related:["ac-dc","vfd","motor-basics","three-phase"],lesson:"wave"},
    {id:"rms",category:"fundamentals",title:"RMS Voltage",eyebrow:"AC Fundamentals",oneLine:"A way to express AC voltage by its equivalent heating effect compared with DC.",plain:"AC voltage is constantly changing. RMS gives a useful effective value. A 120 V RMS sine wave has a peak magnitude around 170 V even though the meter commonly displays about 120 V.",analogy:"RMS is a useful 'work-equivalent' rating for a waveform that is always moving.",where:["AC meters","Power calculations","Waveform analysis"],failures:["Confusing peak and RMS values","Assuming distorted waveforms are always measured correctly by basic meters"],safety:"Peak voltage can be substantially greater than the familiar RMS number.",related:["ac-dc","frequency","multimeter"],lesson:"wave"},
    {id:"capacitance",category:"fundamentals",title:"Capacitance",eyebrow:"Electrical Fundamentals",oneLine:"The ability to store energy in an electric field.",plain:"A capacitor stores separated electric charge. In circuits it can smooth DC supplies, provide motor phase shift, filter noise and create timing behavior.",analogy:"A flexible pressure tank that briefly stores energy and releases it later.",where:["DC buses","Motor capacitors","Power supplies","Filters"],failures:["Bulging or leaking capacitor","Loss of capacitance","Shorted dielectric","Stored charge after shutdown"],safety:"Capacitors can retain dangerous voltage after power is removed. Discharge and verify according to equipment procedures.",related:["power-supply","vfd","ac-dc"],lesson:"none"},
    {id:"inductance",category:"fundamentals",title:"Inductance",eyebrow:"Electrical Fundamentals",oneLine:"The tendency of a magnetic field to oppose changes in current.",plain:"Current through a coil builds a magnetic field. When current changes, the changing field creates a voltage that opposes that change. This behavior appears in motors, transformers, relays and solenoids.",analogy:"Electrical inertia: current through an inductor does not want to change instantly.",where:["Coils","Motors","Transformers","Contactors"],failures:["Inductive voltage spikes","Coil overheating","Shorted turns"],safety:"Opening inductive circuits can produce high transient voltage.",related:["coil","transformer","relay","motor-basics"],lesson:"relay"},
    {id:"impedance",category:"fundamentals",title:"Impedance",eyebrow:"AC Fundamentals",oneLine:"The total opposition an AC circuit presents to current.",plain:"Impedance includes ordinary resistance plus the frequency-dependent effects of inductance and capacitance. It explains why many AC loads cannot be understood using resistance alone.",analogy:"A road can resist traffic because it is narrow, but traffic timing and storage can add additional effects too.",where:["Motors","Transformers","AC coils","Filters"],failures:["Using DC resistance as the only indicator of AC behavior","Ignoring frequency"],safety:"Use equipment-specific test methods when evaluating AC components.",related:["resistance","inductance","capacitance","frequency"],lesson:"none"},
    {id:"conductor-size",category:"components",title:"Conductors + Wire Size",eyebrow:"Components",oneLine:"Conductor material and cross-sectional area determine current capacity and voltage drop.",plain:"Larger conductors have lower resistance and can generally carry more current with less heating. Actual sizing depends on insulation, temperature, installation method, code rules and the load.",analogy:"A larger pipe can move more water with less restriction.",where:["Machine wiring","Feeders","Motor circuits","Control panels"],failures:["Overheating","Excessive voltage drop","Damaged insulation","Loose strands"],safety:"Conductor sizing and installation must follow applicable electrical codes and equipment requirements.",related:["current","resistance","voltage-drop","breaker"],lesson:"none"},
    {id:"terminal-block",category:"components",title:"Terminal Block",eyebrow:"Components",oneLine:"A structured connection point used to join and organize conductors.",plain:"Terminal blocks give field wiring a maintainable landing point inside panels. Good labeling and terminal organization make testing and service much faster.",analogy:"A train station where wires arrive, connect and continue in an organized way.",where:["Control panels","Junction boxes","PLC cabinets","Marshalling panels"],failures:["Loose terminal","Wrong wire landed","Corrosion","Damaged ferrule"],safety:"A terminal may remain energized from another source even when nearby devices are off.",related:["control-circuit","plc-inputs","voltage-drop"],lesson:"none"},
    {id:"disconnect",category:"components",title:"Disconnect Switch",eyebrow:"Components",oneLine:"A switching device intended to visibly or functionally isolate equipment from its power source.",plain:"Disconnects provide a defined means to remove power from equipment for service or emergency control. Some are fused and some are non-fused.",analogy:"The equipment's main gate between the source and the machine.",where:["Machine feeds","HVAC equipment","Motor circuits","Industrial panels"],failures:["Burned blades","Loose lugs","Mechanical binding","Incorrect fuse size"],safety:"A disconnect position is not proof of absence of voltage; verification is still required.",related:["breaker","fuse","safety-loto","grounding"],lesson:"none"},
    {id:"pushbutton",category:"components",title:"Pushbutton",eyebrow:"Components",oneLine:"A manually operated momentary control device.",plain:"Pushbuttons usually change contact state only while pressed. START buttons are commonly normally open; STOP buttons are commonly normally closed in traditional control circuits.",analogy:"A temporary human command to the control circuit.",where:["Motor starters","Operator stations","Machine panels"],failures:["Worn contact block","Stuck actuator","Broken wire","Wrong contact arrangement"],safety:"A pushbutton may command dangerous automatic motion; use required safeguards.",related:["control-circuit","seal-in","normally-open","normally-closed"],lesson:"starter"},
    {id:"selector-switch",category:"components",title:"Selector Switch",eyebrow:"Components",oneLine:"A maintained operator switch used to choose operating modes or states.",plain:"Selector switches commonly choose HAND/AUTO, LOCAL/REMOTE, FORWARD/REVERSE or similar modes. Multiple contact blocks can change several circuit conditions at once.",analogy:"A physical mode selector for the machine's control logic.",where:["Control stations","MCC doors","Machine panels"],failures:["Loose knob","Failed contact block","Mode label mismatch","Mechanical wear"],safety:"Changing modes can bypass normal automatic sequences or initiate movement.",related:["control-circuit","interlock","plc-inputs"],lesson:"none"},
    {id:"solenoid",category:"components",title:"Solenoid",eyebrow:"Components",oneLine:"An electromagnetic actuator that converts coil current into linear movement.",plain:"A solenoid coil creates a magnetic field that pulls or pushes a plunger. In industry, solenoids commonly shift pneumatic or hydraulic valves.",analogy:"An electrical command turns into a short mechanical push or pull.",where:["Valve manifolds","Door locks","Hydraulic valves","Pneumatic valves"],failures:["Open coil","Stuck plunger","Wrong voltage","Mechanical contamination"],safety:"Energizing a solenoid can immediately move fluid-powered equipment.",related:["coil","plc-outputs","relay"],lesson:"relay"},
    {id:"aux-contact",category:"components",title:"Auxiliary Contact",eyebrow:"Components",oneLine:"A low-power contact mechanically linked to a contactor, relay or breaker state.",plain:"Auxiliary contacts report or reuse the mechanical state of another device. They are used for seal-in circuits, interlocks, PLC feedback and status indication.",analogy:"A small feedback switch that moves whenever the main device moves.",where:["Motor starters","Contactors","Breakers","Interlocks"],failures:["Pitted contact","Mechanical mismatch","Wrong NO/NC block","Loose wiring"],safety:"Auxiliary status does not prove the main power poles are safe to touch.",related:["contactor","seal-in","interlock","plc-inputs"],lesson:"starter"},
    {id:"control-transformer",category:"power",title:"Control Transformer",eyebrow:"Power",oneLine:"A transformer used to create a lower control voltage from a higher machine supply.",plain:"Control transformers commonly step machine line voltage down to a control voltage such as 120 VAC. They electrically separate and adapt the control circuit from the power circuit.",analogy:"A dedicated voltage gearbox for the machine's control system.",where:["Motor starters","Machine panels","Legacy control circuits"],failures:["Blown primary fuse","Blown secondary fuse","Open winding","Wrong tap"],safety:"Both primary and secondary circuits can remain hazardous and may be separately protected.",related:["transformer","control-circuit","fuse","power-supply"],lesson:"transformer"},
    {id:"mcc",category:"power",title:"Motor Control Center (MCC)",eyebrow:"Power Distribution",oneLine:"A lineup that groups motor feeders, starters, drives and protection into modular sections.",plain:"An MCC centralizes power distribution and motor control. Individual buckets can contain breakers or fuses, contactors, overloads, control power and sometimes VFDs or soft starters.",analogy:"An apartment building for industrial motor-control circuits.",where:["Factories","Water plants","Process facilities","Large mechanical systems"],failures:["Loose bus connections","Bucket contact wear","Control power faults","Overheating"],safety:"MCCs can contain very high available fault energy. Only qualified personnel should work inside energized equipment.",related:["motor-starter","breaker","contactor","vfd"],lesson:"none"},
    {id:"phase-sequence",category:"power",title:"Phase Sequence",eyebrow:"Three-Phase Power",oneLine:"The order in which the three phase waveforms reach their peaks.",plain:"Swapping any two phases reverses phase sequence and normally reverses a three-phase motor's rotation direction.",analogy:"Three people pushing around a wheel in one order make it spin one way; reverse two people and the direction reverses.",where:["Motor commissioning","Generators","Transfer systems"],failures:["Pump running backward","Fan airflow reversed","Machine rotation wrong"],safety:"Rotation checks must account for mechanical hazards and machine procedures.",related:["three-phase","motor-basics","reversing-starter"],lesson:"wave"},
    {id:"phase-loss",category:"power",title:"Phase Loss",eyebrow:"Three-Phase Power",oneLine:"Loss of one phase in a three-phase supply or motor circuit.",plain:"A running motor that loses one phase can continue turning while drawing damaging current in the remaining phases. A stopped motor may fail to start and simply hum or trip protection.",analogy:"A three-person team suddenly loses one member but the remaining two are forced to carry the load.",where:["Motor circuits","Fuses","Contactors","Loose terminals"],failures:["Overheating","Low torque","Current imbalance","Overload trip"],safety:"Phase-loss troubleshooting may involve hazardous three-phase systems.",related:["three-phase","motor-basics","overload","fuse"],lesson:"motor"},
    {id:"motor-nameplate",category:"motors",title:"Motor Nameplate",eyebrow:"Motors",oneLine:"The motor's operating identity: voltage, current, frequency, speed, power, service factor and more.",plain:"The nameplate tells you what electrical and mechanical conditions the motor was designed for. It is one of the first references when checking supply voltage, overload settings, VFD parameters or expected speed.",analogy:"The motor's passport and operating limits printed on its body.",where:["Every industrial motor"],failures:["Wrong voltage connection","Wrong overload setting","Incorrect VFD base frequency","Misread FLA"],safety:"Nameplate data does not indicate whether the motor is presently de-energized.",related:["motor-basics","overload","vfd","three-phase"],lesson:"motor"},
    {id:"motor-slip",category:"motors",title:"Motor Slip",eyebrow:"Motors",oneLine:"The difference between synchronous magnetic-field speed and actual induction-motor rotor speed.",plain:"An induction motor must run slightly slower than the rotating magnetic field to induce rotor current and produce torque. As load increases, slip generally increases.",analogy:"The magnetic field stays just ahead of the rotor and keeps pulling it forward.",where:["Induction motors","Speed diagnostics","Load analysis"],failures:["Excessive slip from overload","Unexpected speed from wrong frequency","Mechanical drag"],safety:"Speed observations must be made without exposure to rotating hazards.",related:["motor-basics","frequency","vfd","motor-nameplate"],lesson:"motor"},
    {id:"reversing-starter",category:"motors",title:"Reversing Starter",eyebrow:"Motor Controls",oneLine:"Two interlocked contactors that reverse a three-phase motor by swapping two phases.",plain:"A reversing starter uses forward and reverse contactors wired with two phases exchanged. Electrical and mechanical interlocks prevent both contactors from closing at the same time.",analogy:"Two mutually exclusive power paths: one spins forward, the other swaps phase order and spins backward.",where:["Conveyors","Hoists","Machine axes","Fans"],failures:["Failed interlock","Welded contactor","Wrong phase wiring","Control logic fault"],safety:"Simultaneous forward/reverse contactor closure can create a severe fault.",related:["contactor","interlock","phase-sequence","motor-starter"],lesson:"starter"},
    {id:"safety-relay",category:"controls",title:"Safety Relay",eyebrow:"Safety Controls",oneLine:"A monitored control device designed for safety functions such as E-stops and guard circuits.",plain:"Safety relays use redundant channels, monitoring and controlled reset behavior to detect certain wiring or component faults rather than relying on a single ordinary relay contact.",analogy:"A control circuit that checks itself instead of blindly trusting one switch.",where:["E-stops","Guard switches","Safety mats","Light curtains"],failures:["Channel discrepancy","Reset fault","Feedback loop open","Wiring fault"],safety:"Safety circuit design requires standards-based risk assessment and qualified design practices.",related:["interlock","emergency-stop","control-circuit"],lesson:"none"},
    {id:"emergency-stop",category:"controls",title:"Emergency Stop",eyebrow:"Safety Controls",oneLine:"A manually actuated emergency function intended to stop hazardous machine operation quickly.",plain:"An E-stop is part of a complete safety function. The mushroom button is only the operator device; downstream safety logic, contactors, monitoring and reset behavior determine the actual safety performance.",analogy:"The big red button is the request; the safety system is what makes the request trustworthy.",where:["Machinery","Conveyors","Cells","Operator stations"],failures:["Bypassed contact","Single-channel wiring","Failed reset logic","Contactor feedback fault"],safety:"E-stops are not substitutes for lockout/tagout during servicing.",related:["safety-relay","interlock","safety-loto"],lesson:"none"},
    {id:"hmi",category:"plc",title:"HMI",eyebrow:"Automation",oneLine:"A human-machine interface that displays process information and sends operator commands to a control system.",plain:"HMIs show status, alarms, trends, setpoints and controls. They usually communicate with a PLC or controller rather than directly switching field loads.",analogy:"The machine's dashboard and touchscreen controls.",where:["Operator panels","SCADA systems","Packaging machines","Process equipment"],failures:["Communication loss","Stale data","Wrong tag mapping","Unauthorized setpoint change"],safety:"An HMI indication is not proof of safe energy state.",related:["plc","plc-inputs","plc-outputs"],lesson:"scan"},
    {id:"analog-signals",category:"plc",title:"Analog Signals",eyebrow:"Automation",oneLine:"Continuous electrical values used to represent changing measurements and commands.",plain:"Unlike a simple ON/OFF input, an analog signal represents a range. Common industrial standards include 0–10 V and 4–20 mA.",analogy:"Digital is a light switch; analog is a dimmer knob.",where:["Pressure transmitters","Speed references","Temperature transmitters","Valve position"],failures:["Scaling error","Open loop","Noise","Ground loop"],safety:"Know whether the signal is isolated and what other energy exists in the field device.",related:["plc-inputs","4-20ma","hmi"],lesson:"none"},
    {id:"4-20ma",category:"plc",title:"4–20 mA Loop",eyebrow:"Automation",oneLine:"A robust analog current-loop standard where 4 mA represents the low end and 20 mA the high end.",plain:"Current loops tolerate voltage drop over long wiring runs better than simple voltage signals. The 4 mA live zero also helps distinguish a valid zero reading from some open-circuit faults.",analogy:"The measurement is encoded in how much current continuously circulates around the loop.",where:["Pressure","Level","Flow","Temperature transmitters"],failures:["Open loop","Wrong scaling","Insufficient loop supply","Grounding issue"],safety:"Some loops enter hazardous areas and may use intrinsic-safety barriers; follow system-specific procedures.",related:["analog-signals","plc-inputs","multimeter"],lesson:"none"},
    {id:"sinking-sourcing",category:"plc",title:"Sinking vs Sourcing I/O",eyebrow:"Automation",oneLine:"Describes which side of a DC circuit provides current and which side returns it.",plain:"In DC automation wiring, sourcing devices provide positive current to a load while sinking devices provide a path toward the negative/common side. PLC input and sensor compatibility depends on the circuit arrangement.",analogy:"One side supplies the water; the other side opens the drain path.",where:["24 VDC PLC inputs","Sensors","Transistor outputs"],failures:["Input LED never turns on","Wrong common wiring","PNP/NPN mismatch"],safety:"Verify voltage polarity and device wiring diagrams before connecting I/O.",related:["plc-inputs","proximity-sensor","pnp-npn"],lesson:"sensor"},
    {id:"pnp-npn",category:"sensors",title:"PNP vs NPN Sensor Output",eyebrow:"Sensors",oneLine:"Two common transistor-output arrangements used by DC sensors.",plain:"A PNP sensor commonly switches positive voltage to the input; an NPN sensor commonly switches the load toward 0 V. The PLC input common must be wired to suit the chosen sensor type.",analogy:"Both sensors answer the same question, but they hand the electrical signal to the PLC from opposite sides of the circuit.",where:["Proximity sensors","Photoeyes","PLC inputs"],failures:["Sensor LED works but PLC never sees input","Wrong input common","Mixed wiring standards"],safety:"Always follow the exact device wiring diagram; color codes can vary by device and standard.",related:["proximity-sensor","plc-inputs","sinking-sourcing"],lesson:"sensor"},
    {id:"encoder",category:"sensors",title:"Encoder",eyebrow:"Sensors",oneLine:"A sensor that converts shaft or linear motion into position or speed information.",plain:"Incremental encoders produce pulse trains as motion occurs; absolute encoders report a unique position code. PLCs and drives use encoder feedback for speed, position and motion control.",analogy:"A digital odometer attached directly to motion.",where:["Conveyors","Servo systems","Machine axes","Length measurement"],failures:["Loose coupling","Missing pulses","Noise","Wrong scaling"],safety:"Rotating encoder couplings and machine shafts require guarding and safe service procedures.",related:["plc-inputs","vfd","counter"],lesson:"sensor"},
    {id:"soft-starter",category:"drives",title:"Soft Starter",eyebrow:"Drives",oneLine:"An electronic motor starter that reduces voltage during acceleration to limit starting current and torque.",plain:"Soft starters use solid-state switching to ramp motor voltage during startup and sometimes stopping. Unlike a VFD, they normally do not continuously control motor speed once bypassed or at full voltage.",analogy:"Ease the motor onto full power instead of slamming the switch closed.",where:["Pumps","Fans","Conveyors","Large motors"],failures:["Overtemperature","SCR fault","Bypass contactor fault","Ramp too long"],safety:"Power electronics can retain voltage and may not provide isolation.",related:["motor-starter","vfd","motor-basics"],lesson:"motor"},
    {id:"dc-bus",category:"drives",title:"VFD DC Bus",eyebrow:"Drives",oneLine:"The internal DC energy link between a VFD's rectifier and inverter stages.",plain:"Incoming AC is rectified to DC and stored on bus capacitors. The inverter then switches this DC to synthesize variable-frequency motor voltage.",analogy:"A temporary energy reservoir between the incoming power and the electronically created motor output.",where:["Inside VFDs","Regenerative systems"],failures:["Bus overvoltage","Undervoltage","Failed capacitor","Braking fault"],safety:"The DC bus can remain at hazardous voltage after input power is removed. Observe discharge times and verify.",related:["vfd","capacitance","frequency"],lesson:"motor"},
    {id:"clamp-meter",category:"diagnostics",title:"Clamp Meter",eyebrow:"Diagnostics",oneLine:"Measures current by sensing the magnetic field around a conductor without opening the circuit.",plain:"A clamp meter surrounds one conductor and measures its magnetic field. Clamping around both outgoing and returning conductors often causes the fields to cancel.",analogy:"Measure the traffic in one lane by sensing its magnetic signature without cutting the road.",where:["Motor current","Load checks","Current imbalance","Troubleshooting"],failures:["Clamping multiple conductors","Wrong AC/DC mode","Poor jaw closure"],safety:"Use an appropriately rated meter and maintain required approach and PPE practices.",related:["current","multimeter","three-phase"],lesson:"meter"},
    {id:"insulation-resistance",category:"diagnostics",title:"Insulation Resistance Test",eyebrow:"Diagnostics",oneLine:"Applies a controlled DC test voltage to evaluate insulation resistance between conductors and ground or other windings.",plain:"An insulation-resistance tester can reveal moisture, contamination and insulation deterioration that an ordinary low-voltage ohmmeter may not expose.",analogy:"Stress-test the electrical insulation to see whether it leaks under a controlled test voltage.",where:["Motors","Cables","Transformers","Heaters"],failures:["Low insulation resistance","Moisture","Contamination","Damaged winding"],safety:"Equipment must be isolated, discharged and checked for connected electronics before insulation testing.",related:["multimeter","motor-basics","transformer"],lesson:"none"},
    {id:"current-transformer",category:"diagnostics",title:"Current Transformer (CT)",eyebrow:"Diagnostics + Power",oneLine:"Produces a scaled current proportional to a larger primary current for metering or protection.",plain:"A CT lets instruments safely monitor large AC current. The conductor through the core acts as a primary winding; the secondary feeds a meter or protective relay.",analogy:"A current gearbox that makes a huge primary current measurable at a smaller scale.",where:["Power meters","Protection relays","MCCs","Energy monitoring"],failures:["Wrong polarity","Wrong ratio","Open secondary","Loose terminal"],safety:"A CT secondary must not be casually opened while primary current flows; dangerous voltage can develop.",related:["current","three-phase","clamp-meter"],lesson:"transformer"},
    {id:"thermal-imaging",category:"diagnostics",title:"Thermal Imaging",eyebrow:"Diagnostics",oneLine:"Uses infrared temperature patterns to find abnormal heating without touching the component.",plain:"Electrical faults often create heat before they fail completely. Thermal imaging can reveal overloaded conductors, loose connections, unbalanced phases and failing contacts when equipment is under load.",analogy:"See electrical stress as a heat map.",where:["Panels","MCCs","Bus joints","Bearings","Transformers"],failures:["Hot connection","Overloaded phase","Failed contact","Poor cooling"],safety:"Infrared inspections around energized equipment still require electrical safe-work practices.",related:["voltage-drop","contactor","three-phase"],lesson:"none"},
    {id:"arc-flash",category:"safety",title:"Arc Flash",eyebrow:"Electrical Safety",oneLine:"A rapid release of thermal and pressure energy caused by an electrical arc fault.",plain:"An arc flash can create extreme heat, molten metal, pressure and intense light. Hazard severity depends on system voltage, available fault current, clearing time, working distance and other factors.",analogy:"Not simply a shock hazard: an electrical fault can become a violent energy-release event.",where:["Switchgear","MCCs","Panels","Industrial distribution"],failures:["Dropped conductive object","Insulation failure","Loose connection","Incorrect work practice"],safety:"Arc-flash risk assessment, boundaries, PPE and work methods must follow applicable regulations and facility procedures.",related:["breaker","disconnect","safety-loto","grounding"],lesson:"none"},
    {id:"stored-energy",category:"safety",title:"Stored Energy",eyebrow:"Electrical Safety",oneLine:"Energy that remains after the obvious power source has been disconnected.",plain:"Capacitors, rotating equipment, springs, gravity, pressure and thermal systems can all retain energy after shutdown. Safe servicing requires identifying and controlling every energy form.",analogy:"Turning off the faucet does not empty a pressure tank that is already charged.",where:["VFDs","Power supplies","Motors","Hydraulics","Pneumatics"],failures:["Unexpected restart","Capacitor discharge","Coast-down motion","Released pressure"],safety:"Stored-energy control is a core part of effective lockout/tagout.",related:["safety-loto","capacitance","vfd"],lesson:"none"}
  ];

  const existing = new Set(D.concepts.map(c=>c.id));
  extra.forEach(c=>{ if(!existing.has(c.id)) D.concepts.push(c); });

  const overrides = {
    rms:{why:"RMS is the effective value of an AC waveform for heating and power calculations. Most meters display RMS for sine waves; distorted waveforms can cause average-responding meters to lie.",steps:["Know whether the meter is true-RMS or average-responding.","For a clean sine wave, peak is about 1.414 × RMS.","Use RMS values for power and most nameplate comparisons.","When the waveform is distorted (VFDs, non-linear loads), prefer true-RMS instruments."],recognize:["Panel meters and multimeters usually show the RMS value for AC voltage and current.","Nameplates list RMS voltages (120 V, 208 V, 480 V, etc.).","A pure sine wave at 120 V RMS reaches roughly ±170 V peak."],verify:["Confirm the meter mode is AC and the instrument is appropriate for the waveform.","Compare the displayed value with expected system voltage under the same load conditions.","If readings and equipment behavior disagree, check for peak vs RMS confusion or a non-true-RMS meter on a distorted waveform."],failures:["Confusing peak and RMS values","Assuming every AC meter is true-RMS","Using a basic meter on heavily distorted waveforms from VFDs or electronic loads"],misconceptions:["The number on the meter is not always the peak value.","A distorted waveform can make an average-responding meter read low even when the true RMS heating effect is higher."],fieldScenario:"A VFD-fed motor circuit shows lower-than-expected voltage on a basic meter while the motor runs hot. The issue may be measurement method on a non-sinusoidal waveform rather than an actual low supply."},
    voltage:{why:"Nearly every electrical diagnosis starts by asking where voltage exists, where it should exist, and where it disappears. Understanding voltage as a difference between two points prevents one of the most common beginner mistakes: thinking a wire simply 'has voltage' by itself.",steps:["Choose two reference points. Voltage only exists as a difference between them.","A source separates charge and creates electrical potential.","When a complete path is available, that potential can drive current through a load.","Loads and unwanted resistance consume portions of the source voltage as measurable voltage drops."],recognize:["Meters read voltage between two probes, never at only one point.","Control schematics often label expected voltages such as 24 VDC, 120 VAC or 480 VAC.","A normal open switch may show full source voltage across its two terminals; a healthy closed switch should show very little voltage across itself under load."],verify:["First decide what two points you are comparing and what voltage you expect.","Use the correct AC/DC meter mode and an appropriately rated instrument.","Compare source voltage, then progressively measure through the circuit to locate the point where the expected potential is lost."],fieldScenario:"A contactor will not pull in. You measure 24 VDC at the power supply but only 7 V at the coil while the START circuit is commanded. That tells you the problem is not simply 'no voltage'; something upstream is dropping most of it under load.",misconceptions:["Voltage is not current. You can measure voltage with almost no current flowing.","Ground is not magically zero everywhere; it is a reference point whose meaning depends on the system."],check:{q:"A normally open switch is open in a 24 VDC series control circuit. What would you typically expect to measure directly across that open switch?",options:["About 0 V","About the source voltage","Infinite current","Exactly half the source voltage"],answer:1,explain:"With no current flowing, most or all of the source potential can appear across the open point."}},
    current:{why:"Current tells you how hard the circuit is actually working. It is especially valuable for motors and heaters because abnormal current often reveals overload, phase loss, mechanical drag or a shorted condition.",steps:["Voltage creates the potential to move charge.","A complete path allows charge to circulate through the load.","The load's impedance determines how much current the source drives.","That same series-path current produces heating and magnetic effects in conductors and equipment."],recognize:["Motor nameplates list full-load current or amps.","Overloads and breakers respond to current, but they protect against different conditions and on different time scales.","Current is measured through a path, not simply from one point to ground."],verify:["Use a clamp meter around one conductor when possible for a non-invasive current reading.","Compare all three motor phases instead of only one.","Compare measured current with expected load and nameplate data."],fieldScenario:"A three-phase motor sounds weak. Two phases measure 8 A and one phase reads almost zero. That pattern points you toward a missing phase or open path rather than a simple mechanical overload.",misconceptions:["A load does not 'use up' current in a series circuit; the same current flows through each series element.","More voltage does not always mean proportionally more current in complex AC loads."],check:{q:"To measure current with a clamp meter on a single-phase load, what should the jaw normally surround?",options:["Both supply conductors together","One current-carrying conductor","The equipment enclosure","The ground conductor only"],answer:1,explain:"Clamping one conductor lets the meter sense its magnetic field; surrounding outgoing and returning conductors can cancel the fields."}},
    contactor:{why:"Contactors are everywhere in industrial and HVAC control. If you can separate the control side from the power side in your head, motor starters and machine controls become dramatically easier to understand.",steps:["Control voltage is applied to the coil terminals.","The energized coil creates a magnetic field and pulls the armature inward.","The armature mechanically closes the main power contacts and changes auxiliary contacts.","Removing coil power lets the return spring reopen the contacts."],recognize:["Main line/load terminals are physically larger because they carry load current.","Coil terminals are typically marked separately, often A1 and A2.","Auxiliary contact blocks may be attached to the front or side and are rated for control current rather than motor current."],verify:["Determine the coil's rated voltage before testing.","When the contactor should be energized, compare actual coil voltage with its rating.","If coil voltage is correct but the contactor does not move, investigate the coil/mechanism; if it moves but the load does not receive power, investigate main contacts and line/load conditions."],fieldScenario:"A compressor contactor chatters rapidly. The coil is rated 24 VAC, but the voltage collapses to 15 VAC whenever it pulls in. The symptom suggests the contactor may be reacting to weak control voltage rather than being the original cause.",misconceptions:["A contactor is not the same thing as an overload relay; the contactor switches, the overload protects against sustained motor overcurrent.","A de-energized coil does not guarantee the line terminals are de-energized."],check:{q:"The contactor coil has its correct rated voltage but the armature never pulls in. Which area becomes the strongest suspect?",options:["The source frequency only","The coil or mechanical mechanism","The downstream motor bearings only","The PLC program must be correct"],answer:1,explain:"If the correct coil voltage is present, the command path has reached the contactor. The coil/mechanism becomes a primary suspect."}},
    relay:{why:"Relays teach the core idea behind industrial control: one electrical circuit can make decisions about another circuit without carrying the same load current.",steps:["Current flows through the relay coil.","The coil creates a magnetic field.","A mechanical armature changes the relay's NO and NC contacts.","Those contacts can signal another circuit, PLC input or load."],recognize:["Socket-mounted ice-cube relays commonly show a printed contact diagram.","Coil voltage is printed separately from contact ratings.","Multiple contact sets may change together from one coil."],verify:["Confirm the coil rating and expected command voltage.","Check whether the coil energizes and whether the expected contact changes state.","With power safely removed, continuity testing can help verify contact behavior."],fieldScenario:"A PLC output LED turns on but a solenoid never receives power. The PLC drives an interposing relay. The relay coil energizes, but its output contact is burned open, separating the PLC logic from the field-side fault.",misconceptions:["The coil circuit and contact circuit can be completely different voltages.","Normally open/closed describes the de-energized state of the relay, not what you want the machine to do."],check:{q:"What directly causes a relay's contacts to change state?",options:["The load current flowing through the contacts","Magnetic force from the energized coil","The PLC scan time","Ground current"],answer:1,explain:"The energized coil creates a magnetic field that moves the armature and contact mechanism."}},
    "motor-basics":{why:"Three-phase induction motors drive an enormous portion of industrial equipment. Their current, speed, sound and temperature connect electrical problems to mechanical problems.",steps:["Three AC phase currents create magnetic fields in the stator.","Because the phases are time-shifted, those fields combine into a rotating magnetic field.","The moving field induces current in the rotor and creates torque.","The rotor runs slightly slower than the field so induction and torque can continue."],recognize:["A terminal or junction box is mounted on the motor frame.","The nameplate gives voltage, current, frequency, speed, power and connection information.","Cooling fins and a rear fan help remove heat from many general-purpose motors."],verify:["Compare phase-to-phase voltage before blaming the motor.","Compare current on all phases while running.","Check rotation, mechanical load, vibration, temperature and nameplate values together."],fieldScenario:"A conveyor motor draws high current on all three phases and runs slower than normal. Electrical supply is balanced. That pushes the diagnosis toward mechanical overload, binding or a motor condition rather than a single lost phase.",misconceptions:["An induction motor rotor normally does not run exactly at synchronous speed.","A motor overload and a branch-circuit short-circuit protective device solve different problems."],check:{q:"Why does an induction motor normally run slightly below synchronous speed?",options:["To create the relative motion needed for rotor induction and torque","Because one phase is always missing","Because the bearings intentionally slip","Because the VFD always limits it"],answer:0,explain:"The rotor must lag the rotating magnetic field so relative motion continues to induce rotor current and produce torque."}},
    plc:{why:"Once you understand the PLC as a repeating input → logic → output machine, automation stops looking like magic. Troubleshooting becomes a question of finding which layer disagrees with reality.",steps:["Field devices create electrical input states.","Input modules convert those states into data the PLC can read.","The processor executes logic using those input states and internal data.","Output modules translate program decisions back into electrical signals for field devices."],recognize:["PLC racks often have a CPU plus input/output modules with channel LEDs.","Module labels separate input addresses from output addresses.","Network ports connect PLCs to HMIs, drives and remote I/O."],verify:["Start with the real-world symptom, then compare the field device, module LED, software tag and program condition.","For an output problem, distinguish 'logic says ON' from 'output module actually sends voltage' and from 'field load receives voltage.'"],fieldScenario:"A photoeye LED changes when boxes pass, but the PLC input bit never changes. That isolates the issue to wiring, input power, common arrangement or the input channel, not the ladder sequence downstream.",misconceptions:["A green output bit on a laptop does not prove the field device has voltage.","PLC logic and physical wiring are two separate layers that must agree."],check:{q:"A sensor LED changes but the PLC input bit never changes. What should you investigate before rewriting ladder logic?",options:["The motor bearings","The sensor-to-input wiring and PLC input channel","The HMI color theme","The VFD acceleration ramp"],answer:1,explain:"The physical signal must reach and be recognized by the input module before program logic can use it."}},
    "ladder-logic":{why:"Ladder logic is easier when read as cause-and-effect rather than as mysterious symbols. Each rung is a logical statement controlling an action or internal state.",steps:["Read the rung from left to right conceptually.","Each condition instruction either allows or blocks logical continuity based on its referenced state.","Branches create OR paths; series conditions create AND relationships.","When the rung evaluates true, the output instruction executes according to its type."],recognize:["XIC / examine-ON symbols look like normally open relay contacts.","XIO / examine-OFF symbols look like normally closed contacts.","Output instructions often appear near the right side of the rung."],verify:["Identify the output that should change.","Work backward through the rung and find the first required condition that is false.","Then determine whether that false condition is correct process logic or evidence of a field/input problem."],fieldScenario:"A MOTOR_RUN rung is false even though START is pressed. Tracing the rung reveals the permissive AIR_PRESSURE_OK bit is false. The ladder has told you what is blocking the command; the next job is proving why that bit is false.",misconceptions:["An XIC symbol does not necessarily mean the physical device is wired normally open.","Green rung highlighting shows logical state, not necessarily field voltage."],check:{q:"In ladder logic, what is the fastest way to diagnose why a simple output rung is false?",options:["Replace the PLC","Work backward and find the first required false condition","Change every XIO to XIC","Force the output immediately"],answer:1,explain:"The first blocking condition tells you which permissive, input or internal state is preventing the rung from becoming true."}},
    vfd:{why:"VFDs combine power electronics, motor theory and control logic. They are common enough that technicians need to understand both their internal energy path and their parameter/fault behavior.",steps:["The rectifier converts incoming AC to DC.","Capacitors smooth and store energy on the DC bus.","Power transistors switch the DC bus rapidly to synthesize a variable-frequency three-phase output.","Changing output frequency changes the motor's rotating magnetic-field speed."],recognize:["Line terminals and motor output terminals are separated and labeled.","A keypad or display shows speed reference, frequency, current and faults.","Cooling fans and heat sinks remove losses from power electronics."],verify:["Read the displayed fault before cycling power when possible.","Check input supply, DC-bus condition if trained/authorized, output command and motor data/parameters.","Separate command problems from power-stage problems from motor/load problems."],fieldScenario:"A conveyor VFD trips overcurrent only during acceleration. The motor checks normal and runs at steady speed. That pattern points toward acceleration time, mechanical breakaway load, motor data or drive sizing rather than a random steady-state fault.",misconceptions:["A stopped VFD output does not mean the DC bus is discharged.","A VFD is not simply a fancy contactor; it actively synthesizes the motor waveform."],check:{q:"Which VFD section sits between the input rectifier and output inverter?",options:["Mechanical overload relay","DC bus","Safety relay","Control transformer secondary only"],answer:1,explain:"The rectifier charges the DC bus; the inverter switches that stored DC to create the variable-frequency motor output."}},
    multimeter:{why:"A meter is only useful when the measurement answers a specific question. The skill is not 'knowing how to turn the dial'; it is choosing a test point that divides the possible faults.",steps:["State what the circuit should be doing.","Choose the electrical quantity that would prove or disprove part of that expectation.","Choose reference points and meter mode deliberately.","Interpret the reading in context, then choose the next measurement based on what you learned."],recognize:["COM is the common lead jack; separate jacks may exist for voltage/resistance and high current.","Meter category and voltage ratings matter for where the meter can safely be used.","Selector positions separate AC voltage, DC voltage, resistance, current and other functions."],verify:["Verify meter operation according to your procedure before relying on an absence-of-voltage reading.","Never measure resistance on an energized circuit.","Never put a current-mode meter directly across a voltage source."],fieldScenario:"A motor-starter coil reads 0 V to common. Instead of replacing the coil, you move one test point upstream through STOP, overload and fuse until 24 V reappears. The fault is between the last good point and first bad point.",misconceptions:["A meter reading is evidence, not an answer by itself.","Continuity beep does not prove a connection will carry load current without excessive voltage drop."],check:{q:"Why can a continuity test pass on a bad connection that still fails in operation?",options:["Continuity uses a very small test current and may not reveal resistance under load","Meters cannot measure resistance","The wire automatically repairs itself","Voltage and current are identical"],answer:0,explain:"A weak or corroded connection can pass a tiny meter current yet develop a large voltage drop when real load current flows."}},
    "diagnostics-method":{why:"Good troubleshooting is an information strategy. The goal is to make each measurement eliminate as many possible causes as possible without changing the system blindly.",steps:["Define the symptom precisely and determine what still works.","Understand the expected sequence using drawings, I/O and machine behavior.","Choose a test point that divides the remaining possibilities into large groups.","Follow the evidence until the failed condition is proven, then verify the repair and root cause."],recognize:["The best next test is the one that changes what you know.","A schematic is a map of expected relationships, not just a wiring picture.","Multiple failures are possible, but assume nothing until evidence demands it."],verify:["Record expected versus actual readings.","Avoid changing several components or parameters at once.","After repair, reproduce the original operating condition and verify the system through a complete cycle."],fieldScenario:"A machine is dead. Instead of checking every component, you first confirm control power at the supply, then at the midpoint of the permissive chain. One reading cuts the possible fault area in half immediately.",misconceptions:["Experienced troubleshooting is not random intuition; it is fast hypothesis testing built on system knowledge.","Replacing a suspected part is not the same as proving the failure."],check:{q:"What makes a troubleshooting measurement especially valuable?",options:["It is taken at the easiest point to reach","It separates many possible causes into different outcomes","It uses the most expensive meter","It always reads zero"],answer:1,explain:"A high-information test quickly narrows the fault region or distinguishes entire groups of causes."}},
    "safety-loto":{why:"Electrical knowledge is useless if a learner treats 'OFF' as the same thing as safe. LOTO teaches the system-level habit of controlling every hazardous energy source and verifying the result.",steps:["Identify all electrical and non-electrical energy sources.","Shut the equipment down using normal controls.","Physically isolate energy and apply locks/tags according to procedure.","Control stored energy and verify isolation before beginning work."],recognize:["Machines can have multiple disconnects and backfeeds.","Hydraulic, pneumatic, gravitational and capacitive energy can remain after electrical shutdown.","Verification is a deliberate step, not an assumption."],verify:["Follow the employer's energy-control procedure and authorized-person requirements.","Verify the correct isolation point and absence of expected energy using approved methods.","Before return to service, ensure guards, personnel, locks and controls are handled according to procedure."],fieldScenario:"A conveyor disconnect is locked out, but its pneumatic stop gate remains pressurized and capable of moving. Electrical isolation alone did not control the machine's complete hazardous energy.",misconceptions:["An E-stop is not lockout/tagout.","A PLC 'OFF' command is not an energy-isolating device."],check:{q:"Which statement best describes lockout/tagout?",options:["Pressing STOP and trusting the PLC","A complete hazardous-energy control process including isolation and verification","Turning off only the main HMI","Removing one control fuse"],answer:1,explain:"LOTO is a process that identifies, isolates, controls and verifies hazardous energy, not merely an operator stop command."}}
  };

  function genericDeep(c){
    const cat = c.category || "";
    const isMeas = /fundamentals|measurement|circuits/.test(cat);
    const isControl = /control|automation|logic/.test(cat);
    const isPower = /motors|power|components/.test(cat);
    return {
      why: c.why || (isMeas
        ? `${c.title} is a measurement concept. Technicians use it to interpret what a meter or waveform is actually telling them about circuit conditions, not as an abstract formula.`
        : isControl
        ? `${c.title} lives in the control layer. Understanding it means knowing when the circuit or program is allowing energy to reach the load and when it is intentionally preventing it.`
        : `${c.title} is part of the physical power or machine path. A technician needs to recognize it on the equipment, understand what it contributes, and know what evidence shows it is working or failing.`),
      steps: c.steps || [
        `State the job of ${c.title.toLowerCase()} in one sentence using the real system, not the textbook definition.`,
        `Name the components immediately upstream and downstream of it.`,
        `List the two or three observations or readings that prove it is performing its job.`,
        `Name the most common way this concept is misdiagnosed in the field.`
      ],
      recognize: c.recognize || (isMeas
        ? [`Find where this quantity is actually measured or displayed on the equipment or instrument.`,`Note the scale, mode, or units the meter or nameplate uses for this value.`,`Compare the reading method with the waveform or circuit type so you do not misinterpret peak, RMS, or average.`]
        : isControl
        ? [`Locate the device, terminal, or program element that represents ${c.title.toLowerCase()}.`,`Identify the signal or condition that turns it on or true, and the load or output it controls.`,`Look for status indicators (LEDs, HMI bits, contact position) that show its real state.`]
        : [`Find the physical hardware associated with ${c.title.toLowerCase()} on the machine or in the panel.`,`Note the nameplate data, terminal markings, or schematic symbols that identify it.`,`Observe its physical condition: heat discoloration, contact wear, connection quality, or unusual sound/vibration.`]),
      verify: c.verify || (isMeas
        ? [`Decide the expected magnitude and units before you measure.`,`Confirm meter function, range, and probe placement match the quantity (AC/DC, voltage/current, peak vs RMS).`,`If the reading conflicts with system behavior, check method and scale before condemning the circuit.`]
        : [`Write the expected normal state before you test.`,`Use one measurement or observation that can separate this concept from the next most likely cause.`,`If evidence conflicts, move one step upstream or downstream rather than swapping parts.`]),
      fieldScenario: c.fieldScenario || `A symptom appears that could involve ${c.title.toLowerCase()}. The technician first confirms the surrounding conditions (power, load, command signal) and then uses a targeted observation or measurement to prove whether this concept is the actual fault or only a downstream effect.`,
      misconceptions: c.misconceptions || [
        `A definition is not the same as knowing how ${c.title.toLowerCase()} behaves under load or during a fault.`,
        `One meter reading or indicator must be interpreted with the rest of the circuit or process.`
      ],
      check: c.check || {q:`What best shows you understand ${c.title}?`,options:["Reciting the one-line definition","Recognizing it, explaining its job, and predicting what changes when it fails","Ignoring related components","Assuming every symptom means this part is bad"],answer:1,explain:"Understanding means connecting the concept to system behavior, recognition, and fault symptoms."}
    };
  }

  D.concepts.forEach(c => {
    const deep = Object.assign(genericDeep(c), overrides[c.id] || {});
    Object.assign(c, deep);
  });

  const asset = (src,caption,credit,license,url) => ({src,caption,credit,license,url});
  D.visualAssets = Object.assign({}, D.visualAssets || {}, {
    contactor:asset("assets/reference/electrical/contactor.jpg","Industrial electromagnetic contactor: real hardware is much more physically substantial than the schematic symbol suggests.","Julo / Wikimedia Commons","Public domain","https://commons.wikimedia.org/wiki/File:Stycznik_przemyslowy.jpg"),
    relay:asset("assets/reference/electrical/contactor_internals.svg","Coil, armature, main contacts, and aux contacts: same ideas as a relay at higher load current.","TradeSchool technical visual","",""),
    coil:asset("assets/reference/electrical/contactor_internals.svg","The coil creates magnetic pull when energized. Wrong coil voltage is a common failure.","TradeSchool technical visual","",""),
    "aux-contact":asset("assets/reference/electrical/contactor_internals.svg","Aux contacts handle seal-in and interlock signals, not motor load current.","TradeSchool technical visual","",""),
    "motor-basics":asset("assets/reference/electrical/three_phase_motor.jpg","Typical three-phase induction motor.","KishanMalaviyaatCHETAK ELECTRICALS / Wikimedia Commons","CC BY-SA 4.0","https://commons.wikimedia.org/wiki/File:Three_Phase_Induction_Motor.jpg"),
    "motor-nameplate":asset("assets/reference/electrical/three_phase_motor.jpg","Three-phase motor with the nameplate visible on the frame.","KishanMalaviyaatCHETAK ELECTRICALS / Wikimedia Commons","CC BY-SA 4.0","https://commons.wikimedia.org/wiki/File:Three_Phase_Induction_Motor.jpg"),
    plc:asset("assets/reference/electrical/plc.jpg","Examples of micro, mini and rack-style programmable logic controllers.","Bisgaard / Wikimedia Commons","CC BY-SA 3.0 / GFDL","https://commons.wikimedia.org/wiki/File:Programmable_logic_controller.jpg"),
    "plc-inputs":asset("assets/reference/electrical/plc.jpg","PLC hardware showing modular I/O architecture.","Bisgaard / Wikimedia Commons","CC BY-SA 3.0 / GFDL","https://commons.wikimedia.org/wiki/File:Programmable_logic_controller.jpg"),
    "plc-outputs":asset("assets/reference/electrical/plc.jpg","PLC hardware showing modular I/O architecture.","Bisgaard / Wikimedia Commons","CC BY-SA 3.0 / GFDL","https://commons.wikimedia.org/wiki/File:Programmable_logic_controller.jpg"),
    vfd:asset("assets/reference/electrical/vfd.jpg","Variable-frequency drive with its power electronics and terminal wiring exposed.","Rahat / Wikimedia Commons","CC BY-SA 4.0","https://commons.wikimedia.org/wiki/File:Variable_frequency_drive.jpg"),
    "dc-bus":asset("assets/reference/electrical/vfd.jpg","VFD hardware: the DC bus lives inside the drive between the rectifier and inverter stages.","Rahat / Wikimedia Commons","CC BY-SA 4.0","https://commons.wikimedia.org/wiki/File:Variable_frequency_drive.jpg"),
    "proximity-sensor":asset("assets/reference/electrical/proximity_sensor.jpg","Industrial inductive proximity sensor in a threaded cylindrical housing.","Ekbsensor / Wikimedia Commons","CC BY-SA 4.0","https://commons.wikimedia.org/wiki/File:Inductive_proximity_sensor.jpg"),
    "pnp-npn":asset("assets/reference/electrical/proximity_sensor.jpg","A typical DC proximity sensor; the printed wiring diagram on the body is critical when identifying output type.","Ekbsensor / Wikimedia Commons","CC BY-SA 4.0","https://commons.wikimedia.org/wiki/File:Inductive_proximity_sensor.jpg"),
    multimeter:asset("assets/reference/electrical/multimeter.jpg","Digital multimeter with test leads and front-panel ranges.","oomlout / Wikimedia Commons","CC BY-SA 2.0","https://commons.wikimedia.org/wiki/File:Digital_Multimeter.jpg"),
    "clamp-meter":asset("assets/reference/electrical/multimeter.jpg","A standard multimeter is shown here; a clamp meter adds current measurement through a hinged magnetic jaw.","oomlout / Wikimedia Commons","CC BY-SA 2.0","https://commons.wikimedia.org/wiki/File:Digital_Multimeter.jpg")
  });

  // Grok V9 fix: ensure every electrical concept has world set
  D.concepts.forEach(c => { if (!c.world) c.world = "electrical"; });

  const ew = D.worlds.find(w=>w.id==="electrical");
  if(ew) ew.topics = D.concepts.filter(c=>!c.world || c.world==="electrical").length;
  if(D.worldLearningPaths?.electrical){
    D.worldLearningPaths.electrical.push(
      {id:"electrical-field",world:"electrical",name:"Read the Control Panel",level:"Intermediate",minutes:95,concepts:["disconnect","control-transformer","terminal-block","pushbutton","selector-switch","contactor","aux-contact","overload","motor-starter","mcc"]},
      {id:"electrical-analog",world:"electrical",name:"Industrial Signals",level:"Intermediate",minutes:85,concepts:["analog-signals","4-20ma","sinking-sourcing","pnp-npn","proximity-sensor","encoder","plc-inputs","hmi"]},
      {id:"electrical-drive",world:"electrical",name:"Motor + Drive Deep Dive",level:"Intermediate",minutes:110,concepts:["motor-nameplate","motor-slip","phase-sequence","phase-loss","reversing-starter","soft-starter","vfd","dc-bus"]}
    );
  }
})();
