(()=>{
'use strict';
const host=document.createElement('section');host.id='ratioLab';host.className='ratio-lab shell';
host.innerHTML=`<div class="ratio-heading"><span>DRIVE LAB / 01</span><h2>Trade speed for<br><em>turning force.</em></h2><p>A gearbox does not create power. Change the reduction and see where speed, torque and lost energy go.</p></div><div class="ratio-console"><div class="ratio-settings"><label>Reduction ratio <output id="ratioLabel">3:1</output><input id="gearRatio" type="range" min="1" max="6" step="0.5" value="3"></label><label>Input speed <output id="rpmLabel">3,000 rpm</output><input id="inputRpm" type="range" min="600" max="6000" step="100" value="3000"></label><label>Gearbox efficiency <output id="effLabel">90%</output><input id="gearEff" type="range" min="60" max="100" step="1" value="90"></label><p>Input torque is held at 100 N·m. This is an illustrative steady-state gearbox, not a prediction for a specific vehicle.</p></div><div class="ratio-results"><div class="ratio-gears"><svg id="ratioGears" viewBox="0 0 560 230" role="img" aria-label="Input gear driving a larger output gear"></svg></div><dl><div><dt>Output speed</dt><dd id="ratioSpeed"></dd></div><div><dt>Output torque</dt><dd id="ratioTorque"></dd></div><div><dt>Power delivered</dt><dd id="ratioPower"></dd></div><div><dt>Power lost</dt><dd id="ratioLoss"></dd></div></dl><p id="ratioExplain" aria-live="polite"></p></div></div><div class="ratio-question"><h3>Predict before you change it.</h3><p>At the same input speed and efficiency, doubling the reduction ratio will…</p><div><button type="button" data-ratio-answer="0">Double speed and torque</button><button type="button" data-ratio-answer="1">Halve speed, double torque</button><button type="button" data-ratio-answer="2">Halve both</button></div><p id="ratioFeedback" aria-live="polite">Choose an answer, then try it with the slider.</p></div><details><summary>Show the math and source</summary><p>Output rpm = input rpm ÷ reduction ratio. Output torque = input torque × ratio × efficiency. Power in watts = torque × rpm × 2π ÷ 60. Real gearboxes also have torque and thermal limits, changing efficiency and transient loads.</p><a href="https://blog.orientalmotor.com/gearhead-selection-for-stepper-motors" target="_blank" rel="noopener">Oriental Motor: speed, torque and efficiency ↗</a></details>`;
const anchor=document.querySelector('#diagnostics');if(!anchor)return;anchor.before(host);
const $=s=>host.querySelector(s);function draw(){const ratio=+$('#gearRatio').value,rpm=+$('#inputRpm').value,eff=+$('#gearEff').value/100,power=100*rpm*2*Math.PI/60/1000;$('#ratioLabel').textContent=ratio+':1';$('#rpmLabel').textContent=rpm.toLocaleString()+' rpm';$('#effLabel').textContent=Math.round(eff*100)+'%';$('#ratioSpeed').textContent=Math.round(rpm/ratio).toLocaleString()+' rpm';$('#ratioTorque').textContent=Math.round(100*ratio*eff)+' N·m';$('#ratioPower').textContent=(power*eff).toFixed(1)+' kW';$('#ratioLoss').textContent=(power*(1-eff)).toFixed(1)+' kW';$('#ratioExplain').textContent=`The output turns at 1/${ratio} of the input speed. ${Math.round(eff*100)}% of input power reaches it; the rest is lost, mainly as heat.`;gears.set(ratio,rpm);host.style.setProperty('--output-speed',2*3000/rpm*ratio+'s')}
/* meshing gear pair: the output gear has ratio × the input's teeth, so it turns 1/ratio as fast */
const gears=(()=>{const NS='http://www.w3.org/2000/svg',svg=$('#ratioGears'),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const N_IN=12;let ratio=3,rpm=3000,a=0,last=performance.now(),vis=true,raf=0;
const el=(t,at,p)=>{const n=document.createElementNS(NS,t);for(const k in at)n.setAttribute(k,at[k]);(p||svg).append(n);return n};
function path(N,m){const R=m*N/2,ra=R+m,rf=R-1.25*m,p=2*Math.PI/N;let d='';for(let i=0;i<N;i++){const t=i*p;for(const[r,f]of[[rf,-.27],[rf,-.2],[ra,-.1],[ra,.1],[rf,.2],[rf,.27]]){const u=t+f*p;d+=(d?'L':'M')+(r*Math.cos(u)).toFixed(2)+','+(r*Math.sin(u)).toFixed(2)}}return d+'Z'}
let gIn,gOut,nOut,offset;
function build(){svg.innerHTML='';nOut=Math.round(N_IN*ratio);const m=Math.min(6,440/(N_IN+nOut+4),190/(nOut+2.5)),rIn=m*N_IN/2,rOut=m*nOut/2,cy=115,cx=(560-(rIn+rOut))/2-(rOut-rIn)/2*0,xIn=300-(rIn+rOut)/2,xOut=xIn+rIn+rOut;
const mk=(x,N,cls,r)=>{const g=el('g',{transform:`translate(${x} ${cy})`});const rot=el('g',{},g);el('path',{d:path(N,m),class:'gear '+cls},rot);el('circle',{r:Math.max(4,r*.42),class:'gear-web'},rot);el('circle',{r:Math.max(3,r*.14),class:'gear-hub'},rot);for(let i=0;i<(N>20?6:3);i++){const t=i/(N>20?6:3)*Math.PI*2;el('circle',{cx:(Math.cos(t)*r*.62).toFixed(1),cy:(Math.sin(t)*r*.62).toFixed(1),r:Math.max(2,r*.1),class:'gear-hole'},rot)}el('line',{x1:0,y1:0,x2:0,y2:-(r*.42),class:'gear-mark'},rot);const side=cls==='gear-in';const lab=el('text',side?{x:-(r+m+10),y:4,class:'gear-lab','text-anchor':'end'}:{x:0,y:r+m+18,class:'gear-lab','text-anchor':'middle'},g);return{rot,lab}};
gIn=mk(xIn,N_IN,'gear-in',rIn);gOut=mk(xOut,nOut,'gear-out',rOut);gIn.lab.textContent=`INPUT · ${N_IN}T`;gOut.lab.textContent=`OUTPUT · ${nOut}T`;offset=180+180/nOut;paint()}
function paint(){gIn.rot.setAttribute('transform',`rotate(${a.toFixed(2)})`);gOut.rot.setAttribute('transform',`rotate(${(-a*N_IN/nOut+offset).toFixed(2)})`)}
function tick(now){raf=0;const dt=Math.min(.05,(now-last)/1000);last=now;a+=dt*rpm/3000*150;paint();if(vis&&!reduced)raf=requestAnimationFrame(tick)}
new IntersectionObserver(es=>{vis=es[0].isIntersecting;if(vis&&!raf&&!reduced){last=performance.now();raf=requestAnimationFrame(tick)}}).observe(svg);
return{set(r,s){if(r!==ratio||!gIn){ratio=r;build()}rpm=s}}})();
host.querySelectorAll('input').forEach(x=>x.addEventListener('input',draw));host.querySelectorAll('[data-ratio-answer]').forEach(b=>b.addEventListener('click',()=>{host.querySelectorAll('[data-ratio-answer]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('#ratioFeedback').textContent=b.dataset.ratioAnswer==='1'?'Exactly. Twice the ratio gives half the speed and twice the torque. With efficiency unchanged, output power stays the same.':'Follow the trade: speed is divided by the ratio; torque is multiplied by it. Double the ratio: half the speed, twice the torque.'}));draw();
})();
