/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LineageRouteImport } from './routes/lineage'
import { Route as MapRouteImport } from './routes/map'
import { Route as ServiceRouteImport } from './routes/service'
import { Route as SpiritsRouteImport } from './routes/spirits'
import { Route as WellRouteImport } from './routes/well'
import { Route as DSlugRouteImport } from './routes/d.$slug'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnTopicRouteImport } from './routes/learn.$topic'
import { Route as SpiritsIndexRouteImport } from './routes/spirits.index'
import { Route as SpiritsIdRouteImport } from './routes/spirits.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LineageRoute = LineageRouteImport.update({
  id: '/lineage',
  path: '/lineage',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRoute = ServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)
const SpiritsRoute = SpiritsRouteImport.update({
  id: '/spirits',
  path: '/spirits',
  getParentRoute: () => rootRouteImport,
} as any)
const WellRoute = WellRouteImport.update({
  id: '/well',
  path: '/well',
  getParentRoute: () => rootRouteImport,
} as any)
const DSlugRoute = DSlugRouteImport.update({
  id: '/d/$slug',
  path: '/d/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnRoute,
} as any)
const LearnTopicRoute = LearnTopicRouteImport.update({
  id: '/$topic',
  path: '/$topic',
  getParentRoute: () => LearnRoute,
} as any)
const SpiritsIndexRoute = SpiritsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpiritsRoute,
} as any)
const SpiritsIdRoute = SpiritsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SpiritsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/learn': typeof LearnRouteWithChildren
  '/lineage': typeof LineageRoute
  '/map': typeof MapRoute
  '/service': typeof ServiceRoute
  '/spirits': typeof SpiritsRouteWithChildren
  '/well': typeof WellRoute
  '/d/$slug': typeof DSlugRoute
  '/learn/$topic': typeof LearnTopicRoute
  '/spirits/$id': typeof SpiritsIdRoute
  '/learn/': typeof LearnIndexRoute
  '/spirits/': typeof SpiritsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lineage': typeof LineageRoute
  '/map': typeof MapRoute
  '/service': typeof ServiceRoute
  '/well': typeof WellRoute
  '/d/$slug': typeof DSlugRoute
  '/learn/$topic': typeof LearnTopicRoute
  '/spirits/$id': typeof SpiritsIdRoute
  '/learn': typeof LearnIndexRoute
  '/spirits': typeof SpiritsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/learn': typeof LearnRouteWithChildren
  '/lineage': typeof LineageRoute
  '/map': typeof MapRoute
  '/service': typeof ServiceRoute
  '/spirits': typeof SpiritsRouteWithChildren
  '/well': typeof WellRoute
  '/d/$slug': typeof DSlugRoute
  '/learn/$topic': typeof LearnTopicRoute
  '/spirits/$id': typeof SpiritsIdRoute
  '/learn/': typeof LearnIndexRoute
  '/spirits/': typeof SpiritsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/learn'
    | '/lineage'
    | '/map'
    | '/service'
    | '/spirits'
    | '/well'
    | '/d/$slug'
    | '/learn/$topic'
    | '/spirits/$id'
    | '/learn/'
    | '/spirits/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lineage'
    | '/map'
    | '/service'
    | '/well'
    | '/d/$slug'
    | '/learn/$topic'
    | '/spirits/$id'
    | '/learn'
    | '/spirits'
  id:
    | '__root__'
    | '/'
    | '/learn'
    | '/lineage'
    | '/map'
    | '/service'
    | '/spirits'
    | '/well'
    | '/d/$slug'
    | '/learn/$topic'
    | '/spirits/$id'
    | '/learn/'
    | '/spirits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LearnRoute: typeof LearnRouteWithChildren
  LineageRoute: typeof LineageRoute
  MapRoute: typeof MapRoute
  ServiceRoute: typeof ServiceRoute
  SpiritsRoute: typeof SpiritsRouteWithChildren
  WellRoute: typeof WellRoute
  DSlugRoute: typeof DSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lineage': {
      id: '/lineage'
      path: '/lineage'
      fullPath: '/lineage'
      preLoaderRoute: typeof LineageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spirits': {
      id: '/spirits'
      path: '/spirits'
      fullPath: '/spirits'
      preLoaderRoute: typeof SpiritsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/well': {
      id: '/well'
      path: '/well'
      fullPath: '/well'
      preLoaderRoute: typeof WellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$slug': {
      id: '/d/$slug'
      path: '/d/$slug'
      fullPath: '/d/$slug'
      preLoaderRoute: typeof DSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/$topic': {
      id: '/learn/$topic'
      path: '/$topic'
      fullPath: '/learn/$topic'
      preLoaderRoute: typeof LearnTopicRouteImport
      parentRoute: typeof LearnRoute
    }
    '/spirits/': {
      id: '/spirits/'
      path: '/'
      fullPath: '/spirits/'
      preLoaderRoute: typeof SpiritsIndexRouteImport
      parentRoute: typeof SpiritsRoute
    }
    '/spirits/$id': {
      id: '/spirits/$id'
      path: '/$id'
      fullPath: '/spirits/$id'
      preLoaderRoute: typeof SpiritsIdRouteImport
      parentRoute: typeof SpiritsRoute
    }
  }
}

interface LearnRouteChildren {
  LearnTopicRoute: typeof LearnTopicRoute
  LearnIndexRoute: typeof LearnIndexRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnTopicRoute: LearnTopicRoute,
  LearnIndexRoute: LearnIndexRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

interface SpiritsRouteChildren {
  SpiritsIdRoute: typeof SpiritsIdRoute
  SpiritsIndexRoute: typeof SpiritsIndexRoute
}

const SpiritsRouteChildren: SpiritsRouteChildren = {
  SpiritsIdRoute: SpiritsIdRoute,
  SpiritsIndexRoute: SpiritsIndexRoute,
}

const SpiritsRouteWithChildren =
  SpiritsRoute._addFileChildren(SpiritsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LearnRoute: LearnRouteWithChildren,
  LineageRoute: LineageRoute,
  MapRoute: MapRoute,
  ServiceRoute: ServiceRoute,
  SpiritsRoute: SpiritsRouteWithChildren,
  WellRoute: WellRoute,
  DSlugRoute: DSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
