(()=>{
'use strict';
['photos.css','upgrade.css','experience.css'].forEach(href=>{const l=document.createElement('link');l.rel='stylesheet';l.href=href;document.head.append(l)});
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:2}).format(n);
const implied=o=>{o=Number(o);if(!Number.isFinite(o)||o===0)return NaN;return o<0?(-o)/((-o)+100):100/(o+100)};
const profit=(o,s)=>{o=Number(o);s=Number(s);if(!Number.isFinite(o)||!Number.isFinite(s)||o===0||s<0)return NaN;return o<0?s*100/(-o):s*o/100};
function syncOdds(){const o=+($('#americanOdds')?.value||0),s=+($('#stake')?.value||0),p=implied(o),pr=profit(o,s);if($('#probOut'))$('#probOut').textContent=Number.isFinite(p)?(p*100).toFixed(2)+'%':'—';if($('#profitOut'))$('#profitOut').textContent=Number.isFinite(pr)?money(pr):'—';if($('#returnOut'))$('#returnOut').textContent=Number.isFinite(pr)?money(pr+s):'—'}
['americanOdds','stake'].forEach(id=>$('#'+id)?.addEventListener('input',syncOdds));syncOdds();

const markers={
  blackjack:['01','BLACKJACK','21'],
  baccarat:['02','BACCARAT','B / P'],
  craps:['03','CRAPS','⚄ ⚂'],
  roulette:['04','ROULETTE','0 / 00'],
  slots:['05','SLOTS','777'],
  poker:['06','POKER','A♠ K♠'],
  sports:['07','SPORTSBOOK','−110']
};
Object.entries(markers).forEach(([id,[no,name,symbol]])=>{const sec=$('#'+id);if(sec&&!sec.querySelector('.chapter-marker'))sec.insertAdjacentHTML('afterbegin',`<div class="chapter-marker"><span class="chapter-no">${no} / NEW GAME</span><strong class="chapter-name">${name}</strong><span class="chapter-symbol">${symbol}</span></div>`)});

const blackjack=$('#blackjack');
if(blackjack){blackjack.insertAdjacentHTML('beforeend',`<div class="deep-dive blackjack-deep">
  <div class="section-title"><h3>The blackjack edge starts before the first card.</h3><p>The table rules can move the house edge more than many players realize. Pick the right game first, then use basic strategy to avoid giving that edge back.</p></div>
  <div class="two-col-detail"><table class="data-table"><thead><tr><th>Natural blackjack</th><th>$10 bet</th><th>$25 bet</th><th>$100 bet</th></tr></thead><tbody><tr><td><strong>3:2 payout</strong></td><td>$15 profit</td><td>$37.50 profit</td><td>$150 profit</td></tr><tr><td class="warn"><strong>6:5 payout</strong></td><td>$12 profit</td><td>$30 profit</td><td>$120 profit</td></tr></tbody></table><div class="callout-stack"><div class="callout"><h4>Table selection is strategy.</h4><p>Look for 3:2 blackjack, dealer stands on soft 17, double after split, and surrender when available.</p></div><div class="callout"><h4>Insurance is usually a bad price.</h4><p>Insurance normally pays 2:1, but unless the remaining deck is unusually rich in tens, basic strategy players generally skip it.</p></div></div></div>
  <div class="blackjack-playstrip"><div><span>PAIR</span><b>Split Aces and 8s</b><p>Aces create strong new hands. Splitting 8s helps escape hard 16.</p></div><div><span>PAIR</span><b>Keep 10s together</b><p>Twenty is already excellent. Do not break a strong hand chasing more.</p></div><div><span>HARD 12</span><b>Dealer 4 to 6</b><p>Typical multi-deck strategy stands because the dealer is more likely to break.</p></div><div><span>SOFT 18</span><b>Ace + 7 is flexible</b><p>Under common S17 rules, the play changes sharply with the dealer up-card.</p></div></div>
</div>`)}

const baccarat=$('#baccarat');
if(baccarat){baccarat.insertAdjacentHTML('beforeend',`<div class="deep-dive baccarat-deep"><div class="section-title"><h3>Baccarat is mostly a pricing decision.</h3><p>The drawing rules are automatic. The useful part is knowing which wager carries the lowest edge and ignoring pattern-chasing.</p></div><div class="edge-race"><div class="edge-row"><b>Banker</b><div class="track"><i style="--w:7%"></i></div><strong>1.06%</strong><small>Usually the best standard wager.</small></div><div class="edge-row"><b>Player</b><div class="track"><i style="--w:9%"></i></div><strong>1.24%</strong><small>Close second, no commission on the win.</small></div><div class="edge-row bad"><b>Tie</b><div class="track"><i style="--w:86%"></i></div><strong>14.36%</strong><small>Large payout, dramatically worse long-run value.</small></div></div><div class="callout" style="margin-top:12px"><h4>Do not confuse a roadmap with a forecast.</h4><p>Past Banker and Player results can form visible streaks, but the next hand is still independent. Increasing a bet because a side feels “due” changes your risk, not the probability.</p></div></div>`)}

const craps=$('#craps');
if(craps){craps.insertAdjacentHTML('beforeend',`<div class="deep-dive craps-deep"><div class="section-title"><h3>A clean craps route is much smaller than the table.</h3><p>Most new players get lost because the felt shows dozens of wagers at once. You can understand the game by learning one path first.</p></div><div class="craps-route"><article><span>STEP 01</span><b>Pass or Don't Pass</b><p>Start with a line bet and learn what wins on the come-out roll.</p></article><article><span>STEP 02</span><b>Point is set</b><p>4, 5, 6, 8, 9, or 10 becomes the target before a 7 appears.</p></article><article><span>STEP 03</span><b>Add odds</b><p>The odds portion is paid at true odds and carries no house edge by itself.</p></article><article><span>STEP 04</span><b>Expand carefully</b><p>Come bets and Place 6/8 are reasonable next steps. Learn proposition bets last.</p></article></div><table class="data-table" style="margin-top:12px"><thead><tr><th>Point</th><th>Taking odds pays</th><th>Reason</th></tr></thead><tbody><tr><td><strong>4 or 10</strong></td><td>2:1</td><td>True odds of making the point before seven.</td></tr><tr><td><strong>5 or 9</strong></td><td>3:2</td><td>True odds, no embedded edge on that added wager.</td></tr><tr><td><strong>6 or 8</strong></td><td>6:5</td><td>True odds, again with zero house edge on the odds portion.</td></tr></tbody></table></div>`)}

const roulette=$('#roulette');
if(roulette){roulette.insertAdjacentHTML('beforeend',`<div class="roulette-builder" id="rouletteBuilder"><div class="roulette-builder-head"><div><h3>Build a roulette bet.</h3><p>Choose the wheel, click a number or bet type, enter a stake, and see what the payout and hit probability actually look like.</p></div><div class="wheel-toggle"><button type="button" class="on" data-wheel="european">European 0</button><button type="button" data-wheel="american">American 0 / 00</button></div></div><div class="roulette-builder-body"><div class="roulette-mat-wrap"><div class="roulette-mat" id="rouletteMat"><button class="roulette-zero on" data-num="0" type="button">0</button></div><div class="roulette-outside"><button type="button" data-kind="even" data-label="Red">RED</button><button type="button" data-kind="even" data-label="Black">BLACK</button><button type="button" data-kind="even" data-label="Odd">ODD</button><button type="button" data-kind="even" data-label="Even">EVEN</button><button type="button" data-kind="dozen" data-label="1st dozen">1–12</button><button type="button" data-kind="dozen" data-label="2nd dozen">13–24</button><button type="button" data-kind="dozen" data-label="3rd dozen">25–36</button></div><div class="bet-kinds"><button type="button" class="on" data-kind="straight">Straight up</button><button type="button" data-kind="split">Split</button><button type="button" data-kind="street">Street</button><button type="button" data-kind="corner">Corner</button><button type="button" data-kind="six">Six line</button></div></div><aside class="roulette-slip"><h4>Your bet</h4><label>Stake<input id="rouletteStake" type="number" min="1" step="5" value="25"></label><div class="roulette-output"><div><span>BET</span><b id="rouletteBet">0 straight up</b></div><div><span>PAYOUT</span><b id="roulettePayout">35:1</b></div><div><span>HIT CHANCE</span><b id="rouletteChance">2.70%</b></div><div><span>PROFIT IF IT HITS</span><b id="rouletteProfit">$875.00</b></div><div><span>TOTAL RETURN</span><b id="rouletteReturn">$900.00</b></div><div><span>HOUSE EDGE</span><b id="rouletteEdge">2.70%</b></div></div><div class="roulette-read" id="rouletteRead">A straight-up number covers 1 pocket out of 37 on a European wheel. The payout is 35:1.</div></aside></div></div>`)}

const slots=$('#slots');
if(slots){slots.insertAdjacentHTML('beforeend',`<div class="deep-dive slots-deep"><div class="section-title"><h3>Read the machine like a product spec, not a mood.</h3><p>The animation is presentation. The useful information is RTP, volatility, hit frequency, the paytable, and any wager requirement tied to a feature or jackpot.</p></div><div class="slot-anatomy"><article><div class="big-code">96%</div><h4>RTP</h4><p>Long-run modeled return. It does not promise a 96% return in one session.</p></article><article><div class="big-code">VOL</div><h4>Volatility</h4><p>Low volatility spreads value into smaller, more frequent wins. High volatility concentrates more value into fewer, larger hits.</p></article><article><div class="big-code">HIT</div><h4>Hit frequency</h4><p>How often any winning result appears. Many “wins” can still be smaller than the original wager.</p></article><article><div class="big-code">PAY</div><h4>Paytable</h4><p>The actual payout schedule. Read it before assuming every denomination or version of a game behaves the same.</p></article></div></div>`)}

function pc(rank,suit){const red=suit==='♥'||suit==='♦';return `<span class="p-card${red?' red':''}"><b>${rank}</b><i>${suit}</i></span>`}
function handRow(rank,title,cards,desc){return `<div class="poker-hand-row"><div class="hand-name"><span>${rank}</span><b>${title}</b></div><div class="mini-hand">${cards.join('')}</div><p>${desc}</p></div>`}
const poker=$('#poker');
if(poker){
  const hands=[
    handRow('01','Royal flush',[pc('A','♥'),pc('K','♥'),pc('Q','♥'),pc('J','♥'),pc('10','♥')],'<strong>Highest possible straight flush.</strong> All five cards are consecutive and the same suit, ending at Ace.'),
    handRow('02','Straight flush',[pc('9','♣'),pc('8','♣'),pc('7','♣'),pc('6','♣'),pc('5','♣')],'Five consecutive cards of the same suit. If two players have one, the higher top card wins.'),
    handRow('03','Four of a kind',[pc('Q','♠'),pc('Q','♥'),pc('Q','♦'),pc('Q','♣'),pc('2','♥')],'Four cards of one rank. The fifth card is the kicker if players share the same quads on the board.'),
    handRow('04','Full house',[pc('K','♠'),pc('K','♥'),pc('K','♦'),pc('9','♣'),pc('9','♦')],'Three of a kind plus a pair. Compare the three-card rank first, then the pair.'),
    handRow('05','Flush',[pc('A','♦'),pc('J','♦'),pc('8','♦'),pc('5','♦'),pc('2','♦')],'Five cards of one suit, not consecutive. Compare the highest card, then the next highest as needed.'),
    handRow('06','Straight',[pc('9','♠'),pc('8','♥'),pc('7','♦'),pc('6','♣'),pc('5','♠')],'Five consecutive ranks of mixed suits. Aces can be high or low, but not wrap around.'),
    handRow('07','Three of a kind',[pc('7','♠'),pc('7','♥'),pc('7','♦'),pc('K','♣'),pc('2','♠')],'Three matching ranks plus two side cards. Trips and sets are both three of a kind, reached differently.'),
    handRow('08','Two pair',[pc('J','♠'),pc('J','♥'),pc('4','♦'),pc('4','♣'),pc('9','♠')],'Two separate pairs plus a kicker. Compare the higher pair first, then the lower pair, then the kicker.'),
    handRow('09','One pair',[pc('A','♠'),pc('A','♦'),pc('10','♣'),pc('7','♥'),pc('3','♠')],'Two matching ranks. If the pair is tied, compare kickers from highest to lowest.'),
    handRow('10','High card',[pc('A','♠'),pc('J','♦'),pc('8','♣'),pc('5','♥'),pc('2','♣')],'No pair, straight, or flush. The highest card wins, then kickers break ties.')
  ].join('');
  poker.innerHTML=`<div class="chapter-marker"><span class="chapter-no">06 / NEW GAME</span><strong class="chapter-name">POKER</strong><span class="chapter-symbol">A♠ K♠</span></div><div class="poker-visual"><div class="media-sprite media-poker" role="img" aria-label="Real poker table with cards and chips"></div></div><div class="poker-intro"><p class="kicker">POKER / DECISIONS UNDER UNCERTAINTY</p><h2>Poker is a probability game with people in the middle of it.</h2><p>The cards create the mathematical framework. Position, ranges, stack size, bet sizing, and opponent behavior decide how you use it. The room takes a rake, but most of your edge comes from making better decisions than the other players.</p></div><div class="poker-guide">
  <section><h3 style="font:700 34px var(--serif);color:var(--cream);margin:0 0 10px">Hand rankings you can actually see.</h3><div class="poker-hand-ladder">${hands}</div></section>
  <section><h3 style="font:700 34px var(--serif);color:var(--cream);margin:0 0 10px">Position changes the value of the same cards.</h3><div class="poker-position-strip"><article><span>EARLY</span><b>Play tighter</b><p>More players remain behind you, so weak opens are more likely to run into strength.</p></article><article><span>MIDDLE</span><b>Widen carefully</b><p>Fewer players remain, but early-position raises still deserve respect.</p></article><article><span>CUTOFF</span><b>Attack more</b><p>Late position gives more information and more chances to pressure blinds.</p></article><article><span>BUTTON</span><b>Best seat</b><p>You act last after the flop, which is one of the biggest structural advantages in hold'em.</p></article><article><span>BLINDS</span><b>Price matters</b><p>You already have chips invested, but you will often play the rest of the hand out of position.</p></article></div></section>
  <section class="poker-equity-lab"><div class="equity-controls"><h3>Draw odds lab</h3><p>Use clean outs only. If an “out” can make a better hand for your opponent, it should not be counted at full value.</p><div class="preset-outs"><button type="button" data-outs="9">Flush draw · 9 outs</button><button type="button" data-outs="8">Open-ended straight · 8</button><button type="button" data-outs="4">Gutshot · 4</button><button type="button" data-outs="2">Two-outer · 2</button></div><div class="equity-inputs"><label>Pot before call<input id="pokerPot" type="number" min="1" value="100"></label><label>Call amount<input id="pokerCall" type="number" min="1" value="20"></label><label>Clean outs<input id="pokerOuts" type="number" min="0" max="20" value="9"></label></div></div><div class="equity-results"><h3>What the math says</h3><div class="numbers"><div><span>REQUIRED EQUITY</span><b id="pokerRequired">16.7%</b></div><div><span>ONE CARD TO COME</span><b id="pokerOneCard">19.1%</b></div><div><span>TWO CARDS TO COME</span><b id="pokerTwoCard">35.0%</b></div></div><div class="equity-meter"><i id="pokerMeter"></i></div><div class="equity-verdict" id="pokerVerdict">On direct pot odds alone, 9 clean outs are enough against this price. Opponent range, implied odds, reverse implied odds, and fold equity can still change the real decision.</div></div></section>
  <section><h3 style="font:700 34px var(--serif);color:var(--cream);margin:0 0 10px">Common probability situations.</h3><table class="data-table draw-table"><thead><tr><th>Situation after the flop</th><th>Clean outs</th><th>Hit on next card</th><th>Hit by river</th><th>What to remember</th></tr></thead><tbody><tr><td><strong>Four-card flush</strong></td><td>9</td><td>19.1%</td><td>35.0%</td><td>You are not “about 50/50.” Price the call against roughly 35% by the river.</td></tr><tr><td><strong>Open-ended straight draw</strong></td><td>8</td><td>17.0%</td><td>31.5%</td><td>Strong draw, but still misses most of the time.</td></tr><tr><td><strong>Gutshot straight draw</strong></td><td>4</td><td>8.5%</td><td>16.5%</td><td>Needs a much better price than an open-ended draw.</td></tr><tr><td><strong>Two overcards</strong></td><td>Up to 6</td><td>Up to 12.8%</td><td>Up to 24.1%</td><td>Some outs may be dirty if pairing your card still leaves you behind.</td></tr><tr><td><strong>Pocket pair trying to make a set</strong></td><td>2</td><td>4.3%</td><td>8.4%</td><td>A classic example of why implied odds matter.</td></tr></tbody></table></section>
  <section><h3 style="font:700 34px var(--serif);color:var(--cream);margin:0 0 10px">Different poker games change what “strong” means.</h3><div class="poker-variants"><details class="variant-detail" open><summary>Texas Hold'em</summary><div><b>2 hole cards + 5 community cards.</b><br>Make the best five-card hand using any combination of your cards and the board. Position and preflop ranges are central.</div></details><details class="variant-detail"><summary>Pot-Limit Omaha</summary><div><b>4 hole cards, use exactly 2.</b><br>Hands run much closer in equity than hold'em. Nut draws and redraws matter heavily.</div></details><details class="variant-detail"><summary>Omaha Hi-Lo</summary><div><b>Pot can split high and low.</b><br>You still use exactly two hole cards. Strong play often targets hands that can win both halves.</div></details><details class="variant-detail"><summary>Seven-Card Stud</summary><div><b>No community board.</b><br>Each player receives a mix of visible and hidden cards. Remembering folded exposed cards is part of the edge.</div></details><details class="variant-detail"><summary>Five-Card Draw</summary><div><b>One draw, hidden information.</b><br>Pre-draw hand strength, discard choices, and betting patterns matter more than board texture.</div></details></div></section>
</div>`;
}

const sports=$('#sports');
if(sports){sports.insertAdjacentHTML('beforeend',`<div class="deep-dive sports-deep"><div class="section-title"><h3>A sportsbook is a pricing screen.</h3><p>The team name is emotional. The number is the bet. Learn what price you need to break even before deciding whether you have an edge.</p></div><div class="sports-market-tape"><div><span>−110</span><b>52.38% break-even</b><p>A common spread or total price. Win more than this rate to overcome the vig.</p></div><div><span>+150</span><b>40.00% implied</b><p>A $100 winning bet earns $150 profit before the original stake is returned.</p></div><div><span>−200</span><b>66.67% implied</b><p>You risk $200 to win $100. A heavy favorite can still be a bad bet if the price is too high.</p></div><div><span>PARLAY</span><b>Edges multiply too</b><p>Combining legs raises payout but also compounds the bookmaker's hold and variance.</p></div></div></div>`)}

/* Roulette interaction */
const redNums=new Set([1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36]);
const mat=$('#rouletteMat');
if(mat){
  for(let n=1;n<=36;n++){const b=document.createElement('button');b.type='button';b.className='roulette-number '+(redNums.has(n)?'red':'black');b.dataset.num=n;b.textContent=n;mat.appendChild(b)}
  const zz=document.createElement('button');zz.type='button';zz.className='roulette-zero double';zz.dataset.num='00';zz.textContent='00';mat.appendChild(zz);
  const state={wheel:'european',kind:'straight',label:'0 straight up',selected:'0'};
  const specs={straight:[1,35],split:[2,17],street:[3,11],corner:[4,8],six:[6,5],dozen:[12,2],even:[18,1]};
  const updateRoulette=()=>{const pockets=state.wheel==='american'?38:37,[cover,pay]=specs[state.kind],stake=Math.max(0,+($('#rouletteStake')?.value||0)),chance=cover/pockets*100,edge=state.wheel==='american'?5.26:2.70;$('#rouletteBet').textContent=state.label;$('#roulettePayout').textContent=pay+':1';$('#rouletteChance').textContent=chance.toFixed(2)+'%';$('#rouletteProfit').textContent=money(stake*pay);$('#rouletteReturn').textContent=money(stake*(pay+1));$('#rouletteEdge').textContent=edge.toFixed(2)+'%';$('#rouletteRead').textContent=`This ${state.kind==='even'?'even-money':state.kind} bet covers ${cover} pocket${cover===1?'':'s'} out of ${pockets}. A ${state.wheel==='american'?'double-zero American':'single-zero European'} wheel gives a standard house edge of about ${edge.toFixed(2)}% on this wager.`};
  $$('.wheel-toggle button').forEach(b=>b.addEventListener('click',()=>{state.wheel=b.dataset.wheel;$$('.wheel-toggle button').forEach(x=>x.classList.toggle('on',x===b));mat.classList.toggle('american',state.wheel==='american');updateRoulette()}));
  $$('.bet-kinds button').forEach(b=>b.addEventListener('click',()=>{state.kind=b.dataset.kind;state.label=b.textContent.trim();$$('.bet-kinds button,.roulette-outside button').forEach(x=>x.classList.toggle('on',x===b));updateRoulette()}));
  $$('.roulette-outside button').forEach(b=>b.addEventListener('click',()=>{state.kind=b.dataset.kind;state.label=b.dataset.label;$$('.bet-kinds button,.roulette-outside button').forEach(x=>x.classList.toggle('on',x===b));updateRoulette()}));
  $$('.roulette-number,.roulette-zero',mat).forEach(b=>b.addEventListener('click',()=>{state.kind='straight';state.selected=b.dataset.num;state.label=b.dataset.num+' straight up';$$('.roulette-number,.roulette-zero',mat).forEach(x=>x.classList.toggle('on',x===b));$$('.bet-kinds button,.roulette-outside button').forEach(x=>x.classList.remove('on'));const s=$('.bet-kinds [data-kind="straight"]');if(s)s.classList.add('on');updateRoulette()}));
  $('#rouletteStake')?.addEventListener('input',updateRoulette);updateRoulette();
}

/* Poker odds lab */
function updatePokerLab(){const pot=Math.max(0,+($('#pokerPot')?.value||0)),call=Math.max(0,+($('#pokerCall')?.value||0)),outs=Math.max(0,Math.min(20,+($('#pokerOuts')?.value||0))),req=call/(pot+call||1),one=outs/47,two=1-((47-outs)/47)*((46-outs)/46);if($('#pokerRequired'))$('#pokerRequired').textContent=(req*100).toFixed(1)+'%';if($('#pokerOneCard'))$('#pokerOneCard').textContent=(one*100).toFixed(1)+'%';if($('#pokerTwoCard'))$('#pokerTwoCard').textContent=(two*100).toFixed(1)+'%';if($('#pokerMeter'))$('#pokerMeter').style.width=Math.min(100,two*100)+'%';const good=one>=req;const v=$('#pokerVerdict');if(v)v.textContent=`On direct pot odds alone, ${outs} clean out${outs===1?'':'s'} give about ${(one*100).toFixed(1)}% to hit on the next card versus ${(req*100).toFixed(1)}% required by the price. ${good?'That clears the direct-odds threshold.':'That does not clear the direct-odds threshold.'} Opponent range, implied odds, reverse implied odds, and fold equity can still change the real decision.`}
['pokerPot','pokerCall','pokerOuts'].forEach(id=>$('#'+id)?.addEventListener('input',updatePokerLab));$$('[data-outs]').forEach(b=>b.addEventListener('click',()=>{if($('#pokerOuts'))$('#pokerOuts').value=b.dataset.outs;updatePokerLab()}));updatePokerLab();

/* Help drawer */
const drawer=$('#helpDrawer'),backdrop=$('#drawerBackdrop');
function openHelp(){if(!drawer)return;drawer.classList.add('open');backdrop?.classList.add('open');drawer.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeHelp(){if(!drawer)return;drawer.classList.remove('open');backdrop?.classList.remove('open');drawer.setAttribute('aria-hidden','true');document.body.style.overflow=''}
['helpOpen','floatingHelp','startHere'].forEach(id=>$('#'+id)?.addEventListener('click',openHelp));$('#helpClose')?.addEventListener('click',closeHelp);backdrop?.addEventListener('click',closeHelp);$('#helpJump')?.addEventListener('click',closeHelp);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeHelp()});

/* Reveals */
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('seen');observer.unobserve(e.target)}}),{threshold:.06});
$$('.game-selector>*,.chapter-marker,.chapter-visual,.chapter-intro,.blackjack-grid,.baccarat-head,.baccarat-bets,.baccarat-explain,.craps-hero,.craps-flow,.craps-table-wrap,.roulette-layout,.roulette-facts,.roulette-builder,.slots-stage,.slot-concepts,.volatility-demo,.poker-visual,.poker-intro,.poker-guide>*,.sports-top,.sports-board,.deep-dive>*,.odds-lab>*,.responsibility>*').forEach(el=>{el.classList.add('reveal');observer.observe(el)});

/* Decorative physics chips on desktop */
if(window.Matter&&innerWidth>760){const canvas=$('#chips'),{Engine,Render,Runner,Bodies,Composite,Body}=Matter;const engine=Engine.create();engine.gravity.y=.18;const render=Render.create({canvas,engine,options:{width:innerWidth,height:innerHeight,pixelRatio:Math.min(devicePixelRatio||1,1.35),wireframes:false,background:'transparent'}});Composite.add(engine.world,Bodies.rectangle(innerWidth/2,innerHeight+70,innerWidth+200,120,{isStatic:true,render:{visible:false}}));const colors=['#c6a34e','#315e45','#8d3430','#dcd2b8'];for(let i=0;i<13;i++){const r=7+Math.random()*8,b=Bodies.circle(Math.random()*innerWidth,-100-Math.random()*innerHeight*.8,r,{restitution:.7,frictionAir:.01,render:{fillStyle:colors[i%colors.length],strokeStyle:'rgba(255,255,255,.18)',lineWidth:1}});Body.setAngularVelocity(b,(Math.random()-.5)*.05);Composite.add(engine.world,b)}Render.run(render);Runner.run(Runner.create(),engine)}
})();