(()=>{
'use strict';
const photoSheet=document.createElement('link');photoSheet.rel='stylesheet';photoSheet.href='photos.css';document.head.append(photoSheet);
const upgradeSheet=document.createElement('link');upgradeSheet.rel='stylesheet';upgradeSheet.href='upgrade.css';document.head.append(upgradeSheet);
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:2}).format(n);
function implied(o){o=Number(o);if(!Number.isFinite(o)||o===0)return NaN;return o<0?(-o)/((-o)+100):100/(o+100)}
function profit(o,s){o=Number(o);s=Number(s);if(!Number.isFinite(o)||!Number.isFinite(s)||o===0||s<0)return NaN;return o<0?s*100/(-o):s*o/100}
function syncOdds(){const o=+$('#americanOdds').value,s=+$('#stake').value,p=implied(o),pr=profit(o,s);$('#probOut').textContent=Number.isFinite(p)?(p*100).toFixed(2)+'%':'—';$('#profitOut').textContent=Number.isFinite(pr)?money(pr):'—';$('#returnOut').textContent=Number.isFinite(pr)?money(pr+s):'—'}
['americanOdds','stake'].forEach(id=>$('#'+id)?.addEventListener('input',syncOdds));syncOdds();

function addDeepDive(id,html){const section=$(id);if(section&&!section.querySelector('.deep-dive'))section.insertAdjacentHTML('beforeend',html)}

addDeepDive('#blackjack',`<div class="deep-dive blackjack-deep">
  <div class="section-title"><h3>Where most blackjack money is won or lost.</h3><p>The table rules matter before the cards are even dealt. Then basic strategy decides whether you keep the house edge near its minimum or give it back through avoidable mistakes.</p></div>
  <div class="two-col-detail">
    <table class="data-table"><thead><tr><th>Natural blackjack</th><th>$10 bet</th><th>$25 bet</th><th>$100 bet</th></tr></thead><tbody><tr><td><strong>3:2 payout</strong></td><td>$15 profit</td><td>$37.50 profit</td><td>$150 profit</td></tr><tr><td class="warn"><strong>6:5 payout</strong></td><td>$12 profit</td><td>$30 profit</td><td>$120 profit</td></tr></tbody></table>
    <div class="callout-stack"><div class="callout"><h4>Insurance is usually a bad trade.</h4><p>Insurance normally pays 2:1, but unless the deck is unusually rich in tens, the price is not favorable. Basic strategy players generally skip it.</p></div><div class="callout"><h4>Table selection is strategy.</h4><p>Prefer 3:2 blackjack, dealer stands on soft 17, double after split, and surrender when available.</p></div></div>
  </div>
  <div class="info-grid" style="margin-top:12px"><article class="info-card"><span class="label">PAIR RULE</span><h4>Split Aces and 8s</h4><p>Aces create strong starting hands after the split. Two 8s become two chances to escape a weak hard 16.</p></article><article class="info-card"><span class="label">PAIR RULE</span><h4>Do not split 10s or 5s</h4><p>Twenty is already excellent. A pair of 5s should usually be played as a hard 10 and doubled in favorable spots.</p></article><article class="info-card"><span class="label">COMMON HARD TOTAL</span><h4>12 vs. dealer 4 to 6</h4><p>Typical multi-deck basic strategy stands because the dealer is more likely to break. Against 2, 3, or 7 through Ace, the answer changes.</p></article><article class="info-card"><span class="label">SOFT HAND</span><h4>Ace + 7 is flexible</h4><p>Under common S17 rules, double against 3 to 6, stand against 2, 7, or 8, and hit against 9, 10, or Ace.</p></article></div>
</div>`);

addDeepDive('#baccarat',`<div class="deep-dive baccarat-deep">
  <div class="section-title"><h3>Baccarat is simple once you stop trying to predict patterns.</h3><p>The roadmaps can make streaks look meaningful, but each new hand is independent. The useful decision is choosing the wager with the best price.</p></div>
  <table class="data-table"><thead><tr><th>Bet</th><th>Typical payout</th><th>Typical house edge</th><th>Practical read</th></tr></thead><tbody><tr><td><strong>Banker</strong></td><td>1:1 less 5% commission</td><td class="good">about 1.06%</td><td>Usually the strongest standard bet.</td></tr><tr><td><strong>Player</strong></td><td>1:1</td><td>about 1.24%</td><td>Close second, simple payout.</td></tr><tr><td><strong>Tie</strong></td><td>Often 8:1</td><td class="warn">about 14.36%</td><td>Large payout, poor long-run value.</td></tr></tbody></table>
  <div class="info-grid" style="margin-top:12px"><article class="info-card"><span class="label">BEST HABIT</span><h4>Banker first</h4><p>If the standard commission structure is in place, Banker normally has the lowest edge.</p></article><article class="info-card"><span class="label">DO NOT CHASE</span><h4>Roadmap streaks</h4><p>Past Banker and Player results do not make the next result more likely.</p></article><article class="info-card"><span class="label">PAYOUT CHECK</span><h4>Know the commission</h4><p>Some no-commission variants change the payoff on specific Banker results. Read that rule before assuming the same edge.</p></article><article class="info-card"><span class="label">SESSION RULE</span><h4>Flat bets beat emotion</h4><p>Increasing wagers to recover losses changes your risk, not the underlying probability of the next hand.</p></article></div>
</div>`);

addDeepDive('#craps',`<div class="deep-dive craps-deep">
  <div class="section-title"><h3>You only need a small part of the craps layout to play intelligently.</h3><p>The middle of the table is visually loud because many proposition bets pay large multiples. The best mathematical route is much simpler.</p></div>
  <div class="two-col-detail"><table class="data-table"><thead><tr><th>Point</th><th>Taking odds pays</th><th>Why</th></tr></thead><tbody><tr><td><strong>4 or 10</strong></td><td>2:1</td><td>True odds of making the point before 7.</td></tr><tr><td><strong>5 or 9</strong></td><td>3:2</td><td>True odds, no built-in house edge on the odds portion.</td></tr><tr><td><strong>6 or 8</strong></td><td>6:5</td><td>True odds, again with zero house edge on that added wager.</td></tr></tbody></table><div class="callout"><h4>A clean beginner sequence</h4><ul><li>Make a Pass Line or Don't Pass bet.</li><li>Wait for a point.</li><li>Add odds behind the line if the bankroll supports it.</li><li>Learn Place 6 and Place 8 next.</li><li>Leave the center-table one-roll bets alone until you know their edges.</li></ul></div></div>
  <div class="info-grid" style="margin-top:12px"><article class="info-card"><span class="label">PLACE 6 / 8</span><h4>7:6 payout</h4><p>These are among the more reasonable place bets, with a house edge around 1.52%.</p></article><article class="info-card"><span class="label">COME BET</span><h4>A moving Pass Line</h4><p>A Come bet starts after the come-out roll and can also be backed with odds once its number is established.</p></article><article class="info-card"><span class="label">DON'T SIDE</span><h4>Slightly lower edge</h4><p>Don't Pass is about 1.36% before odds, but some players simply prefer betting with the shooter.</p></article><article class="info-card"><span class="label">WATCH OUT</span><h4>Flashy proposition bets</h4><p>Big printed payouts can hide house edges that jump into the high single digits or worse.</p></article></div>
</div>`);

addDeepDive('#roulette',`<div class="deep-dive roulette-deep">
  <div class="section-title"><h3>The payout changes with the bet. The wheel decides the house edge.</h3><p>On standard roulette, a straight-up number and an even-money wager are priced from the same wheel. The number of zero pockets is what changes the long-run math.</p></div>
  <table class="data-table"><thead><tr><th>Bet type</th><th>Numbers covered</th><th>Payout</th><th>Single-zero hit chance</th></tr></thead><tbody><tr><td>Straight up</td><td>1</td><td>35:1</td><td>2.70%</td></tr><tr><td>Split</td><td>2</td><td>17:1</td><td>5.41%</td></tr><tr><td>Street</td><td>3</td><td>11:1</td><td>8.11%</td></tr><tr><td>Corner</td><td>4</td><td>8:1</td><td>10.81%</td></tr><tr><td>Six line</td><td>6</td><td>5:1</td><td>16.22%</td></tr><tr><td>Dozen / column</td><td>12</td><td>2:1</td><td>32.43%</td></tr><tr><td>Red / black, odd / even</td><td>18</td><td>1:1</td><td>48.65%</td></tr></tbody></table>
  <div class="info-grid" style="margin-top:12px"><article class="info-card"><span class="label">BEST TABLE CHOICE</span><h4>Single zero</h4><p>European roulette cuts the standard edge to 2.70% versus 5.26% on American double-zero roulette.</p></article><article class="info-card"><span class="label">VARIANCE</span><h4>Outside bets feel calmer</h4><p>They hit more often, but they do not erase the wheel edge.</p></article><article class="info-card"><span class="label">FRENCH RULES</span><h4>La Partage can help</h4><p>On qualifying even-money bets, losing only half when zero hits can reduce the effective edge to about 1.35%.</p></article><article class="info-card"><span class="label">MYTH</span><h4>No number is due</h4><p>Hot and cold boards describe the past. They do not change the probability of the next independent spin.</p></article></div>
</div>`);

addDeepDive('#slots',`<div class="deep-dive slots-deep">
  <div class="section-title"><h3>The paytable matters more than the animation.</h3><p>Slots are software with a probability model. The symbols, bonus rounds, and sounds are presentation. RTP, volatility, denomination, and the actual paytable explain how the game behaves.</p></div>
  <div class="info-grid"><article class="info-card"><span class="label">RTP</span><h4>Long-run return</h4><p>A 96% RTP describes a modeled average across an enormous number of spins. It does not predict a single session.</p></article><article class="info-card"><span class="label">VOLATILITY</span><h4>Shape of the swings</h4><p>Low volatility usually means smaller, more frequent wins. High volatility concentrates more value in fewer, larger hits.</p></article><article class="info-card"><span class="label">HIT FREQUENCY</span><h4>How often anything wins</h4><p>A high hit rate can still include many wins smaller than the amount wagered.</p></article><article class="info-card"><span class="label">PAYTABLE</span><h4>Read it before spinning</h4><p>Payouts vary by game and sometimes by denomination or configuration. There is no universal slot payout table.</p></article></div>
  <div class="two-col-detail" style="margin-top:12px"><table class="data-table"><thead><tr><th>What to check</th><th>Why it matters</th></tr></thead><tbody><tr><td><strong>RTP</strong></td><td>Higher is generally better when comparing otherwise similar games.</td></tr><tr><td><strong>Volatility</strong></td><td>Match it to the size of swings you are prepared to tolerate.</td></tr><tr><td><strong>Max-bet requirement</strong></td><td>Some jackpots or features require specific wagers. Do not assume.</td></tr><tr><td><strong>Bonus terms</strong></td><td>Free spins, multipliers, wilds, and jackpots distribute value differently.</td></tr></tbody></table><div class="callout"><h4>Best practical strategy</h4><p>Choose the game based on the paytable and budget, not on whether it looks “hot.” Set a fixed spend and time limit before the first spin. Chasing a loss does not improve the next spin.</p></div></div>
</div>`);

const poker=$('#poker');
if(poker){poker.innerHTML=`
  <div class="poker-visual"><div class="media-sprite media-poker" role="img" aria-label="Real poker table with cards and chips"></div></div>
  <div class="poker-intro"><p class="kicker">06 / POKER</p><h2>Poker is a decision game played through incomplete information.</h2><p>Unlike blackjack or roulette, the casino is not setting a fixed payoff against your hand. You are competing against other players while the room takes a rake. Position, hand strength, ranges, stack depth, pot odds, and opponent tendencies all matter.</p></div>
  <div class="poker-guide">
    <div class="poker-foundation">
      <article class="poker-panel"><h3>Position changes how many hands you can profitably play.</h3><p>Acting later gives you more information. That is why the Button and Cutoff can usually play wider ranges than early position.</p><div class="position-table"><div class="position-row head"><span>Position</span><span>What changes</span><span>Beginner adjustment</span></div><div class="position-row"><b>Early</b><span>More players still to act.</span><em>Open tighter. Favor stronger pairs, strong aces, and strong broadway hands.</em></div><div class="position-row"><b>Middle</b><span>Fewer players behind you.</span><em>Widen gradually, but still respect raises from early position.</em></div><div class="position-row"><b>Cutoff / Button</b><span>You act late after the flop.</span><em>Steal more blinds, value position, and pressure capped ranges.</em></div><div class="position-row"><b>Small blind</b><span>You are out of position postflop.</span><em>Play carefully. Calling too many marginal hands becomes expensive.</em></div><div class="position-row"><b>Big blind</b><span>You already have money invested.</span><em>Defend based on the price, opponent range, stack depth, and how well the hand realizes equity.</em></div></div></article>
      <article class="poker-panel"><h3>Hand rankings, with what they actually mean.</h3><div class="hand-grid"><div class="hand-card"><b>1. Royal flush</b><span>A-K-Q-J-10, same suit</span><small>The highest possible straight flush.</small></div><div class="hand-card"><b>2. Straight flush</b><span>Five consecutive cards, same suit</span><small>Example: 9-8-7-6-5 of hearts.</small></div><div class="hand-card"><b>3. Four of a kind</b><span>Four cards of one rank</span><small>Example: four Queens plus any kicker.</small></div><div class="hand-card"><b>4. Full house</b><span>Three of a kind plus a pair</span><small>Example: K-K-K-8-8.</small></div><div class="hand-card"><b>5. Flush</b><span>Five cards of one suit</span><small>Ranks do not need to be consecutive.</small></div><div class="hand-card"><b>6. Straight</b><span>Five consecutive ranks</span><small>Suits do not matter. Ace can be high or low.</small></div><div class="hand-card"><b>7. Three of a kind</b><span>Three matching ranks</span><small>Also called trips or a set depending on how it is made.</small></div><div class="hand-card"><b>8. Two pair</b><span>Two different pairs</span><small>The higher pair is compared first when tied.</small></div><div class="hand-card"><b>9. One pair</b><span>Two matching ranks</span><small>Kickers decide many close pair-versus-pair pots.</small></div><div class="hand-card"><b>10. High card</b><span>No made pair or better</span><small>The highest card, then kickers, break ties.</small></div></div></article>
    </div>
    <div class="poker-math">
      <article class="poker-panel"><h3>Common draw probabilities from the flop.</h3><p>These are practical Texas Hold'em numbers when your outs are clean.</p><table class="data-table draw-table"><thead><tr><th>Draw</th><th>Clean outs</th><th>Next card</th><th>By river</th></tr></thead><tbody><tr><td><strong>Flush draw</strong></td><td>9</td><td>19.1%</td><td>35.0%</td></tr><tr><td><strong>Open-ended straight draw</strong></td><td>8</td><td>17.0%</td><td>31.5%</td></tr><tr><td><strong>Gutshot straight draw</strong></td><td>4</td><td>8.5%</td><td>16.5%</td></tr><tr><td><strong>Pocket pair flops a set</strong></td><td>2 helpful ranks among unseen cards</td><td colspan="2">about 11.8% on the flop</td></tr></tbody></table><p class="poker-note"><strong>Fast estimate:</strong> multiply outs by about 2 for one card to come, or by about 4 when you will see both turn and river. It is a shortcut, not an exact calculation.</p></article>
      <aside class="prob-card"><span class="kicker">POT ODDS DECIDE WHETHER A DRAW IS WORTH THE PRICE</span><strong class="big">Call ÷ final pot</strong><p>That percentage is the minimum equity you need to break even on the call before rake and future betting.</p><div class="compare"><div><b>$20 call into a $100 pot</b><span>Final pot $120. Required equity = 16.7%.</span></div><div><b>$40 call into a $100 pot</b><span>Final pot $140. Required equity = 28.6%.</span></div></div><p style="margin-top:14px">A clean flush draw with one card to come is about 19.1%. The first call can be justified on raw odds. The second usually cannot without additional implied value.</p></aside>
    </div>
    <div><h3>Different kinds of poker reward different skills.</h3><div class="poker-variants" style="margin-top:12px"><article class="variant"><span>MOST COMMON</span><h4>Texas Hold'em</h4><p>Two private cards plus five community cards. Make the best five-card hand. Position and range reading dominate strategy.</p></article><article class="variant"><span>MORE COMBINATIONS</span><h4>Pot-Limit Omaha</h4><p>Four hole cards, but you must use exactly two of them and exactly three board cards. Draws are stronger and nut hands matter more.</p></article><article class="variant"><span>SPLIT POT</span><h4>Omaha Hi-Lo</h4><p>The pot can split between the best high hand and a qualifying low. Strong hands often compete for both halves.</p></article><article class="variant"><span>NO COMMUNITY BOARD</span><h4>Seven-Card Stud</h4><p>Players receive a mix of face-up and face-down cards. Memory and exposed cards become a major part of hand reading.</p></article><article class="variant"><span>CLASSIC DRAW GAME</span><h4>Five-Card Draw</h4><p>Each player starts with five private cards, then can replace cards once. Simpler structure, but betting tells matter more.</p></article></div></div>
    <div><h3>Common situations: use probability before instinct.</h3><div class="situation-grid" style="margin-top:12px"><article class="situation"><span class="spot">DRAWING HAND</span><b>You have 9 clean flush outs with one card to come.</b><p>If the price requires less than <strong>19.1%</strong> equity, a call can make mathematical sense. If the price requires much more, folding is usually correct.</p></article><article class="situation"><span class="spot">TOP PAIR</span><b>One pair is not automatically a stack-off hand.</b><p>Board texture, opponent range, bet size, stack depth, and kicker strength matter. A dry flop and a coordinated turn can tell very different stories.</p></article><article class="situation"><span class="spot">STRONG DRAW</span><b>Combo draws can have huge equity.</b><p>A hand with both flush and straight possibilities may have 12 to 15 useful outs, but double-counting overlapping outs is a common mistake. Count clean outs carefully.</p></article></div></div>
    <div class="two-col-detail"><table class="data-table"><thead><tr><th>Starting-hand family</th><th>What makes it valuable</th><th>Beginner use</th></tr></thead><tbody><tr><td><strong>Premium pairs</strong></td><td>Strong made hands before the flop.</td><td>Raise for value. Do not slow-play automatically.</td></tr><tr><td><strong>Strong broadway</strong></td><td>High-card strength and strong top-pair potential.</td><td>Value goes up in late position and against wide ranges.</td></tr><tr><td><strong>Small pairs</strong></td><td>Can flop a hidden set.</td><td>Best when stacks are deep enough to win more when you hit.</td></tr><tr><td><strong>Suited connectors</strong></td><td>Can make disguised straights and flushes.</td><td>Play better in position and with deeper stacks. They are not automatically profitable.</td></tr><tr><td><strong>Weak offsuit hands</strong></td><td>Often dominated and hard to realize equity.</td><td>Fold more of them, especially from early position.</td></tr></tbody></table><div class="callout"><h4>The practical poker checklist</h4><ul><li>What position am I in?</li><li>What range can my opponent reasonably have?</li><li>What price am I getting?</li><li>How many clean outs do I have?</li><li>Who benefits from the board?</li><li>What happens on the next street if I call?</li></ul></div></div>
  </div>`}

addDeepDive('#sports',`<div class="deep-dive sports-deep">
  <div class="section-title"><h3>Sports betting is a pricing problem before it is a prediction problem.</h3><p>You can be right about the team and still make a bad bet if the number is too expensive. Learn to translate odds into break-even probability and compare prices across books.</p></div>
  <table class="data-table"><thead><tr><th>American odds</th><th>Break-even probability</th><th>$100 stake profit</th><th>How to read it</th></tr></thead><tbody><tr><td><strong>-110</strong></td><td>52.38%</td><td>$90.91</td><td>Common spread or total price.</td></tr><tr><td><strong>+150</strong></td><td>40.00%</td><td>$150</td><td>Underdog price. Lower implied win probability.</td></tr><tr><td><strong>-200</strong></td><td>66.67%</td><td>$50</td><td>Favorite price. You risk more to win less.</td></tr></tbody></table>
  <div class="info-grid" style="margin-top:12px"><article class="info-card"><span class="label">LINE SHOPPING</span><h4>Half a point matters</h4><p>Getting +3 instead of +2.5 or -105 instead of -115 can meaningfully change long-run results.</p></article><article class="info-card"><span class="label">VIG</span><h4>The book's margin</h4><p>Two sides priced at -110 each imply more than 100% total probability. That extra percentage is the built-in hold before normalization.</p></article><article class="info-card"><span class="label">PARLAYS</span><h4>More legs, more hold</h4><p>Parlays create bigger advertised payouts because every leg usually has to win. They also magnify pricing mistakes.</p></article><article class="info-card"><span class="label">BANKROLL</span><h4>Think in units</h4><p>Using a consistent unit size makes performance easier to measure and reduces emotional bet sizing after wins or losses.</p></article></div>
</div>`);

const drawer=$('#helpDrawer'),backdrop=$('#drawerBackdrop');
function openHelp(){drawer.classList.add('open');backdrop.classList.add('open');drawer.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeHelp(){drawer.classList.remove('open');backdrop.classList.remove('open');drawer.setAttribute('aria-hidden','true');document.body.style.overflow=''}
['helpOpen','floatingHelp','startHere'].forEach(id=>$('#'+id)?.addEventListener('click',openHelp));
$('#helpClose')?.addEventListener('click',closeHelp);backdrop?.addEventListener('click',closeHelp);$('#helpJump')?.addEventListener('click',closeHelp);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeHelp()});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('seen');observer.unobserve(e.target)}}),{threshold:.08});
$$('.chapter>*,.game-selector>*,.odds-lab>*,.responsibility>*,.deep-dive>*').forEach(el=>{el.classList.add('reveal');observer.observe(el)});
if(window.Matter&&innerWidth>760){const canvas=$('#chips'),{Engine,Render,Runner,Bodies,Composite,Body}=Matter;const engine=Engine.create();engine.gravity.y=.18;const render=Render.create({canvas,engine,options:{width:innerWidth,height:innerHeight,pixelRatio:Math.min(devicePixelRatio||1,1.4),wireframes:false,background:'transparent'}});const floor=Bodies.rectangle(innerWidth/2,innerHeight+70,innerWidth+200,120,{isStatic:true,render:{visible:false}});Composite.add(engine.world,floor);const colors=['#c6a34e','#315e45','#8d3430','#dcd2b8'];for(let i=0;i<15;i++){const r=7+Math.random()*8,b=Bodies.circle(Math.random()*innerWidth,-100-Math.random()*innerHeight*.8,r,{restitution:.7,frictionAir:.01,render:{fillStyle:colors[i%colors.length],strokeStyle:'rgba(255,255,255,.18)',lineWidth:1}});Body.setAngularVelocity(b,(Math.random()-.5)*.05);Composite.add(engine.world,b)}Render.run(render);Runner.run(Runner.create(),engine)}
})();